Repository shader-slang/slang, pull requests merged in 2024-11, with the labels that each got.

#5472 Add `lerp` for wgsl.
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#5476 Enable a few more WGPU tests
  tests/compute/func-cbuffer-param.slang
  tests/expected-failure-github.txt
  tests/language-feature/tuple/tuple-parameter.slang
Labels: pr: non-breaking

#5479 Improve on spirv generation compile option
  examples/hello-world/main.cpp
  include/slang.h
  source/slang/slang-compiler-options.cpp
  source/slang/slang-compiler-options.h
  source/slang/slang-options.cpp
Labels: pr: non-breaking

#5480 Revert uint<->int implicit cast cost to prefer promotion to unsigned.
  source/slang/slang-ast-support-types.h
  tests/compute/unbounded-array-of-array-syntax.slang
  tests/language-feature/overload-resolution-signed-unsigned.slang
  tests/metal/atomic-texture-texture1d.slang
Labels: pr: breaking change

#5478 Allow enum cases to be used in attribute arguments.
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  tests/language-feature/enums/enum-in-binding.slang
Labels: pr: non-breaking

#5482 Add codeowners file
  .github/CODEOWNERS
Labels: pr: non-breaking

#5491 Fixing the wrong implementation of some math intrinsic
  source/slang/hlsl.meta.slang
  tests/expected-failure-github.txt
  tests/hlsl-intrinsic/scalar-float.slang
  tests/hlsl-intrinsic/vector-float.slang
Labels: pr: non-breaking

#5489 Fix issue of infinity float literal
  source/slang/slang-emit-wgsl.cpp
  source/slang/slang-emit-wgsl.h
  tests/bugs/inf-float-literal.slang
  tests/expected-failure-github.txt
Labels: pr: non-breaking

#5496 Fix system semantics of SV_GroupIndex
  source/slang/slang-ir-wgsl-legalize.cpp
  tests/compute/texture-simpler.slang
Labels: pr: non-breaking

#5495 Catch all exceptions
  cmake/CompilerFlags.cmake
  cmake/SlangTarget.cmake
  tools/CMakeLists.txt
Labels: pr: non-breaking

#5498 Legalize the Entry-point for WGSL
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-wgsl.cpp
  source/slang/slang-emit-wgsl.h
  source/slang/slang-ir-wgsl-legalize.cpp
  tests/compute/assoctype-lookup.slang
  tests/wgsl/nested-varying-input.slang
Labels: pr: non-breaking

#5483 Make structured buffers illegal parameter types in WGSL
  source/slang/slang-compiler.h
  source/slang/slang-ir-specialize-resources.cpp
  source/slang/slang-ir-specialize-resources.h
  source/slang/slang-type-layout.cpp
  tests/bugs/mutating/resource-specialization-inout.slang
  tests/compute/func-resource-param.slang
  tests/expected-failure-github.txt
  tests/optimization/func-resource-result/func-resource-result-simple.slang
Labels: pr: non-breaking

#5497 [WGSL] Enable arbitrary arrays in uniform buffers.
  source/slang/slang-emit.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-lower-buffer-element-type.cpp
  source/slang/slang-ir-lower-buffer-element-type.h
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-ir.cpp
  tests/compute/non-square-row-major.slang
  tests/expected-failure-github.txt
  tests/wgsl/uniform-array-2.slang
  tests/wgsl/uniform-array.slang
Labels: pr: non-breaking

#5494 Document raytracing functions
  source/slang/hlsl.meta.slang
Labels: kind:documentation, pr: non-breaking

#5508 Fix IntVal unification logic to insert type casts + buffer element lowering regression.
  source/slang/hlsl.meta.slang
  source/slang/slang-check-constraint.cpp
  source/slang/slang-ir-lower-buffer-element-type.cpp
  source/slang/slang-ir-util.cpp
  source/slang/slang-ir-util.h
  tests/autodiff/bug-1.slang
  tests/bindings/nested-parameter-block-3.slang
  tests/bugs/array-of-array-in-sb.slang
  tests/bugs/generic-type-duplication.slang
  tests/expected-failure-github.txt
  tests/language-feature/anonymous-struct.slang
  tests/language-feature/types/opaque/inout-param-opaque-type-in-struct.slang
  tests/language-feature/types/opaque/inout-param-opaque-type.slang
  tests/language-feature/types/opaque/out-param-opaque-type-in-struct.slang
  tests/language-feature/types/opaque/out-param-opaque-type.slang
  tests/language-feature/types/opaque/return-opaque-type-in-struct.slang
  tests/language-feature/types/opaque/return-opaque-type.slang
  tests/metal/groupshared-threadlocal-same-parameter.slang
Labels: pr: non-breaking

#5506 Fix the WGSL error about semantic when a nested struct is inlined
  source/slang/slang-ir-wgsl-legalize.cpp
Labels: pr: non-breaking

#5509 Fix CUDA prelude for makeMatrix
  prelude/slang-cuda-prelude.h
  tests/cuda/make-matrix.slang
Labels: pr: non-breaking

#5512 Fix the logic bug in spirv-emit compile option
  source/slang/slang-compiler-options.cpp
Labels: pr: non-breaking

#5513 Enable a bunch of WGPU tests
  tests/autodiff/diff-ptr-type-call.slang
  tests/autodiff/diff-ptr-type-loop.slang
  tests/autodiff/diff-ptr-type-smoke.slang
  tests/bugs/frexp.slang
  tests/bugs/gh-2959.slang
  tests/bugs/gh-471.slang
  tests/bugs/gh-566.slang
  tests/bugs/obfuscate-specialization-naming.slang
  tests/bugs/specialize-function-array-args.slang
  tests/compute/constant-buffer-memory-packing.slang
  tests/compute/func-cbuffer-param.slang
  tests/compute/func-param-legalize.slang
  tests/compute/matrix-layout.hlsl
  tests/expected-failure-github.txt
  tests/hlsl/packoffset.slang
  tests/language-feature/enums/nested-enum.slang
  tests/language-feature/generics/irwarray.slang
  tests/language-feature/generics/variadic-void.slang
  tests/language-feature/higher-order-functions/simple.slang
  tests/language-feature/swizzles/matrix-swizzle-write-single.slang
  tests/language-feature/swizzles/matrix-swizzle-write.slang
  tests/pipeline/compute/compute-system-values.slang
Labels: pr: non-breaking

#5517 Mark -embed-downstream-ir as experimental
  source/slang/slang-options.cpp
Labels: pr: non-breaking

#5523 lower permission level for format dispatch
  .github/workflows/slash-command-dispatch.yml
Labels: pr: non-breaking

#5524 Fix EHa flag compiler filtering
  cmake/CompilerFlags.cmake
  cmake/SlangTarget.cmake
  tools/CMakeLists.txt
Labels: pr: non-breaking

#5499 [WGSL] [WASM] Add reflection endpoints + Fix bit manipulation operations
  source/slang-wasm/slang-wasm-bindings.cpp
  source/slang-wasm/slang-wasm.cpp
  source/slang-wasm/slang-wasm.h
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-wgsl.cpp
Labels: pr: non-breaking

#5527 Require GL_EXT_samplerless_texture_functions only if needed
  source/slang/slang-core-module-textures.cpp
  tests/bugs/gh-5518.slang
Labels: pr: non-breaking

#5528 Use automatic coarse grained memory management in wasm binding.
  source/slang-wasm/slang-wasm-bindings.cpp
  source/slang-wasm/slang-wasm.cpp
  source/slang-wasm/slang-wasm.h
Labels: pr: non-breaking

#5525 Transfer offset decorations when legalizing laid-out structs
  source/slang/slang-legalize-types.cpp
  tests/autodiff/existential-1.slang
  tests/autodiff/existential-2.slang
  tests/autodiff/material/diff-bwd-falcor-material-system.slang
  tests/autodiff/material2/diff-bwd-falcor-material-system.slang
  tests/expected-failure-github.txt
Labels: pr: non-breaking

#5533 Refine codeowners for proposals
  .github/CODEOWNERS
Labels: pr: non-breaking

#5507 Reflection compiler option
  docs/command-line-slangc-reference.md
  include/slang-deprecated.h
  include/slang.h
  source/compiler-core/slang-pretty-writer.cpp
  source/compiler-core/slang-pretty-writer.h
  source/slang/slang-options.cpp
  source/slang/slang-reflection-json.cpp
  source/slang/slang-reflection-json.h
  source/slang/slang.cpp
  tools/slang-reflection-test/slang-reflection-test-main.cpp
Labels: pr: non-breaking

#5534 Use correct slang source dir for slang-rhi
  external/CMakeLists.txt
Labels: kind:bug, pr: non-breaking

#5536 Add wasm binding to get reflection json.
  .gitignore
  include/slang.h
  source/slang-wasm/slang-wasm-bindings.cpp
  source/slang-wasm/slang-wasm.cpp
  source/slang-wasm/slang-wasm.h
  source/slang/slang-reflection-json.cpp
Labels: pr: non-breaking

#5540 Fix two specialization bugs
  source/slang/slang-ir-link.cpp
  source/slang/slang-ir-specialize.cpp
Labels: pr: non-breaking

#5544 Push buffer load to end of access chain.
  source/slang/slang-emit.cpp
  source/slang/slang-ir-defer-buffer-load.cpp
  source/slang/slang-ir-defer-buffer-load.h
  source/slang/slang-ir.cpp
  tests/spirv/sb-load-2.slang
  tests/spirv/sb-load.slang
Labels: pr: non-breaking

#5546 Update CONTRIBUTION.md to clarify merge strategy.
  CONTRIBUTION.md
Labels: pr: non-breaking

#5554 WASM-binding: default to sm_6_6 when targeting hlsl.
  source/slang-wasm/slang-wasm.cpp
Labels: pr: non-breaking

#5557 [WGSL] [WASM] Fix WGSL emit for bitwise '&' and add bindings for thread group size
  source/slang-wasm/slang-wasm-bindings.cpp
  source/slang-wasm/slang-wasm.cpp
  source/slang-wasm/slang-wasm.h
  source/slang/slang-emit-wgsl.cpp
Labels: pr: new feature, pr: non-breaking

#5547 Copy headers into build dir at build time
  source/slang/CMakeLists.txt
Labels: pr: non-breaking

#5552 Simplify defer buffer load.
  source/slang/slang-ir-defer-buffer-load.cpp
Labels: pr: non-breaking

#5553 Make `getDependencyFilePath` return most unique identity.
  source/slang/slang-compiler.cpp
  source/slang/slang.cpp
Labels: pr: non-breaking

#5555 Proposal for a language version directive.
  docs/proposals/012-language-version-directive.md
Labels: pr: non-breaking

#5556 Remove 'raw' default construct insts for SPIRV emit
  source/slang/slang-emit.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-strip-default-construct.cpp
  source/slang/slang-ir-strip-default-construct.h
Labels: pr: non-breaking

#5560 Insert some casts for WGSL texture attribute queries
  source/slang/slang-core-module-textures.cpp
  tests/compute/texture-sampling-no-1d-arrays.slang
  tests/compute/texture-sampling-no-1d-arrays.slang.expected.txt
Labels: pr: non-breaking

#5569 Embed core module in wasm build.
  .gitignore
  CMakePresets.json
  source/compiler-core/slang-artifact-associated-impl.h
  source/slang-record-replay/record/slang-module.h
  source/slang/slang-ast-decl.h
  source/slang/slang-ast-expr.h
  source/slang/slang-ast-modifier.h
  source/slang/slang-ast-support-types.h
  source/slang/slang-ast-type.cpp
  source/slang/slang-ast-val.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-compiler.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir.cpp
  source/slang/slang-lower-to-ir.cpp
  tools/slang-cpp-extractor/diagnostic-defs.h
  tools/slang-cpp-extractor/parser.cpp
Labels: pr: non-breaking

#5576 Add `IDifferentiablePtrType` support for arrays
  source/slang/diff.meta.slang
  source/slang/slang-ir-autodiff.cpp
  source/slang/slang-ir-specialize-resources.cpp
  source/slang/slang-ir-spirv-legalize.cpp
  tests/autodiff/diff-ptr-type-array.slang
Labels: pr: non-breaking

#5585 Remove "GL_EXT_samplerless_texture_functions" from combined sampler funcs.
  source/slang/hlsl.meta.slang
  tests/glsl/sampler-fetch.slang
Labels: pr: non-breaking

#5568 Fix specialization constant miscompile in glsl mode.
  source/slang/slang-check-decl.cpp
  tests/spirv/specialization-constant.slang
Labels: pr: non-breaking

#5589 Implement semantics for WGSL
  source/slang/slang-ir-wgsl-legalize.cpp
Labels: pr: non-breaking

#5588 Markdown emphasis corrections
  CONTRIBUTION.md
  docs/64bit-type-support.md
  docs/cpu-target.md
  docs/cuda-target.md
  docs/design/experimental.md
  docs/gfx-user-guide/unsupported-formats.md
  docs/gpu-feature/derivatives-in-compute/derivatives-in-compute.md
  docs/user-guide/a2-01-spirv-target-specific.md
  docs/user-guide/a3-01-reference-capability-profiles.md
  extras/formatting.sh
Labels: pr: non-breaking

#5593 LanuageServer: fix signature help param range.
  source/slang/slang-ast-print.cpp
Labels: pr: non-breaking

#5594 Document math core lib functions
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#5597 Fix wgsl legalization around __ref parameter.
  source/slang/hlsl.meta.slang
  source/slang/slang-ir-wgsl-legalize.cpp
  tests/wgsl/workgroup-uniform-load.slang
Labels: pr: non-breaking

#5609 WGSL: Support isnan, isinf, etc..
  source/slang/hlsl.meta.slang
  tests/expected-failure-github.txt
  tests/hlsl-intrinsic/classify-float.slang
Labels: pr: non-breaking

#5611 Fix WGPU test by provding TEST_INPUT for outputBuffer
  tests/bugs/shadowed-lookup.slang
  tests/expected-failure-github.txt
Labels: pr: non-breaking

#5599 Minor core lib doc fixes
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#5616 Add link to metal docs and regen TOC
  docs/user-guide/a2-target-specific-features.md
  docs/user-guide/toc.html
Labels: kind:documentation, pr: non-breaking

#5620 Add Matrix overload for exp10() core lib function
  source/slang/hlsl.meta.slang
  tests/hlsl-intrinsic/matrix-double.slang
  tests/hlsl-intrinsic/matrix-double.slang.expected.txt
  tests/hlsl-intrinsic/matrix-float.slang
  tests/hlsl-intrinsic/matrix-float.slang.expected.txt
Labels: pr: non-breaking

#5619 Clarify stdlib-docgen example
  docs/stdlib-docgen.md
Labels: pr: non-breaking

#5615 Small docs corrections
  docs/target-compatibility.md
  docs/user-guide/09-targets.md
Labels: kind:documentation, pr: non-breaking

#5614 Refresh of disabled WGPU tests
  tests/autodiff/custom-intrinsic.slang
  tests/autodiff/diff-ptr-type-array.slang
  tests/bugs/atomic-coerce.slang
  tests/bugs/buffer-swizzle-store.slang
  tests/bugs/dxbc-double-problem.slang
  tests/bugs/frexp-double.slang
  tests/bugs/gh-3980.slang
  tests/bugs/gh-518.slang
  tests/bugs/op-assignment-unify-mat.slang
  tests/compute/atomics-buffer.slang
  tests/compute/atomics-groupshared.slang
  tests/compute/atomics.slang
  tests/compute/buffer-type-splitting.slang
  tests/compute/constant-buffer-memory-packing.slang
  tests/compute/constexpr.slang
  tests/compute/func-cbuffer-param.slang
  tests/compute/interface-shader-param-in-struct.slang
  tests/compute/interface-shader-param.slang
  tests/compute/loop-unroll.slang
  tests/compute/matrix-layout.hlsl
  tests/compute/texture-get-dimensions.slang
  tests/compute/texture-sampling.slang
  tests/compute/texture-simple.slang
  tests/compute/transcendental-double.slang
  tests/expected-failure-github.txt
  tests/hlsl-intrinsic/byte-address-buffer/byte-address-struct.slang
  tests/hlsl-intrinsic/classify-double.slang
  tests/hlsl-intrinsic/matrix-float.slang
  tests/hlsl-intrinsic/matrix-int.slang
  tests/hlsl-intrinsic/scalar-double-simple.slang
  tests/hlsl/packoffset.slang
  tests/language-feature/constants/static-const-in-generic-interface.slang
  tests/language-feature/enums/strongly-typed-id.slang
  tests/language-feature/generics/tuple.slang
  tests/language-feature/generics/variadic-0.slang
  tests/language-feature/shader-params/interface-shader-param-ordinary.slang
  tests/language-feature/swizzles/matrix-swizzle-write-array.slang
  tests/language-feature/swizzles/matrix-swizzle-write-swizzle.slang
  tests/optimization/func-resource-result/func-resource-result-complex.slang
Labels: pr: non-breaking

#5622 Add reuse and related files
  .reuse/dep5
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  LICENSES/Apache-2.0.txt
  LICENSES/CC-BY-4.0.txt
  LICENSES/LLVM-exception.txt
  LICENSES/MIT.txt
  LICENSES/UOI-NCSA.txt
  README.md
Labels: pr: non-breaking

#5608 Add datalayout for constant buffers.
  docs/user-guide/a2-01-spirv-target-specific.md
  source/slang/core.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-ast-builder.cpp
  source/slang/slang-ast-builder.h
  source/slang/slang-ast-type.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-shader.cpp
  source/slang/slang-check-type.cpp
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-hlsl.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-collect-global-uniforms.cpp
  source/slang/slang-ir-entry-point-uniforms.cpp
  source/slang/slang-ir-entry-point-uniforms.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-legalize-types.cpp
  source/slang/slang-ir-lower-buffer-element-type.cpp
  source/slang/slang-ir-optix-entry-point-uniforms.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-ir.h
  source/slang/slang-legalize-types.cpp
  source/slang/slang-legalize-types.h
  source/slang/slang-parameter-binding.cpp
  source/slang/slang-syntax.cpp
  source/slang/slang-type-layout.cpp
  source/slang/slang-type-layout.h
  source/slang/slang.cpp
  tests/bugs/vk-shift-uniform-issue.slang
  tests/reflection/binding-push-constant-gl.hlsl.expected
  tests/spirv/constant-buffer-layout.slang
  tests/spirv/push-constant-layout.slang
  tests/spirv/spec-constant-space.slang
Labels: pr: non-breaking

#5637 [Docs] Optional<T> - fix small typo on example
  docs/user-guide/03-convenience-features.md
Labels: pr: non-breaking

#5644 Enable core module embedding by default in CMake.
  .github/workflows/release-linux-glibc-2-17.yml
  .github/workflows/release.yml
  CMakeLists.txt
  CMakePresets.json
  docs/building.md
Labels: pr: non-breaking

#5643 ci: Use v1.11 of the release-downloader action
  .github/actions/common-setup/action.yml
  .github/workflows/falcor-compiler-perf-test.yml
  .github/workflows/vk-gl-cts-nightly.yml
Labels: pr: non-breaking

#5630 [AD] Add support for resolving custom derivatives where generic parameters can't be automatically inferred
  source/slang/slang-check-decl.cpp
  tests/autodiff/custom-derivative-enum-param.slang
  tests/autodiff/custom-intrinsic-1.slang
  tests/autodiff/custom-intrinsic-1.slang.expected.txt
  tests/diagnostics/custom-derivative-generic.slang
Labels: pr: non-breaking

#5650 Fix unused struct in sample shader
  examples/triangle/shaders.slang
Labels: pr: non-breaking

#5642 wgsl: Fix field semantics even if input struct doesn't need flattening
  source/slang/slang-ir-wgsl-legalize.cpp
  tests/expected-failure-github.txt
  tests/render/multiple-stage-io-locations.slang
  tests/render/multiple-stage-io-locations.slang.1.expected
  tests/render/multiple-stage-io-locations.slang.1.expected.png
  tests/render/multiple-stage-io-locations.slang.2.expected
  tests/render/multiple-stage-io-locations.slang.2.expected.png
  tests/render/multiple-stage-io-locations.slang.expected
  tests/render/multiple-stage-io-locations.slang.expected.png
Labels: pr: non-breaking

#5670 Fix issue where inter-stage parameters without semantics don't get location attributes
  source/slang/slang-ir-wgsl-legalize.cpp
  tests/render/multiple-stage-io-locations-without-user-semantics.slang
  tests/render/multiple-stage-io-locations-without-user-semantics.slang.expected
  tests/render/multiple-stage-io-locations-without-user-semantics.slang.expected.png
Labels: pr: non-breaking

#5641 Support interpolation modifiers for WGSL
  source/slang/slang-emit-wgsl.cpp
  source/slang/slang-emit-wgsl.h
  source/slang/slang-ir-wgsl-legalize.cpp
  tests/expected-failure-github.txt
  tests/render/nointerpolation.hlsl
  tests/render/nointerpolation.hlsl.3.expected
  tests/render/nointerpolation.hlsl.3.expected.png
Labels: pr: non-breaking

#5680 Fix issue with slang-embed & include ordering
  prelude/CMakeLists.txt
  prelude/slang-torch-prelude.h
  tools/slang-embed/slang-embed.cpp
Labels: pr: non-breaking

#5678 Enable Link-Time-Code-Generation for Release builds
  cmake/SlangTarget.cmake
Labels: pr: non-breaking

#5681 wgpu: Enable Metal-like legalization for byte addressible buffers
  source/slang/slang-emit.cpp
  tests/expected-failure-github.txt
  tests/hlsl-intrinsic/byte-address-buffer/byte-address-struct.slang
Labels: pr: non-breaking

#5682 WGSL: Fix issue where swizzle L-values are generated
  source/slang/slang-emit-c-like.cpp
  tests/expected-failure-github.txt
  tests/language-feature/swizzles/matrix-swizzle-write-array.slang
  tests/language-feature/swizzles/matrix-swizzle-write-swizzle.slang
Labels: pr: non-breaking

#5688 Update workflow YML files for renamed files
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  .github/workflows/compile-regression-test.yml
  .github/workflows/ensure-pr-label.yml
  .github/workflows/falcor-compiler-perf-test.yml
  .github/workflows/falcor-test.yml
  .github/workflows/push-benchmark-results.yml
  .github/workflows/release.yml
Labels: pr: non-breaking

#5694 wgsl: Conditionally enable some tests based on 'half' support
  tests/expected-failure-github.txt
  tests/language-feature/generics/tuple.slang
  tests/language-feature/generics/variadic-0.slang
Labels: pr: non-breaking

#5692 wgsl: signedness mismatch fixes
  source/slang/slang-ir-wgsl-legalize.cpp
  tests/expected-failure-github.txt
  tests/language-feature/enums/strongly-typed-id.slang
Labels: pr: non-breaking

#5700 Make ToC regeneration script path handling more robust
  docs/build_toc.sh
Labels: pr: non-breaking

#5663 Add missing WGSL intrinsics to test
  tests/autodiff/custom-intrinsic-1.slang
Labels: pr: non-breaking

#5672 Fix markdown mistakes on user guide
  docs/user-guide/02-conventional-features.md
Labels: pr: non-breaking

#5695 Support nonuniformEXT for GLSL
  source/slang/glsl.meta.slang
  tests/cross-compile/non-uniform-indexing.slang
Labels: pr: non-breaking

#5702 Explain why tests/autodiff/diff-ptr-type-array.slang is disabled for WGPU
  tests/autodiff/diff-ptr-type-array.slang
Labels: pr: non-breaking

#5696 Emit OpExecutionMode SpacingEqual for Domain stage
  source/slang/slang-emit-spirv.cpp
  tests/spirv/tessellation.slang
Labels: pr: non-breaking

#5707 fetch and extract prebuilt deps lazily
  cmake/FetchedSharedLibrary.cmake
Labels: pr: non-breaking
