Repository shader-slang/slang, pull requests merged in 2024-06, with the labels that each got.

#4249 Fix a bug on default initialization of interface typed value.
  source/slang/slang-lower-to-ir.cpp
  tests/language-feature/interfaces/zero-init-interface.slang
Labels: pr: non-breaking

#4237 Capabilities generator inclusive join and misc
  docs/command-line-slangc-reference.md
  source/core/core.natvis
  source/core/slang-uint-set.h
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  source/slang/slang-capability.cpp
  source/slang/slang-capability.h
  source/slang/slang-serialize-ast-type-info.h
  tools/slang-capability-generator/capability-generator-main.cpp
  tools/slang-capability-generator/slang-capability-diagnostic-defs.h
Labels: pr: non-breaking

#4254 Support different SPIRV versions.
  source/slang/slang-capabilities.capdef
  source/slang/slang-capability.cpp
  source/slang/slang-capability.h
  source/slang/slang-check-shader.cpp
  source/slang/slang-compiler.h
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-spirv-ops.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-glsl-legalize.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-restructure.cpp
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-ir-spirv-legalize.h
  source/slang/slang-ir-synthesize-active-mask.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-profile-defs.h
  source/slang/slang-spirv-val.cpp
  source/slang/slang.cpp
  tests/metal/texture.slang
  tests/spirv/array-resource.slang
  tests/spirv/discard.slang
  tests/spirv/spv-version.slang
  tools/gfx/vulkan/vk-api.h
  tools/gfx/vulkan/vk-device.cpp
Labels: pr: non-breaking

#4250 Prevent hoisting of non-hoistable instructions in non-function values with code
  source/slang/slang-ir-redundancy-removal.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-ir.h
  tests/bugs/generic-initializer-inlining.slang
Labels: pr: non-breaking

#4238 Metal Task Shader payload
  slang.h
  source/slang/hlsl.meta.slang
  source/slang/slang-emit-metal.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-metal-legalize.cpp
  source/slang/slang-ir.h
  tests/metal/simple-task.slang
Labels: pr: non-breaking

#4260 Add an option to disable source map in obfuscation
  slang.h
  source/slang/slang-compiler-options.h
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-options.cpp
Labels: pr: non-breaking

#4261 Fix performance issue in obfuscate source loc
  source/compiler-core/slang-source-map.cpp
Labels: pr: non-breaking

#4255 Print warning when operator<< shifting too much
  build/visual-studio/slang/slang.vcxproj
  build/visual-studio/slang/slang.vcxproj.filters
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-ir-operator-shift-overflow.cpp
  source/slang/slang-ir-operator-shift-overflow.h
  source/slang/slang-lower-to-ir.cpp
  tests/diagnostics/warning_operator_left_shift_overflow.slang
Labels: pr: non-breaking

#4268 Fixes incorrect profile string in hello-word example
  examples/hello-world/main.cpp
Labels: pr: non-breaking

#4242 Add APIs to get profile of compile time
  slang.h
  source/core/slang-performance-profiler.cpp
  source/core/slang-performance-profiler.h
  source/slang/slang-api.cpp
  source/slang/slang-compiler.h
  source/slang/slang.cpp
Labels: pr: non-breaking

#4270 Use memcpy to replace strncpy_s
  source/core/slang-performance-profiler.cpp
Labels: pr: non-breaking

#4272 initial set of lldb formatters
  source/core/core_lldb.py
Labels: pr: non-breaking

#4275 add 'override' keyword to getCompileTimeProfile
  source/slang/slang-compiler.h
Labels: pr: non-breaking

#4279 Avoid duplicating entry points in library
  source/slang/slang-compiler.cpp
Labels: pr: non-breaking

#4285 make String::trim consistent with String::trimStart/trimEnd
  source/core/slang-string.h
Labels: pr: non-breaking

#4282 Fix python syntax highlighting in slangpy chapter
  docs/user-guide/a1-02-slangpy.md
Labels: pr: non-breaking

#4287 work on gfx metal backend
  source/compiler-core/slang-metal-compiler.cpp
  source/slang/slang-reflection-api.cpp
  tools/gfx/metal/metal-base.h
  tools/gfx/metal/metal-buffer.cpp
  tools/gfx/metal/metal-buffer.h
  tools/gfx/metal/metal-command-buffer.cpp
  tools/gfx/metal/metal-command-buffer.h
  tools/gfx/metal/metal-command-encoder.cpp
  tools/gfx/metal/metal-command-encoder.h
  tools/gfx/metal/metal-command-queue.cpp
  tools/gfx/metal/metal-command-queue.h
  tools/gfx/metal/metal-device.cpp
  tools/gfx/metal/metal-device.h
  tools/gfx/metal/metal-fence.cpp
  tools/gfx/metal/metal-fence.h
  tools/gfx/metal/metal-framebuffer.cpp
  tools/gfx/metal/metal-framebuffer.h
  tools/gfx/metal/metal-helper-functions.cpp
  tools/gfx/metal/metal-helper-functions.h
  tools/gfx/metal/metal-pipeline-state.cpp
  tools/gfx/metal/metal-pipeline-state.h
  tools/gfx/metal/metal-query.cpp
  tools/gfx/metal/metal-query.h
  tools/gfx/metal/metal-render-pass.cpp
  tools/gfx/metal/metal-render-pass.h
  tools/gfx/metal/metal-resource-views.cpp
  tools/gfx/metal/metal-resource-views.h
  tools/gfx/metal/metal-sampler.cpp
  tools/gfx/metal/metal-sampler.h
  tools/gfx/metal/metal-shader-object-layout.cpp
  tools/gfx/metal/metal-shader-object-layout.h
  tools/gfx/metal/metal-shader-object.cpp
  tools/gfx/metal/metal-shader-object.h
  tools/gfx/metal/metal-shader-program.cpp
  tools/gfx/metal/metal-shader-program.h
  tools/gfx/metal/metal-swap-chain.cpp
  tools/gfx/metal/metal-swap-chain.h
  tools/gfx/metal/metal-texture.cpp
  tools/gfx/metal/metal-texture.h
  tools/gfx/metal/metal-transient-heap.cpp
  tools/gfx/metal/metal-transient-heap.h
  tools/gfx/metal/metal-util.cpp
  tools/gfx/metal/metal-util.h
  tools/gfx/metal/metal-vertex-layout.h
  tools/gfx/render.cpp
Labels: pr: non-breaking

#4283 Remove unnecessary call to __requireComputeDerivative
  source/slang/glsl.meta.slang
  source/slang/hlsl.meta.slang
Labels: kind:cleanup, pr: non-breaking

#4276 Fix build warnings and treat warnings as error on CI
  .github/workflows/ci.yml
  source/slang/CMakeLists.txt
  source/slang/slang-check-impl.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-bit-field-accessors.cpp
  source/slang/slang-ir-legalize-types.cpp
  source/slang/slang-ir-link.cpp
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-ir-uniformity.cpp
  source/slang/slang-options.cpp
  tools/slang-capability-generator/capability-generator-main.cpp
Labels: kind:cleanup, pr: non-breaking

#4284 Fix typo in 06-interfaces-generics.md
  docs/user-guide/06-interfaces-generics.md
Labels: pr: non-breaking

#4295 Capabilities System: Inclusive join logic bug
  tools/slang-capability-generator/capability-generator-main.cpp
Labels: pr: non-breaking

#4297 Fixed profile string per request in pr#4268
  examples/hello-world/main.cpp
Labels: pr: non-breaking

#4269 Precompute UIntSet from individual capabilities inside generator
  source/core/slang-uint-set.h
  source/slang/slang-capability.cpp
  source/slang/slang-capability.h
  tools/slang-capability-generator/capability-generator-main.cpp
Labels: pr: non-breaking

#4299 Improve documentation and example formatting consistency
  docs/cuda-target.md
  docs/doc-system.md
  docs/faq.md
  examples/autodiff-texture/draw-quad.slang
  examples/autodiff-texture/reconstruct.slang
  examples/autodiff-texture/train.slang
  examples/gpu-printing/printing.slang
  examples/model-viewer/shaders.slang
  examples/shader-toy/example-effect.slang
  examples/shader-toy/shader-toy.slang
Labels: pr: non-breaking

#4302 Make CTS failure report more obvious
  .github/workflows/vk-gl-cts-nightly.yml
Labels: pr: non-breaking

#4309 Small SPIRV emit cleanup around vector element extract.
  source/slang/slang-emit-spirv.cpp
Labels: pr: non-breaking

#4310 Support HLSL `.mips` syntax.
  source/slang/hlsl.meta.slang
  tests/hlsl/texture-mips-operator.slang
Labels: pr: non-breaking

#4306 Adding functional test for GLSL texture functions
  tests/glsl-intrinsic/intrinsic-texture.slang
Labels: kind:testing, pr: non-breaking

#4308 Metal system value overhaul.
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-metal.cpp
  source/slang/slang-emit-metal.h
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-metal-legalize.cpp
  tests/metal/stage-in-2.slang
  tests/metal/stage-in.slang
  tests/metal/system-val-conversion.slang
Labels: pr: non-breaking

#4312 Disallow certain types of decls in `interface` to provide better diagnostic message.
  source/slang/slang-parser.cpp
Labels: pr: non-breaking

#4216 Add initial draft auto-diff basics and IR overview documents
  docs/design/autodiff/basics.md
  docs/design/autodiff/ir-overview.md
Labels: pr: non-breaking

#4303 SPIRV `Block` decoration fixes.
  source/slang/slang-capability.cpp
  source/slang/slang-capability.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-compiler.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-glsl-legalize.cpp
  source/slang/slang-ir-specialize-target-switch.cpp
  source/slang/slang-options.cpp
  source/slang/slang-profile.h
  tests/bindings/glsl-parameter-blocks.slang
  tests/bugs/gh-941.slang
  tests/bugs/vk-image-atomics.slang
  tests/bugs/vk-structured-buffer-binding.hlsl
  tests/bugs/vk-structured-buffer-binding.hlsl.glsl
  tests/cross-compile/barycentrics.slang
  tests/cross-compile/barycentrics.slang.glsl
  tests/cross-compile/dual-source-blending.slang
  tests/cross-compile/early-depth-stencil.hlsl
  tests/cross-compile/early-depth-stencil.hlsl.glsl
  tests/cross-compile/early-depth-stencil.hlsl.hlsl
  tests/cross-compile/glsl-empty-struct-param-field.slang
  tests/cross-compile/glsl-empty-struct-param-field.slang.glsl
  tests/cross-compile/half-conversion.slang
  tests/cross-compile/non-uniform-indexing.slang
  tests/cross-compile/non-uniform-indexing.slang.glsl
  tests/cross-compile/sign.slang
  tests/cross-compile/sign.slang.glsl
  tests/cross-compile/sign.slang.hlsl
  tests/cross-compile/sv-coverage.slang
  tests/cross-compile/sv-coverage.slang.glsl
  tests/cross-compile/unknown-image-format.slang
  tests/cross-compile/unknown-image-format.slang.glsl
  tests/cross-compile/vector-comparison.slang
  tests/cross-compile/vector-comparison.slang.glsl
  tests/cross-compile/vk-push-constant-set.slang
  tests/diagnostics/constant-buffer-unsized.slang
  tests/hlsl/raster-order-resource.slang
  tests/spirv/block-decoration.slang
  tests/spirv/varying-out-index.slang
Labels: pr: non-breaking

#4322 Fix typos in the docs
  docs/design/capabilities.md
  docs/design/casting.md
  docs/design/coding-conventions.md
  docs/design/decl-refs.md
  docs/design/existential-types.md
  docs/design/interfaces.md
  docs/design/ir.md
Labels: pr: non-breaking

#4324 [gfx] Metal graphics support
  slang-gfx.h
  source/compiler-core/slang-metal-compiler.cpp
  tools/gfx/metal/metal-buffer.h
  tools/gfx/metal/metal-command-buffer.cpp
  tools/gfx/metal/metal-command-buffer.h
  tools/gfx/metal/metal-command-encoder.cpp
  tools/gfx/metal/metal-command-encoder.h
  tools/gfx/metal/metal-device.cpp
  tools/gfx/metal/metal-framebuffer.cpp
  tools/gfx/metal/metal-framebuffer.h
  tools/gfx/metal/metal-helper-functions.h
  tools/gfx/metal/metal-pipeline-state.cpp
  tools/gfx/metal/metal-pipeline-state.h
  tools/gfx/metal/metal-render-pass.cpp
  tools/gfx/metal/metal-render-pass.h
  tools/gfx/metal/metal-shader-program.cpp
  tools/gfx/metal/metal-shader-program.h
  tools/gfx/metal/metal-swap-chain.cpp
  tools/gfx/metal/metal-swap-chain.h
  tools/gfx/metal/metal-texture.h
  tools/gfx/metal/metal-util.cpp
  tools/gfx/metal/metal-util.h
  tools/gfx/metal/metal-vertex-layout.cpp
  tools/gfx/metal/metal-vertex-layout.h
  tools/gfx/vulkan/vk-fence.cpp
Labels: pr: non-breaking

#4311 Support all integer typed indices in StructuredBuffer Load/Store/[].
  source/slang/hlsl.meta.slang
  tests/language-feature/overload-resolution.slang
  tests/spirv/i64-structured-buffer.slang
  tests/spirv/subgroup-size-2.slang
Labels: pr: non-breaking

#4318 Fix SPIRV emit for `Flat` decoration and TessLevel builtin.
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-glsl-legalize.cpp
  tests/spirv/flat.slang
  tests/spirv/tess-factor.slang
Labels: pr: non-breaking

#4294 Partial implementation of static_assert
  source/slang/core.meta.slang
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-autodiff-fwd.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  tests/language-feature/static_assert.slang
Labels: pr: non-breaking

#4323 Address glslang ordering requirments for 'derivative_group_*NV'
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit.cpp
  tests/bugs/gh-4305.slang
  tests/glsl-intrinsic/intrinsic-texture.slang
  tools/gfx/vulkan/vk-api.h
  tools/gfx/vulkan/vk-device.cpp
Labels: pr: non-breaking

#4334 Fix `GetAttributeAtVertex` for spirv and glsl targets.
  source/slang/hlsl.meta.slang
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-glsl-legalize.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  tests/diagnostics/get-vertex-attribute.slang
  tests/spirv/get-vertex-attribute.slang
Labels: pr: non-breaking

#4335 Remove duplicate `VkPhysicalDeviceComputeShaderDerivativesFeaturesNV` extension structure in vk-api.h
  tools/gfx/vulkan/vk-api.h
  tools/gfx/vulkan/vk-device.cpp
Labels: pr: non-breaking

#4329 Support integer typed textures for GLSL
  source/slang/glsl.meta.slang
  source/slang/hlsl.meta.slang
  tests/diagnostics/int-texture-sample.slang
  tests/glsl-intrinsic/intrinsic-texture.slang
Labels: pr: non-breaking

#4333 Metal: Support and test integer type textures
  source/slang/slang-emit-metal.cpp
  tests/metal/byte-address-buffer.slang
  tests/metal/texture.slang
Labels: pr: non-breaking

#4336 SPIRV backend: add support for tessellation stages.
  source/slang/hlsl.meta.slang
  source/slang/slang-compiler.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-glsl-legalize.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-specialize-target-switch.cpp
  source/slang/slang-parameter-binding.cpp
  tests/spirv/tessellation.slang
Labels: pr: non-breaking

#4337 [gfx] Metal improvements
  tools/gfx/metal/metal-command-encoder.cpp
  tools/gfx/metal/metal-device.cpp
  tools/gfx/metal/metal-fence.cpp
  tools/gfx/metal/metal-helper-functions.h
  tools/gfx/metal/metal-pipeline-state.cpp
  tools/gfx/metal/metal-resource-views.cpp
Labels: pr: non-breaking

#4339 Fix global value inlining for spirv_asm blocks.
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-spirv-legalize.cpp
  tests/spirv/static-array-spv-asm.slang
Labels: pr: non-breaking

#4341 Fix crash when using optional type in a generic.
  source/slang/slang-ir-lower-optional-type.cpp
  tests/bugs/optional-generic.slang
  tests/bugs/optional.slang
Labels: pr: non-breaking

#4344 Add option to preserve shader parameter declaration in output SPIRV.
  docs/command-line-slangc-reference.md
  slang.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-dce.cpp
  source/slang/slang-ir-dce.h
  source/slang/slang-ir-link.cpp
  source/slang/slang-ir-specialize.cpp
  source/slang/slang-ir-ssa-simplification.cpp
  source/slang/slang-ir-ssa-simplification.h
  source/slang/slang-options.cpp
  tests/spirv/preserve-param.slang
Labels: pr: non-breaking

#4346 Fix duplicate SPIRV decorations.
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-spirv-legalize.cpp
Labels: pr: non-breaking

#4349 Fix crash on invalid entrypoint varying parameter.
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-parameter-binding.cpp
  tests/bugs/invalid-entrypoint-param.slang
Labels: pr: non-breaking

#4353 Fix incorrect drop of decoration when translating glsl global var toe ntrypoint param
  source/slang/slang-ir-translate-glsl-global-var.cpp
  tests/bugs/gh-4345.slang
Labels: pr: non-breaking

#4354 Add compiler option to treat enum types as unscoped.
  slang.h
  source/slang/slang-lookup.cpp
  source/slang/slang-options.cpp
  source/slang/slang-parser.cpp
  tests/language-feature/enums/anonymous-enum.slang
  tests/language-feature/enums/unscoped-enum-option.slang
Labels: pr: non-breaking

#4355 Extend the COM-based API to support whole program compilation.
  build/visual-studio/slang-unit-test-tool/slang-unit-test-tool.vcxproj
  build/visual-studio/slang-unit-test-tool/slang-unit-test-tool.vcxproj.filters
  slang.h
  source/slang-capture-replay/slang-composite-component-type.cpp
  source/slang-capture-replay/slang-composite-component-type.h
  source/slang-capture-replay/slang-entrypoint.cpp
  source/slang-capture-replay/slang-entrypoint.h
  source/slang-capture-replay/slang-module.cpp
  source/slang-capture-replay/slang-module.h
  source/slang-capture-replay/slang-type-conformance.cpp
  source/slang-capture-replay/slang-type-conformance.h
  source/slang/slang-compiler.h
  source/slang/slang.cpp
  tools/slang-unit-test/unit-test-get-target-code.cpp
Labels: pr: non-breaking

#3987 Add slangc flag to `-zero-initialize` all variables
  slang.h
  source/slang/core.meta.slang
  source/slang/slang-ast-builder.cpp
  source/slang/slang-ast-builder.h
  source/slang/slang-ast-expr.h
  source/slang/slang-ast-support-types.h
  source/slang/slang-ast-type.h
  source/slang/slang-check-conformance.cpp
  source/slang/slang-check-constraint.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-inheritance.cpp
  source/slang/slang-check-overload.cpp
  source/slang/slang-check-shader.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-options.cpp
  source/slang/slang.cpp
  tests/language-feature/struct-field-initializers/struct-field-initializer-static.slang
  tests/language-feature/zero-initialize/IDefaultExplicit-wrapper-type.slang
  tests/language-feature/zero-initialize/IDefaultExplicit.slang
  tests/language-feature/zero-initialize/IDefaultExplicitGenerics.slang
  tests/language-feature/zero-initialize/generic.slang
  tests/language-feature/zero-initialize/missing-zero-init.slang
  tests/language-feature/zero-initialize/regular.slang
  tests/language-feature/zero-initialize/static-struct-field-init-list.slang
  tests/language-feature/zero-initialize/static-struct-field-init.slang
  tests/language-feature/zero-initialize/struct-array-some-member-missing-init.slang
  tests/language-feature/zero-initialize/struct-array.slang
  tests/language-feature/zero-initialize/struct-no-zero-init.slang
  tests/language-feature/zero-initialize/struct-some-member-init-missing-zero-init.slang
  tests/language-feature/zero-initialize/struct-some-zero-init.slang
  tests/language-feature/zero-initialize/struct.slang
  tests/spirv/debug-type-pointer.slang
Labels: pr: new feature, pr: breaking change

#4359 Add constant folding for % operator.
  source/slang/slang-ir-sccp.cpp
Labels: pr: non-breaking

#4241 Capability System: Implicit capability upgrade warning/error
  docs/command-line-slangc-reference.md
  slang.h
  source/core/slang-uint-set.cpp
  source/core/slang-uint-set.h
  source/slang/glsl.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-ast-support-types.h
  source/slang/slang-capabilities.capdef
  source/slang/slang-capability.cpp
  source/slang/slang-capability.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-shader.cpp
  source/slang/slang-compiler.cpp
  source/slang/slang-compiler.h
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-doc-markdown-writer.cpp
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-glsl.h
  source/slang/slang-ir-glsl-legalize.cpp
  source/slang/slang-ir-specialize-target-switch.cpp
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-options.cpp
  source/slang/slang-profile-defs.h
  source/slang/slang.cpp
  tests/bugs/sample-grad-clamp-lod.slang
  tests/compute/dynamic-dispatch-14.slang
  tests/feature/source-embed/source-embed-1.slang
  tests/language-feature/capability/capability5.slang
  tests/language-feature/capability/specializeTargetSwitch.slang
  tests/language-feature/capability/testing-framework-with-profiles.slang
  tests/pipeline/rasterization/get-attribute-at-vertex.slang
  tests/pipeline/rasterization/mesh/component-write.slang
  tests/pipeline/rasterization/mesh/dead-loop.slang
  tests/pipeline/rasterization/mesh/hlsl-syntax.slang
  tests/pipeline/rasterization/mesh/nested-component-write.slang
  tests/pipeline/rasterization/mesh/simple.slang
  tests/pipeline/rasterization/mesh/swizzled-store.slang
  tests/pipeline/rasterization/mesh/task-groupshared.slang
  tests/pipeline/rasterization/mesh/task-simple.slang
  tests/pipeline/ray-tracing/trace-ray-inline.slang
  tests/slang-extension/atomic-float-byte-address-buffer-cross.slang
  tests/vkray/rayquery-closesthit.slang
  tools/render-test/render-test-main.cpp
  tools/render-test/slang-support.cpp
Labels: pr: non-breaking

#4362 Fix emit logic for getElementPtr.
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-ir-metal-legalize.cpp
  source/slang/slang-serialize-ast-type-info.h
  tests/metal/vector-get-element-ptr.slang
Labels: pr: non-breaking

#4361 Delete glsl_vulkan and glsl_vulkan_one_desc targets.
  slang.h
  source/compiler-core/slang-artifact-desc-util.cpp
  source/core/slang-type-convert-util.cpp
  source/core/slang-type-text-util.cpp
  source/slang/slang-compiler.cpp
  source/slang/slang-compiler.h
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-type-layout.cpp
  source/slang/slang.cpp
Labels: pr: breaking change

#4327 Enable full test on macos.
  .github/github_test.sh
  tests/compute/column-major.slang
  tests/expected-failure-github.txt
Labels: pr: non-breaking

#4371 Implement Sampler2D for CPP target
  source/slang/slang-type-layout.cpp
  tests/bindings/hlsl-to-cpp-combined.slang
Labels: pr: non-breaking

#4378 Fix cuda/cpp/metal crash when using GLSL shader inputs
  source/slang/slang-ir-explicit-global-context.cpp
  tests/glsl/matrix-mul.slang
Labels: pr: non-breaking

#4372 capture/replay: implement infrastructure for capture
  build/visual-studio/slang/slang.vcxproj
  build/visual-studio/slang/slang.vcxproj.filters
  source/core/slang-stream.h
  source/slang-capture-replay/api_callId.h
  source/slang-capture-replay/capture-manager.cpp
  source/slang-capture-replay/capture-manager.h
  source/slang-capture-replay/output-stream.cpp
  source/slang-capture-replay/output-stream.h
  source/slang-capture-replay/parameter-encoder.cpp
  source/slang-capture-replay/parameter-encoder.h
  source/slang-capture-replay/slang-global-session.cpp
  source/slang-capture-replay/slang-global-session.h
Labels: pr: non-breaking

#4364 Remove `IRHLSLExportDecoration` and `IRKeepAliveDecoration` for non-CUDA/Torch targets
  source/slang/slang-emit.cpp
  source/slang/slang-ir-pytorch-cpp-binding.cpp
  source/slang/slang-ir-pytorch-cpp-binding.h
  source/slang/slang-lower-to-ir.cpp
  tests/autodiff/hlsl-torch-cross-compile.slang
Labels: pr: non-breaking

#4368 SPIR-V `SV_InstanceId` support in pixel shader
  source/slang/slang-ir-glsl-legalize.cpp
  source/slang/slang-ir-util.h
  source/slang/slang-parameter-binding.cpp
  tests/bugs/gh-3087-multi-entry-point.slang
  tests/bugs/gh-3087.slang
Labels: pr: non-breaking

#4374 Metal: misc fixes and enable more tests.
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  source/slang/slang-emit-hlsl.cpp
  source/slang/slang-emit-metal.cpp
  source/slang/slang-emit-metal.h
  source/slang/slang-ir-byte-address-legalize.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir.cpp
  tests/autodiff-dstdlib/determinant.slang
  tests/autodiff-dstdlib/dstdlib-mul-mat-mat.slang
  tests/autodiff-dstdlib/dstdlib-mul-mat-vec.slang
  tests/autodiff-dstdlib/dstdlib-mul-vec-mat.slang
  tests/autodiff-dstdlib/dstdlib-sqrt.slang
  tests/autodiff/custom-intrinsic.slang
  tests/autodiff/reverse-matrix-ops.slang
  tests/bindings/nested-parameter-block-2.slang
  tests/bugs/negative-literal.slang
  tests/bugs/op-assignment-unify-mat.slang
  tests/compute/byte-address-buffer.slang
  tests/compute/cbuffer-legalize.slang
  tests/compute/frem.slang
  tests/compute/matrix-layout-structured-buffer.slang
  tests/compute/non-square-column-major.slang
  tests/compute/non-square-row-major.slang
  tests/compute/non-square-row-major.slang.expected.txt
  tests/compute/structured-buffer-of-matrices.slang
  tests/compute/texture-simple.slang
  tests/hlsl-intrinsic/bit-cast.slang
  tests/hlsl-intrinsic/f16tof32.slang
  tests/hlsl-intrinsic/f32tof16.slang
  tests/hlsl-intrinsic/scalar-float.slang
  tests/hlsl-intrinsic/size-of/align-of-2.slang
  tests/hlsl-intrinsic/size-of/align-of-3.slang
  tests/hlsl-intrinsic/size-of/align-of-generic.slang
  tests/hlsl-intrinsic/size-of/align-of.slang
  tests/hlsl-intrinsic/size-of/size-of-2.slang
  tests/hlsl-intrinsic/size-of/size-of-3.slang
  tests/hlsl-intrinsic/size-of/size-of-generic.slang
  tests/hlsl-intrinsic/size-of/size-of.slang
  tests/hlsl-intrinsic/vector-float.slang
  tests/hlsl/packoffset.slang
  tests/ir/scalar-truncate.slang
  tests/language-feature/bit-cast/struct-bit-cast.slang
  tests/language-feature/bitfield/sizeof.slang
  tests/metal/stage-in.slang
Labels: pr: non-breaking

#4382 fix the clang/gcc warning
  source/slang/slang-capability.cpp
Labels: pr: non-breaking

#4385 Implement for metal `SV_GroupIndex`
  source/slang/slang-ir-legalize-varying-params.cpp
  source/slang/slang-ir-legalize-varying-params.h
  source/slang/slang-ir-metal-legalize.cpp
  tests/bugs/frexp-double.slang
  tests/bugs/frexp.slang
  tests/bugs/gh-3980.slang
  tests/compute/texture-simpler.slang
  tests/language-feature/higher-order-functions/simple.slang
  tests/language-feature/swizzles/matrix-swizzle-write-array.slang
  tests/language-feature/swizzles/matrix-swizzle-write-single.slang
  tests/language-feature/swizzles/matrix-swizzle-write-swizzle.slang
  tests/language-feature/swizzles/matrix-swizzle-write.slang
  tests/metal/thread_position_in_threadgroup.slang
  tests/pipeline/compute/compute-system-values.slang
Labels: pr: non-breaking

#4390 [Metal] Support SV_TargetN.
  source/slang/slang-ir-metal-legalize.cpp
  source/slang/slang-parameter-binding.cpp
  source/slang/slang-parameter-binding.h
  tests/metal/sv_target.slang
Labels: pr: non-breaking

#4391 Make unknown attributes a warning instead of an error.
  source/slang/slang-diagnostic-defs.h
Labels: pr: non-breaking

#4392 [Metal] Fix global constant array emit.
  source/slang/slang-emit-c-like.cpp
  tests/compute/static-const-array.slang
  tests/compute/static-const-matrix-array.slang
  tests/compute/static-const-vector-array.slang
Labels: pr: non-breaking

#4396 Improve Direct SPIRV Backend Test Coverage & Fix Associated Bug
  source/slang/hlsl.meta.slang
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-profile.cpp
  source/slang/slang-profile.h
  tests/gpu-feature/texture/query/footprint/nv-shader-texture-footprint-simple.slang
  tests/gpu-feature/texture/query/footprint/nv-shader-texture-footprint.slang
  tests/hlsl-intrinsic/ray-tracing/rt-pipeline-intrinsics-ahit.slang
  tests/hlsl-intrinsic/ray-tracing/rt-pipeline-intrinsics-chit.slang
  tests/hlsl-intrinsic/ray-tracing/rt-pipeline-intrinsics-int.slang
  tests/hlsl-intrinsic/ray-tracing/rt-pipeline-intrinsics-miss.slang
  tests/hlsl-intrinsic/ray-tracing/rt-pipeline-intrinsics-rgen.slang
  tests/vkray/anyhit.slang
  tests/vkray/callable.slang
Labels: pr: non-breaking

#4398 Remove inline that crashes old glibc version
  source/slang/slang-capability.cpp
Labels: pr: non-breaking

#4403 Fixed gl_LocalInvocationIndex being uvec3 instead of uint
  source/slang/glsl.meta.slang
Labels: pr: non-breaking

#4397 Feature/capture
  source/core/slang-stream.h
  source/slang-capture-replay/capture-manager.cpp
  source/slang-capture-replay/capture-manager.h
  source/slang-capture-replay/capture_utility.h
  source/slang-capture-replay/output-stream.cpp
  source/slang-capture-replay/parameter-encoder.cpp
  source/slang-capture-replay/parameter-encoder.h
  source/slang-capture-replay/slang-global-session.cpp
  source/slang-capture-replay/slang-global-session.h
Labels: pr: non-breaking

#4417 Metal: Implement fix for non vector4 texture Load/Sample
  source/slang/hlsl.meta.slang
  tests/metal/texture.slang
Labels: pr: non-breaking

#4425 Disambiguate int type matrix multiply
  source/slang/hlsl.meta.slang
  tests/bugs/gh-4414.slang
Labels: pr: non-breaking

#4412 Add capture logic to other interfaces.
  source/slang-capture-replay/api_callId.h
  source/slang-capture-replay/capture-manager.cpp
  source/slang-capture-replay/capture-manager.h
  source/slang-capture-replay/parameter-encoder.cpp
  source/slang-capture-replay/parameter-encoder.h
  source/slang-capture-replay/slang-composite-component-type.cpp
  source/slang-capture-replay/slang-composite-component-type.h
  source/slang-capture-replay/slang-entrypoint.cpp
  source/slang-capture-replay/slang-entrypoint.h
  source/slang-capture-replay/slang-filesystem.cpp
  source/slang-capture-replay/slang-filesystem.h
  source/slang-capture-replay/slang-global-session.cpp
  source/slang-capture-replay/slang-module.cpp
  source/slang-capture-replay/slang-module.h
  source/slang-capture-replay/slang-session.cpp
  source/slang-capture-replay/slang-session.h
  source/slang-capture-replay/slang-type-conformance.cpp
  source/slang-capture-replay/slang-type-conformance.h
Labels: pr: non-breaking

#4436 Implementing `tbuffer` layout(s)
  source/slang/slang-emit-hlsl.cpp
  source/slang/slang-emit-metal.cpp
  source/slang/slang-type-layout.cpp
  source/slang/slang-type-layout.h
  tests/hlsl/tbuffer.slang
Labels: pr: non-breaking

#4432 Added float2x2 cast to float4 (and vise versa)
  source/slang/core.meta.slang
  tests/hlsl-intrinsic/matrix-cast-to-vector.slang
Labels: pr: non-breaking

#4419 Add case to `emitVectorReshape` for when using a `vector<M, N>` type with `T` value
  source/slang/slang-ir.cpp
  tests/bugs/gh-4411.slang
Labels: pr: non-breaking

#4471 Add intrinsic for `IsHelperLane()` in HLSL
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  tests/hlsl-intrinsic/helper-lane.slang
Labels: pr: non-breaking

#4465 Metal: function return type address space checks
  source/slang/slang-ir-specialize-address-space.cpp
  tests/optimization/func-resource-result/func-resource-result-simple.slang
Labels: pr: non-breaking

#4473 Support atomic intrinsics for Metal
  source/slang/hlsl.meta.slang
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-metal.cpp
  source/slang/slang-ir-inst-defs.h
  tests/bugs/atomic-coerce.slang
  tests/compute/atomics-groupshared.slang
  tests/compute/atomics.slang
  tests/metal/atomic-intrinsics.slang
Labels: pr: non-breaking

#4408 Expand upon existing `ImageSubscript` support (Metal, GLSL, SPIRV)
  build/visual-studio/slang/slang.vcxproj
  build/visual-studio/slang/slang.vcxproj.filters
  source/slang/hlsl.meta.slang
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-metal.cpp
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-glsl-legalize.cpp
  source/slang/slang-ir-glsl-legalize.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-legalize-image-subscript.cpp
  source/slang/slang-ir-legalize-image-subscript.h
  source/slang/slang-ir-util.cpp
  source/slang/slang-ir-util.h
  source/slang/slang-ir.cpp
  tests/compute/texture-subscript-multisample.slang
  tests/compute/texture-subscript.slang
Labels: pr: non-breaking

#4485 Fix Texture2DMSArray
  source/slang/glsl.meta.slang
  source/slang/hlsl.meta.slang
  tests/compute/texture-subscript-multisample.slang
Labels: pr: non-breaking

#4478 Remove returned-array-legalization pass for metal
  source/slang/slang-emit.cpp
  tests/bugs/gh-2959.slang
  tests/metal/groupshared-threadlocal-same-parameter.slang
Labels: pr: non-breaking

#4480 Cache address-space-legalization of `kIROp_Store`
  source/slang/slang-ir-specialize-address-space.cpp
  tests/language-feature/types/opaque/inout-param-opaque-type-in-struct.slang
  tests/language-feature/types/opaque/inout-param-opaque-type.slang
  tests/language-feature/types/opaque/out-param-opaque-type-in-struct.slang
  tests/language-feature/types/opaque/out-param-opaque-type.slang
  tests/language-feature/types/opaque/return-opaque-type-in-struct.slang
Labels: pr: non-breaking

#4482 Include examples in default build
  .github/workflows/ci.yml
  .github/workflows/compile-regression-test.yml
  .github/workflows/falcor-compiler-perf-test.yml
  .github/workflows/falcor-test.yml
  CMakeLists.txt
  premake5.lua
Labels: pr: non-breaking

#4496 switch from ubuntu-18 to centos-7 build
  .github/workflows/release-linux-glibc-2-17.yml
  deps/target-deps.json
Labels: pr: non-breaking

#4499 Extend `countbits` intrinsic for vector types
  source/slang/glsl.meta.slang
  source/slang/hlsl.meta.slang
  tests/hlsl-intrinsic/countbits.slang
Labels: pr: non-breaking

#4501 Enable upload asset for old glibc build
  .github/workflows/release-linux-glibc-2-17.yml
Labels: pr: non-breaking

#4498 Update the coding convention document.
  docs/design/coding-conventions.md
Labels: kind:documentation, pr: non-breaking

#4505 Fix `WorkgroupSize()` compiler failure
  source/slang/glsl.meta.slang
  source/slang/slang-ir-translate-glsl-global-var.cpp
  tests/bugs/gh-4504.slang
Labels: pr: non-breaking

#4491 Nested initialization list in struct crash fix
  source/slang/slang-check-expr.cpp
  tests/language-feature/nested-empty-initializer-list.slang
Labels: pr: non-breaking

#4503 Adding a note about the keyword, class.
  docs/user-guide/02-conventional-features.md
Labels: pr: non-breaking

#4509 Implement CheckAccessFullyMapped
  source/slang/hlsl.meta.slang
  tests/hlsl-intrinsic/texture/partial-resident-texture.slang
Labels: pr: non-breaking

#4507 Parse scope for local variable declaration
  source/slang/slang-parser.cpp
  tests/bugs/gh-4457.slang
Labels: pr: non-breaking
