Repository shader-slang/slang, pull requests merged in 2024-07, with the labels that each got.

#4514 Add clearer information about how to submit a proposal document.
  docs/proposals/README.md
Labels: pr: non-breaking

#4513 Set debug working directory for slangc.exe
  CMakeLists.txt
Labels: pr: non-breaking

#4516 Error out when constructing tensor views from tensors with 0 stride.
  prelude/slang-torch-prelude.h
  source/slang/slang-ir-pytorch-cpp-binding.cpp
Labels: pr: breaking change

#4522 Supply SPIRV capability for textureQueryLod
  source/slang/glsl.meta.slang
  tests/spirv/texture-query-lod.slang
Labels: pr: non-breaking

#4524 Support HLSL `.sample` operators for MS textures
  source/slang/hlsl.meta.slang
  tests/hlsl/texture-sample-operator.slang
Labels: pr: non-breaking

#4523 Fix the type error in kIROp_RWStructuredBufferLoad
  source/slang/slang-emit-glsl.cpp
  tests/compute/byte-address-buffer-array.slang
Labels: pr: non-breaking

#4510 Emit errors when invalid capabilities are used
  source/slang/glsl.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-modifier.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-stdlib-textures.cpp
  tests/glsl-intrinsic/intrinsic-texture.slang
  tests/language-feature/capability/capability6.slang
Labels: pr: non-breaking

#4535 Add README.md and LICENSE to binary windows and macos packages
  .github/workflows/macos.yml
  .github/workflows/release-macos.yml
  .github/workflows/release-windows.yml
  .github/workflows/windows.yml
Labels: pr: non-breaking

#4534 Add specializations for 1 vectors in functions using the $N glsl intrinsic placement
  source/slang/hlsl.meta.slang
  tests/bugs/gh-4533.slang
Labels: pr: non-breaking

#4550 Correct type for double log10
  prelude/slang-cpp-scalar-intrinsics.h
  tests/hlsl-intrinsic/scalar-double-log10.slang
  tests/hlsl-intrinsic/scalar-double-log10.slang.expected.txt
Labels: pr: non-breaking

#4551 Correctly set launch parameters of Metal `tests\compute\semantic.slang` test
  tests/compute/semantic.slang
Labels: pr: non-breaking

#4526 Treat global variables and parameters as non-differentiable when checking derivative data-flow
  source/slang/slang-ir-check-differentiability.cpp
  tests/autodiff/warn-on-shared-memory-access.slang
Labels: pr: breaking change

#4561 Language server performance and document symbol fix.
  source/slang/slang-check-decl.cpp
  source/slang/slang-language-server-document-symbols.cpp
  source/slang/slang.cpp
Labels: pr: non-breaking

#4559 Fix the issue in emitFloatCast
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-util.cpp
  source/slang/slang-ir-util.h
  tests/bugs/gh-4556.slang
Labels: pr: non-breaking

#4563 Add intrinsic for clock2x32ARB
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  tests/glsl-intrinsic/clock-read.slang
Labels: pr: non-breaking

#4470 Add documentation of the auto-diff type system and relevant decorations
  docs/design/autodiff/decorators.md
  docs/design/autodiff/ir-overview.md
  docs/design/autodiff/types.md
Labels: pr: non-breaking

#4515 Fix Lexer to recognize swizzling on an integer scalar value
  source/compiler-core/slang-lexer.cpp
  tests/hlsl-intrinsic/scalar-swizzling.slang
Labels: pr: non-breaking

#4530 Warnings for uninitialized values
  build/visual-studio/slang/slang.vcxproj
  build/visual-studio/slang/slang.vcxproj.filters
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-ir-use-uninitialized-out-param.cpp
  source/slang/slang-ir-use-uninitialized-values.cpp
  source/slang/slang-ir-use-uninitialized-values.h
  source/slang/slang-lower-to-ir.cpp
  tests/bugs/gh-4434.slang
  tests/bugs/gh-4441.slang
  tests/diagnostics/ctor-ordinary-retval-legal.slang
  tests/diagnostics/uninitialized-out.slang
  tests/diagnostics/uninitialized.slang
Labels: pr: breaking change

#4572 Change to use cmake in centos7 build
  .github/workflows/release-linux-glibc-2-17.yml
Labels: pr: non-breaking

#4592 Neaten filecheck output for non-passing nested-parameter-block test
  tests/bindings/nested-parameter-block-2.slang
Labels: pr: non-breaking

#4594 Do not unnecessarily build llvm tools
  external/build-llvm.sh
Labels: pr: non-breaking

#4596 A couple of small fixes to cmake releases
  .github/workflows/ci.yml
  .github/workflows/release.yml
  CMakePresets.json
Labels: pr: breaking change

#4590 Emit spirv insts in the right sections.
  source/slang/slang-emit-spirv.cpp
Labels: pr: non-breaking

#4525 Various fixes around differentiable member associations `[DerivativeMember(<diff-member>)]`
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-diagnostic-defs.h
  tests/autodiff/diff-make-struct-with-associations.slang
  tests/autodiff/diff-make-struct-with-associations.slang.expected.txt
  tests/autodiff/generic-impl-jvp.slang
  tests/autodiff/getter-setter.slang
  tests/autodiff/struct-without-diff-associations.slang
Labels: pr: breaking change

#4490 Support status argument for GatherXXX
  source/slang/hlsl.meta.slang
  tests/hlsl-intrinsic/texture/texture-intrinsics.slang
Labels: pr: non-breaking

#4566 Add GL_EXT_ray_tracing_position_fetch capability
  source/slang/slang-capabilities.capdef
Labels: pr: non-breaking

#4584 Add `float16` support for the `TorchTensor` type
  prelude/slang-torch-prelude.h
Labels: pr: non-breaking

#4536 Fixes to Metal Input parameters and Output value input/output semantics
  source/slang/hlsl.meta.slang
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-legalize-varying-params.cpp
  source/slang/slang-ir-legalize-varying-params.h
  source/slang/slang-ir-metal-legalize.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-parameter-binding.cpp
  source/slang/slang-parameter-binding.h
  tests/compute/compile-time-loop.slang
  tests/compute/constexpr.slang
  tests/compute/discard-stmt.slang
  tests/compute/texture-sampling.slang
  tests/metal/atomic-intrinsics.slang
  tests/metal/nested-struct-fragment-input.slang
  tests/metal/nested-struct-fragment-output.slang
  tests/metal/nested-struct-multi-entry-point-vertex.slang
  tests/metal/no-struct-vertex-output.slang
  tests/metal/stage-in-2.slang
  tests/metal/sv_target-complex-1.slang
  tests/metal/sv_target-complex-2.slang
Labels: pr: non-breaking

#4544 Implement non member function atomic texture support
  source/compiler-core/slang-gcc-compiler-util.cpp
  source/slang/hlsl.meta.slang
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-legalize-extract-from-texture-access.cpp
  source/slang/slang-ir-legalize-extract-from-texture-access.h
  source/slang/slang-ir-legalize-image-subscript.cpp
  source/slang/slang-ir-legalize-is-texture-access.cpp
  source/slang/slang-ir-legalize-is-texture-access.h
  tests/compute/atomics-buffer.slang
  tests/compute/atomics-invalid-dest-type.slang
  tests/hlsl-intrinsic/atomic/atomic-intrinsics.slang
  tests/metal/atomic-texture-buffer.slang
  tests/metal/atomic-texture-texture1d.slang
  tests/metal/atomic-texture-texture2d.slang
  tests/metal/atomic-texture-texture3d.slang
Labels: pr: non-breaking

#4557 Add user guide section on user-defined attributes.
  docs/user-guide/03-convenience-features.md
  docs/user-guide/toc.html
Labels: pr: non-breaking

#4587 Add reflection API for functions.
  docs/user-guide/09-reflection.md
  docs/user-guide/toc.html
  slang.h
  source/slang-capture-replay/slang-entrypoint.cpp
  source/slang-capture-replay/slang-entrypoint.h
  source/slang/slang-compiler.h
  source/slang/slang-reflection-api.cpp
  source/slang/slang.cpp
  tools/slang-unit-test/unit-test-function-reflection.cpp
Labels: pr: non-breaking

#4588 Fix the invalid spirv generation for matrix cast
  source/slang/slang-emit-spirv.cpp
  tests/bugs/gh-4556.slang
Labels: pr: non-breaking

#4600 Specialize address space during spirv legalization.
  CMakeLists.txt
  cmake/CompilerFlags.cmake
  docs/building.md
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-glsl-legalize.cpp
  source/slang/slang-ir-metal-legalize.cpp
  source/slang/slang-ir-specialize-address-space.cpp
  source/slang/slang-ir-specialize-address-space.h
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-ir.h
  tests/spirv/address-space-specialize.slang
Labels: pr: non-breaking

#4598 Update CONTRIBUTION.md after CI side changes
  CONTRIBUTION.md
Labels: kind:documentation, pr: non-breaking

#4601 Delete unused build scripts.
  .github/github_test.sh
  .github/workflows/release.yml
  github_build.sh
  github_macos_build.sh
Labels: pr: non-breaking

#4609 Cope with failed version parsing
  CMakeLists.txt
  cmake/GitVersion.cmake
  cmake/SlangTarget.cmake
  slang-tag-version.h
  slang-tag-version.h.in
  source/slang/CMakeLists.txt
  source/slang/slang.cpp
Labels: kind:bug, pr: non-breaking

#4571 Implement 64-bit version of clockARB
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  tests/glsl-intrinsic/clock-read.slang
Labels: pr: non-breaking

#4612 More precise handing of option dependencies
  .github/workflows/vk-gl-cts-nightly.yml
  CMakeLists.txt
  cmake/SlangTarget.cmake
Labels: pr: non-breaking

#4613 Statically link MSVC runtime
  CMakeLists.txt
  CMakePresets.json
  external/build-llvm.sh
Labels: pr: non-breaking

#4611 populate slang-tag-version with cmake
  slang-tag-version.h
  slang.h
  source/slang/CMakeLists.txt
  source/slang/slang.cpp
Labels: pr: non-breaking

#4614 Fix missing include for static slang
  source/slang/CMakeLists.txt
Labels: kind:bug, pr: non-breaking

#4602 Fix issue with synthesizing `Differential` type for self-differential generic types
  source/slang/slang-check-expr.cpp
  tests/autodiff/auto-differential-type-generic.slang
  tests/autodiff/auto-differential-type-generic.slang.expected.txt
Labels: pr: non-breaking

#4618 Fix incorrect codegen when returning initializer list as existential value.
  CMakePresets.json
  docs/building.md
  source/slang/slang-check-conversion.cpp
  tests/language-feature/interfaces/default-construct-conformance.slang
Labels: pr: non-breaking

#4619 Update CONTRIBUTION.md for path to slang-test.exe
  CONTRIBUTION.md
Labels: kind:documentation, pr: non-breaking

#4623 Start autodiff pass if `IRDerivativeMemberDecoration` is found
  source/slang/slang-emit.cpp
  tests/compute/struct-autodiff-default-init.slang
Labels: pr: non-breaking

#4629 Fix release configuration for macOS.
  .github/workflows/release.yml
  CMakeLists.txt
Labels: pr: non-breaking

#4628 Move if_let syntax to convenience-features section
  docs/user-guide/03-convenience-features.md
  docs/user-guide/06-interfaces-generics.md
  docs/user-guide/toc.html
Labels: pr: non-breaking

#4644 Fix gfx/metal uniform data binding and memory leaks.
  tools/gfx/d3d11/d3d11-shader-object.cpp
  tools/gfx/metal/metal-command-buffer.h
  tools/gfx/metal/metal-device.h
  tools/gfx/metal/metal-pipeline-state.h
  tools/gfx/metal/metal-shader-object.cpp
  tools/gfx/metal/metal-shader-program.h
Labels: pr: non-breaking

#4640 SCCP instead of CFG to clear unused blocks using `isTextureAccess` with `static_assert`
  source/slang/slang-emit.cpp
  source/slang/slang-ir-legalize-is-texture-access.cpp
  source/slang/slang-ir-legalize-is-texture-access.h
  tests/hlsl-intrinsic/atomic/atomic-intrinsics.slang
Labels: pr: non-breaking

#4638 Fix issue with synthesized `__init` methods not getting added to witness table
  source/slang/slang-check-decl.cpp
  tests/compute/assoctype-nested-lookup.slang
Labels: pr: non-breaking

#4626 Warnings function parameters
  source/slang/slang-ir-use-uninitialized-values.cpp
  tests/autodiff/material2/MxWeights.slang
  tests/bugs/generic-param-cast.slang
  tests/bugs/specialize-existential-in-generic.slang
  tests/compute/assoctype-func-param.slang
  tests/compute/assoctype-nested-lookup.slang
  tests/compute/dynamic-dispatch-17.slang
  tests/compute/empty-struct2.slang
  tests/compute/generic-closer.slang
  tests/compute/generic-default-arg.slang
  tests/compute/transitive-interface.slang
  tests/cuda/cuda-array-layout.slang
  tests/diagnostics/interfaces/anyvalue-size-validation.slang
  tests/diagnostics/uninitialized-globals.slang
  tests/diagnostics/uninitialized-local-variables.slang
  tests/diagnostics/uninitialized-out-parameters.slang
  tests/diagnostics/uninitialized-out.slang.expected
  tests/diagnostics/uninitialized-use-functions.slang
  tests/language-feature/types/is-on-type.slang
Labels: pr: non-breaking

#4660 Fix minimal-optimization flag use with texture atomics
  source/slang/slang-ir-legalize-is-texture-access.cpp
  tests/bugs/interlocked-add-uint-int.slang
Labels: pr: non-breaking

#4668 Fix latex rendering errors in auto-diff docs
  docs/design/autodiff/basics.md
Labels: pr: non-breaking

#4642 Use slang-glslang.dll for spirv-validation
  source/compiler-core/slang-downstream-compiler.h
  source/compiler-core/slang-glslang-compiler.cpp
  source/slang-glslang/slang-glslang.cpp
  source/slang-glslang/slang-glslang.h
  source/slang-llvm/slang-llvm.cpp
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-spirv-val.cpp
  source/slang/slang-spirv-val.h
Labels: pr: non-breaking

#4646 Add slang-llvm and slang-glslang readmes
  source/slang-llvm/README.md
Labels: pr: non-breaking

#4649 Remove generated file from source and build at build time
  cmake/SlangTarget.cmake
  source/slang/CMakeLists.txt
  source/slang/slang-spirv-core-grammar-embed.cpp
  tools/slang-spirv-embed-generator/spirv-embed-generator-main.cpp
Labels: pr: non-breaking

#4669 Squash warnings on gcc and clang
  external/CMakeLists.txt
  source/slang/slang-ir-use-uninitialized-values.cpp
Labels: pr: non-breaking

#4651 Reduce duplication in slang lib builds
  cmake/SlangTarget.cmake
  source/slang/CMakeLists.txt
Labels: pr: non-breaking

#4670 Adjust how `slang` and `slangc` uses a `profile` to manage the stage of an entry-point
  source/slang/slang-capability.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-shader.cpp
  source/slang/slang-compiler.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-options.cpp
  tests/language-feature/capability/conflicting-profile-stage-for-entry-point.slang
Labels: pr: breaking change

#4673 Add unexpected end of input error to lexer
  source/compiler-core/slang-lexer-diagnostic-defs.h
  source/compiler-core/slang-lexer.cpp
  tests/diagnostics/end-of-input.slang
Labels: kind:enhancement, pr: non-breaking

#4672 Correctly parse multiple escaped newlines
  source/compiler-core/slang-lexer.cpp
  tests/bugs/gh-4667.slang
Labels: pr: non-breaking

#4666 Initial implementation for decl-tree reflection API
  include/slang.h
  source/slang-capture-replay/slang-global-session.cpp
  source/slang-capture-replay/slang-global-session.h
  source/slang-capture-replay/slang-module.cpp
  source/slang-capture-replay/slang-module.h
  source/slang/slang-compiler.h
  source/slang/slang-reflection-api.cpp
  source/slang/slang.cpp
  tools/slang-unit-test/unit-test-decl-tree-reflection.cpp
Labels: pr: non-breaking

#4677 Fix bug with uninitiailized variable warnings in nested scopes
  source/slang/slang-ir-use-uninitialized-values.cpp
  tests/diagnostics/uninitialized-local-variables.slang
  tests/hlsl-intrinsic/size-of/align-of-3.slang
  tests/hlsl-intrinsic/size-of/size-of-3.slang
Labels: pr: non-breaking

#4527 Support OpDebugTypePointer for struct member pointer
  source/slang/slang-emit-spirv-ops-debug-info-ext.h
  source/slang/slang-emit-spirv.cpp
  tests/spirv/debug-type-pointer.slang
Labels: pr: non-breaking

#4665 Separating slang-test in CI for emit-spirv-via-glsl
  .github/workflows/ci.yml
Labels: kind:cleanup, pr: non-breaking

#4680 Warnings for uninitialized fields in constructors
  source/slang/slang-ast-decl.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-use-uninitialized-values.cpp
  source/slang/slang-lower-to-ir.cpp
  tests/compute/struct-default-init.slang
  tests/diagnostics/uninitialized-fields.slang
  tests/language-feature/struct-field-initializers/struct-field-initializer.slang
Labels: pr: non-breaking

#4653 Allow CPP/CUDA/Metal to lower/legalize buffer-elements to support column_major/row_major.
  prelude/slang-cuda-prelude.h
  source/slang/slang-compiler.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-lower-buffer-element-type.cpp
  tests/compute/column-major.slang
  tests/compute/column-major.slang.expected.txt
  tests/compute/constant-buffer-memory-packing.slang
Labels: pr: non-breaking

#4655 Metal: `Interlocked` (atomic) member function support for buffers
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  source/slang/slang-emit.cpp
  source/slang/slang-ir-byte-address-legalize.cpp
  source/slang/slang-ir-byte-address-legalize.h
  tests/hlsl-intrinsic/byte-address-buffer-atomics.slang
  tests/metal/atomic-texture-buffer.slang
  tests/metal/atomic-texture-texture1d.slang
  tests/metal/atomic-texture-texture2d.slang
  tests/metal/atomic-texture-texture3d.slang
Labels: pr: non-breaking

#4632 Always run autodiff-decoration-stripping-pass
  source/slang/slang-emit.cpp
  source/slang/slang-ir-autodiff.cpp
Labels: pr: non-breaking

#4658 Fix LLVM compile error on Windows
  include/slang.h
Labels: kind:cleanup, pr: non-breaking

#4691 Fix the issue of name mangling
  source/slang/slang-mangle.cpp
  tests/diagnostics/illegal-func-decl-module.slang
  tests/diagnostics/illegal-func-decl.slang
Labels: pr: non-breaking

#4671 Support parameter block in metal shader objects.
  include/slang.h
  source/slang/slang-compiler.h
  source/slang/slang-parameter-binding.cpp
  source/slang/slang-reflection-api.cpp
  source/slang/slang-type-layout.cpp
  source/slang/slang-type-layout.h
  source/slang/slang.cpp
  tests/autodiff/global-param-hoisting.slang
  tests/bindings/nested-parameter-block-2.slang
  tests/bugs/buffer-swizzle-store.slang
  tests/compute/entry-point-uniform-params.slang
  tests/compute/parameter-block.slang
  tests/compute/texture-subscript.slang
  tests/language-feature/shader-params/entry-point-uniform-params.slang
  tests/language-feature/types/opaque/inout-param-opaque-type-in-struct.slang
  tests/language-feature/types/opaque/out-param-opaque-type-in-struct.slang
  tests/language-feature/types/opaque/return-opaque-type-in-struct.slang
  tools/gfx/metal/metal-command-encoder.cpp
  tools/gfx/metal/metal-device.cpp
  tools/gfx/metal/metal-device.h
  tools/gfx/metal/metal-shader-object-layout.cpp
  tools/gfx/metal/metal-shader-object-layout.h
  tools/gfx/metal/metal-shader-object.cpp
  tools/gfx/metal/metal-shader-object.h
Labels: pr: non-breaking

#4690 Fix for invalid swizzle causing crash
  source/slang/slang-check-expr.cpp
  tests/bugs/invalid-swizzle-count.slang
Labels: pr: non-breaking

#4703 Add Metal to user-guide/09-targets.md
  docs/user-guide/09-targets.md
  docs/user-guide/toc.html
Labels: pr: non-breaking

#4678 Simplify `CapabilitySet` Diagnostic Printing
  source/slang/slang-ast-base.h
  source/slang/slang-capability.cpp
  source/slang/slang-capability.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-shader.cpp
  source/slang/slang-diagnostic-defs.h
  tests/language-feature/capability/capability7.slang
  tests/language-feature/capability/capabilitySimplification1.slang
  tests/language-feature/capability/capabilitySimplification2.slang
  tests/language-feature/capability/capabilitySimplification3.slang
Labels: pr: non-breaking

#4708 Warn if providing explicit bindings to a object using uniform locations
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-parameter-binding.cpp
  tests/bugs/gh-4700.slang
Labels: pr: non-breaking

#4712 Install the missing public headers in release package
  CMakeLists.txt
Labels: pr: non-breaking

#4697 Print SPIRV validation error message
  source/slang-glslang/slang-glslang.cpp
Labels: pr: non-breaking

#4705 Fix for `ConstantBuffer<T[...]>` struct member access causing a crash
  source/slang/slang-ir-lower-buffer-element-type.cpp
  tests/bugs/gh-4704.slang
Labels: pr: non-breaking

#4713 Allow only specific spv storage classes for binding decoration
  source/slang/slang-emit-spirv.cpp
  tests/bindings/binding-spv-storage-class.slang
Labels: pr: non-breaking

#4731 Cleanup global memory allocations on shutdown.
  include/slang.h
  source/compiler-core/slang-spirv-core-grammar.h
  source/core/slang-performance-profiler.cpp
  source/core/slang-performance-profiler.h
  source/slang/slang-api.cpp
  source/slang/slang-capability.h
  source/slang/slang.cpp
  source/slangc/main.cpp
  tools/render-test/render-test-main.cpp
  tools/slang-capability-generator/capability-generator-main.cpp
  tools/slang-reflection-test/slang-reflection-test-main.cpp
  tools/slang-spirv-embed-generator/spirv-embed-generator-main.cpp
  tools/slang-test/slang-test-main.cpp
  tools/slangd/main.cpp
  tools/test-server/test-server-main.cpp
Labels: pr: non-breaking

#4737 Fix checking of var with matrix layout modifier.
  source/slang/slang-check-decl.cpp
  tests/bugs/gh-4633.slang
Labels: pr: non-breaking

#4735 Add missing make_bool intrinsics in cuda prelude.
  prelude/slang-cuda-prelude.h
Labels: pr: non-breaking

#4389 Add generic descriptor indexing intrinsic
  include/slang.h
  source/slang/hlsl.meta.slang
  source/slang/slang-ast-type.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-glsl-legalize.cpp
  source/slang/slang-ir-glsl-legalize.h
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-specialize-resources.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-ir.h
  source/slang/slang-reflection-api.cpp
  source/slang/slang-type-layout.cpp
  tests/slang-extension/dynamic-resource-gl.slang
  tests/slang-extension/dynamic-resource-gl.slang.1.expected
  tools/slang-reflection-test/slang-reflection-test-main.cpp
Labels: pr: non-breaking

#4728 Support 1-dimensional matrix for HLSL
  source/slang/core.meta.slang
  tests/bugs/gh-4395.slang
Labels: pr: non-breaking

#4739 Allow implicitly casting enum types to bool.
  source/slang/core.meta.slang
  tests/language-feature/enums/implicit-cast-to-bool.slang
Labels: pr: non-breaking

#4736 Don't trigger CI on doc changes.
  .github/workflows/ci.yml
  .github/workflows/compile-regression-test.yml
  .github/workflows/ensure-pr-label.yml
  .github/workflows/falcor-compiler-perf-test.yml
  .github/workflows/falcor-test.yml
  .github/workflows/release.yml
Labels: pr: non-breaking

#4729 Fix around extensions and `IDifferentiable` requirement synthesis.
  source/slang/slang-ast-builder.h
  source/slang/slang-ast-type.cpp
  source/slang/slang-check-decl.cpp
  tests/bugs/extended-type-in-param.slang
Labels: pr: non-breaking

#4710 Overhaul IR lowering of pointer types.
  source/slang/core.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-ast-builder.cpp
  source/slang/slang-ast-builder.h
  source/slang/slang-ast-type.cpp
  source/slang/slang-ast-type.h
  source/slang/slang-capabilities.capdef
  source/slang/slang-check-conversion.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-cuda.cpp
  source/slang/slang-emit-cuda.h
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-glsl.h
  source/slang/slang-emit-hlsl.cpp
  source/slang/slang-emit-hlsl.h
  source/slang/slang-emit-metal.cpp
  source/slang/slang-emit-metal.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-any-value-marshalling.cpp
  source/slang/slang-ir-autodiff-primal-hoist.cpp
  source/slang/slang-ir-composite-reg-to-mem.cpp
  source/slang/slang-ir-explicit-global-context.cpp
  source/slang/slang-ir-glsl-liveness.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-lower-buffer-element-type.cpp
  source/slang/slang-ir-simplify-for-emit.cpp
  source/slang/slang-ir-specialize-address-space.cpp
  source/slang/slang-ir-specialize-address-space.h
  source/slang/slang-ir-specialize.cpp
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-ir.h
  source/slang/slang-legalize-types.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-syntax.cpp
  source/slang/slang-type-system-shared.h
  tests/spirv/pointer-array-2.slang
  tests/spirv/pointer-data-marshal.slang
Labels: pr: non-breaking

#4684 Add a proposal for new AST/IR serialization
  docs/proposals/implementation/ast-ir-serialization.md
Labels: pr: non-breaking

#4702 Add `_Internal`/`External` atom enforcement and validation.
  source/slang/slang-capabilities.capdef
  source/slang/slang-capability.cpp
  source/slang/slang-capability.h
  source/slang/slang-check-modifier.cpp
  source/slang/slang-diagnostic-defs.h
  tests/language-feature/capability/capability4.slang
  tests/language-feature/capability/capability5.slang
  tests/language-feature/capability/capability6.slang
  tests/language-feature/capability/usingInternalCapabilityWarning.slang
  tools/slang-capability-generator/capability-generator-main.cpp
  tools/slang-capability-generator/slang-capability-diagnostic-defs.h
Labels: pr: non-breaking

#4277 Allow swizzle on n-dimension vectors
  tests/bugs/g3180-swizzle-nd-vectors.slang
Labels: pr: non-breaking

#4733 Fail assertion on debug build when memory leaks
  source/slangc/main.cpp
Labels: pr: non-breaking

#4711 Reflect inout modifiers
  include/slang.h
  source/slang/slang-reflection-api.cpp
Labels: pr: non-breaking

#4745 Disable warnings for input global variables
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-use-uninitialized-values.cpp
  tests/diagnostics/uninitialized-globals.slang
Labels: pr: non-breaking

#4744 Allow passing sized array to unsized array parameter.
  docs/user-guide/02-conventional-features.md
  source/slang/core.meta.slang
  source/slang/slang-ast-support-types.h
  source/slang/slang-check-conversion.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-autodiff-fwd.cpp
  source/slang/slang-ir-check-unsupported-inst.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-peephole.cpp
  source/slang/slang-ir-specialize-arrays.cpp
  source/slang/slang-ir-specialize-function-call.cpp
  source/slang/slang-ir-specialize-function-call.h
  source/slang/slang-ir.cpp
  tests/language-feature/unsized-array.slang
Labels: pr: non-breaking

#4753 Fix SPIRV emit for small-integer texture types.
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-util.cpp
  tests/spirv/small-int-texture.slang
Labels: pr: non-breaking

#4757 Set `nullptr` to coerce into the default value of `T*` type
  source/slang/slang-check-conversion.cpp
  tests/bugs/assign-nullptr.slang
Labels: pr: non-breaking

#4751 Fix invalid code generation for when using nested resource specialization
  source/slang/slang-ir-specialize-resources.cpp
  tests/language-feature/resource-specialization-nested-specialization.slang
  tests/language-feature/resource-specialization-struct-out.slang
  tests/language-feature/resource-specialization-struct-return.slang
Labels: pr: non-breaking

#4741 Move SPIRV global variables into a context variable
  include/slang.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-explicit-global-context.cpp
  source/slang/slang-options.cpp
  tests/bugs/spirv-opt-SROA-of-globals.slang
  tests/spirv/address-space-specialize.slang
  tests/spirv/explicit-context-validation-builtin-compute-glsl.slang
  tests/spirv/explicit-context-validation-builtin-compute-hlsl.slang
  tests/spirv/explicit-context-validation-builtin-vertex-glsl.slang
  tests/spirv/explicit-context-validation-groupshared.slang
  tests/spirv/explicit-context-validation-raytracing-glsl.slang
  tests/spirv/explicit-context-validation-raytracing-hlsl.slang
  tests/spirv/subgroup-size-2.slang
Labels: pr: non-breaking

#4752 Fixes for Metal ParameterBlock support.
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-check-shader-parameter-type.cpp
  source/slang/slang-ir-check-shader-parameter-type.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-legalize-types.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-legalize-types.cpp
  tests/bindings/nested-parameter-block-3.slang
  tests/diagnostics/nested-constant-buffer-in-parameter-block.slang
  tools/gfx/d3d12/d3d12-shader-object-layout.cpp
  tools/gfx/d3d12/d3d12-shader-object-layout.h
Labels: pr: non-breaking

#4761 Fix IR lowering for generic interface types.
  source/slang/slang-lower-to-ir.cpp
  tests/language-feature/constants/static-const-in-generic-interface.slang
  tests/language-feature/interfaces/generic-interface-conformance.slang
  tools/slang-test/slang-test-main.cpp
Labels: pr: non-breaking

#4727 Warnings target switch intrinsic asm
  source/slang/slang-ir-reachability.cpp
  source/slang/slang-ir-reachability.h
  source/slang/slang-ir-use-uninitialized-values.cpp
  source/slang/slang-lower-to-ir.cpp
  tests/diagnostics/uninitialized-out-parameters.slang
Labels: pr: non-breaking

#4750 Feature/replayer
  source/slang-record-replay/record/record-manager.cpp
  source/slang-record-replay/record/record-manager.h
  source/slang-record-replay/record/slang-composite-component-type.cpp
  source/slang-record-replay/record/slang-entrypoint.cpp
  source/slang-record-replay/record/slang-filesystem.cpp
  source/slang-record-replay/record/slang-global-session.cpp
  source/slang-record-replay/record/slang-module.cpp
  source/slang-record-replay/record/slang-session.cpp
  source/slang-record-replay/record/slang-type-conformance.cpp
  source/slang-record-replay/replay/decoder-consumer.h
  source/slang-record-replay/replay/json-consumer.cpp
  source/slang-record-replay/replay/json-consumer.h
  source/slang-record-replay/replay/recordFile-processor.cpp
  source/slang-record-replay/replay/recordFile-processor.h
  source/slang-record-replay/replay/replay-consumer.cpp
  source/slang-record-replay/replay/replay-consumer.h
  source/slang-record-replay/replay/slang-decoder.cpp
  source/slang-record-replay/replay/slang-decoder.h
  source/slang-record-replay/util/emum-to-string.h
  source/slang-record-replay/util/record-utility.cpp
  tools/slang-replay/main.cpp
Labels: pr: non-breaking
