Repository shader-slang/slang, pull requests merged in 2024-08, with the labels that each got.

#4766 Allow generic type deduction from ParameterBlock arguments.
  source/slang/slang-check-constraint.cpp
  tests/expected-failure-github.txt
  tests/language-feature/generics/parameter-block-unify.slang
  tools/render-test/shader-input-layout.cpp
Labels: pr: non-breaking

#4765 Allow implicit 'uniform' entrypoint parameters.
  source/slang/slang-check-shader.cpp
  source/slang/slang-diagnostic-defs.h
  tests/bugs/invalid-entrypoint-param.slang
  tests/language-feature/shader-params/entry-point-uniform-params-implicit.slang
  tests/reflection/attribute.slang.expected
Labels: pr: non-breaking

#4767 Perform type legalization on StructuredBuffer element.
  source/slang/slang-legalize-types.cpp
  tests/language-feature/interfaces/empty-type-conformance.slang
Labels: pr: non-breaking

#4768 Allow an enum case to reference a previously defined value.
  source/slang/slang-check-decl.cpp
  source/slang/slang-parser.cpp
  tests/language-feature/enums/reference-previous.slang
Labels: pr: non-breaking

#4755 Initial support for precompiled DXIL in slang-modules
  include/slang.h
  source/compiler-core/slang-dxc-compiler.cpp
  source/slang/slang-capabilities.capdef
  source/slang/slang-compiler-tu.cpp
  source/slang/slang-compiler.cpp
  source/slang/slang-compiler.h
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir.cpp
  source/slang/slang-ir.h
  source/slang/slang-module-library.cpp
  source/slang/slang-options.cpp
  source/slang/slang-serialize-container.cpp
  source/slang/slang-serialize-ir.cpp
  source/slang/slang.cpp
  tests/library/precompiled-dxil.slang
Labels: pr: non-breaking

#4779 Remove dxc disassemble debug code
  source/compiler-core/slang-dxc-compiler.cpp
Labels: pr: non-breaking

#4714 Fix auto-diff synthesized method naming conventions
  source/slang/slang-ir-autodiff-transcriber-base.cpp
  source/slang/slang-ir-autodiff-unzip.cpp
  tests/autodiff/reverse-checkpoint-1.slang
  tests/autodiff/reverse-checkpoint-2.slang
Labels: pr: non-breaking

#4740 More reflection API features.
  include/slang.h
  source/slang/slang-compiler.h
  source/slang/slang-parser.cpp
  source/slang/slang-reflection-api.cpp
  source/slang/slang.cpp
  tools/slang-unit-test/unit-test-decl-tree-reflection.cpp
Labels: pr: new feature, pr: non-breaking

#4785 Reduce dependency on std library
  source/core/slang-io.cpp
  source/core/slang-io.h
  source/slang-record-replay/record/output-stream.cpp
  source/slang-record-replay/record/output-stream.h
  source/slang-record-replay/record/record-manager.cpp
  source/slang-record-replay/record/record-manager.h
  source/slang-record-replay/record/slang-filesystem.cpp
  source/slang-record-replay/replay/json-consumer.cpp
  source/slang-record-replay/replay/json-consumer.h
  source/slang-record-replay/replay/recordFile-processor.h
  source/slang-record-replay/util/record-utility.cpp
  tools/slang-replay/main.cpp
Labels: pr: non-breaking

#4777 Warn when inout parameter is never written
  source/slang/core.meta.slang
  source/slang/diff.meta.slang
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-addr-inst-elimination.cpp
  source/slang/slang-ir-autodiff-transcriber-base.h
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-use-uninitialized-values.cpp
  source/slang/slang-lower-to-ir.cpp
  tests/autodiff/reverse-inout-param-custom-derivative.slang
  tests/bugs/gl-33-ext.slang
  tests/bugs/optional.slang
  tests/diagnostics/inout-never-written.slang
  tests/hlsl-intrinsic/matrix-double.slang
  tests/hlsl-intrinsic/size-of/align-of-3.slang
  tests/hlsl-intrinsic/size-of/size-of-3.slang
  tests/language-feature/struct-field-initializers/struct-field-no-initializer-complex-types.slang
  tests/language-feature/unsized-array.slang
  tests/pipeline/ray-tracing/trace-ray-inline.slang
Labels: pr: non-breaking

#4772 Support unicode identifier names.
  source/compiler-core/slang-lexer.cpp
  source/core/slang-char-encode.cpp
  source/core/slang-char-encode.h
  source/core/slang-char-util.h
  source/core/slang-std-writers.cpp
  source/slang/slang-language-server-document-symbols.cpp
  source/slang/slang-language-server.cpp
  source/slang/slang-workspace-version.cpp
  source/slang/slang-workspace-version.h
  tests/front-end/unicode-identifier.slang
Labels: pr: non-breaking

#4819 Emit memory qualifiers once when compiling to GLSL
  source/slang/slang-emit-glsl.cpp
  tests/bugs/gh-4818-1.slang
  tests/bugs/gh-4818-2.slang
Labels: pr: non-breaking

#4813 Update build steps for MacOS
  CONTRIBUTION.md
Labels: kind:documentation, pr: non-breaking

#4839 FIx issue with specializing witness tables
  source/slang/slang-ir-specialize.cpp
  tools/slang-unit-test/unit-test-generic-interface-conformance.cpp
Labels: pr: non-breaking

#4804 GitHub action benchmark
  .github/workflows/benchmark.yml
  source/core/slang-performance-profiler.cpp
  source/core/slang-performance-profiler.h
  source/slang/slang-compiler.cpp
  source/slang/slang.cpp
  tests/mdl/.gitignore
  tests/mdl/compile.py
Labels: pr: non-breaking

#4769 Issue/legalize resource
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-specialize-function-call.cpp
  tests/compute/nonuniformres-as-function-parameter.slang
Labels: pr: non-breaking

#4838 Do not zero-initialize groupshared and rayquery variables
  source/slang/slang-check-decl.cpp
  source/slang/slang-diagnostic-defs.h
  tests/compute/groupshared-init.slang
  tests/diagnostics/uninitialized-globals.slang
  tests/hlsl-intrinsic/atomic/atomic-intrinsics-64bit.slang
  tests/hlsl-intrinsic/atomic/atomic-intrinsics.slang
  tests/language-feature/shared-memory-initializer-error.slang
  tests/language-feature/zero-initialize/rayquery.slang
  tests/language-feature/zero-initialize/shared-memory.slang
  tests/metal/groupshared-threadlocal-same-parameter.slang
Labels: pr: breaking change

#4833 Variadic Generics Part 1: parsing and type checking.
  docs/proposals/007-variadic-generics.md
  source/slang/slang-ast-builder.cpp
  source/slang/slang-ast-builder.h
  source/slang/slang-ast-decl-ref.cpp
  source/slang/slang-ast-decl.h
  source/slang/slang-ast-expr.h
  source/slang/slang-ast-modifier.h
  source/slang/slang-ast-support-types.h
  source/slang/slang-ast-type.cpp
  source/slang/slang-ast-type.h
  source/slang/slang-ast-val.cpp
  source/slang/slang-ast-val.h
  source/slang/slang-check-conformance.cpp
  source/slang/slang-check-constraint.cpp
  source/slang/slang-check-conversion.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-inheritance.cpp
  source/slang/slang-check-overload.cpp
  source/slang/slang-check-type.cpp
  source/slang/slang-check.h
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-mangle.cpp
  source/slang/slang-parser.cpp
  source/slang/slang.natvis
Labels: pr: non-breaking

#4848 Design proposal for Tuple types.
  docs/proposals/008-tuples.md
Labels: pr: non-breaking

#4852 fix getVKAdapters on MoltenVK
  tools/gfx/vulkan/vk-helper-functions.cpp
Labels: pr: non-breaking

#4845 Make precompileForTargets work with Slang API
  include/slang.h
  source/slang-record-replay/record/slang-module.cpp
  source/slang-record-replay/record/slang-module.h
  source/slang/slang-compiler-tu.cpp
  source/slang/slang-compiler.h
  source/slang/slang.cpp
  tools/gfx-unit-test/precompiled-module-2.cpp
Labels: pr: non-breaking

#4855 Refactoring benchmark CI pipeline
  .github/workflows/benchmark.yml
  tools/benchmark/.gitignore
  tools/benchmark/compile.py
Labels: pr: non-breaking

#4850 Variadic Generics Part 3: language server
  source/slang/slang-ast-iterator.h
  source/slang/slang-ast-print.cpp
  source/slang/slang-language-server-ast-lookup.cpp
  source/slang/slang-language-server.cpp
Labels: pr: non-breaking

#4859 Include inout cast operation as an aliasing instruction
  source/slang/slang-ir-use-uninitialized-values.cpp
  tests/diagnostics/inout-never-written.slang
Labels: pr: non-breaking

#4866 Avoiding the use of the global AST builder in DeclRefType::create
  source/slang/slang-syntax.cpp
  tests/modules/environment.slang
  tests/modules/hit.slang
Labels: pr: non-breaking

#4864 Make sure to resolve overloaded expr for call args.
  source/slang/slang-check-expr.cpp
  tests/bugs/gh-4863.slang
Labels: pr: non-breaking

#4849 Variadic Generics Part 2: IR lowering and specialization.
  docs/proposals/007-variadic-generics.md
  source/slang/core.meta.slang
  source/slang/slang-ast-builder.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-link.cpp
  source/slang/slang-ir-loop-inversion.cpp
  source/slang/slang-ir-peephole.cpp
  source/slang/slang-ir-peephole.h
  source/slang/slang-ir-specialize.cpp
  source/slang/slang-ir-ssa.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-ir.h
  source/slang/slang-legalize-types.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-syntax.cpp
  tests/language-feature/generics/tuple.slang
  tests/language-feature/generics/variadic-0.slang
  tests/language-feature/generics/variadic-void.slang
Labels: pr: non-breaking

#4861 Remove using SpvStorageClass values casted into AddressSpace values
  include/slang.h
  source/core/slang-common.h
  source/core/slang-signal.cpp
  source/core/slang-signal.h
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-metal.cpp
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-explicit-global-context.cpp
  source/slang/slang-ir-glsl-legalize.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-metal-legalize.cpp
  source/slang/slang-ir-specialize-address-space.cpp
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-legalize-types.cpp
  source/slang/slang-type-system-shared.h
Labels: pr: non-breaking

#4871 Implement Path::createDirectoryRecursive
  source/core/slang-io.cpp
  source/slang/slang-ir-specialize-function-call.cpp
Labels: pr: non-breaking

#4847 Fetch slang-llvm.so from correct release
  CMakeLists.txt
  cmake/GitHubRelease.cmake
  docs/building.md
Labels: pr: non-breaking

#4881 Track ContainerDecl with synthesized scope variable for `DifferentialType`
  source/slang/slang-ast-synthesis.h
Labels: pr: non-breaking

#4885 Track uninitialized values of `Ptr<Specialize<T>>` inside type `T` without hang
  source/slang/slang-ir-use-uninitialized-values.cpp
Labels: pr: non-breaking

#4889 Exclude synthesized code from code auto documentation system
  source/slang/slang-doc-ast.cpp
  source/slang/slang-doc-ast.h
  source/slang/slang-doc-markdown-writer.cpp
Labels: pr: non-breaking

#4886 Fix `tests\autodiff\reverse-while-loop-3.slang` test
  tests/autodiff/reverse-while-loop-3.slang
  tests/autodiff/reverse-while-loop-3.slang.expected.txt
Labels: pr: non-breaking

#4870 Support dependent generic constraints.
  source/slang/slang-ast-decl.h
  source/slang/slang-check-constraint.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-overload.cpp
  source/slang/slang-ir-clone.cpp
  source/slang/slang-lower-to-ir.cpp
  tests/language-feature/generics/dependent-generic-2.slang
  tests/language-feature/generics/dependent-generic-3.slang
  tests/language-feature/generics/dependent-generic.slang
Labels: pr: non-breaking

#4893 Revert "Fetch slang-llvm.so from correct release (#4847)"
  CMakeLists.txt
  cmake/GitHubRelease.cmake
  docs/building.md
Labels: pr: non-breaking

#4896 Allow creating draft releases from tags containing "draft"
  .github/workflows/release-linux-glibc-2-17.yml
  .github/workflows/release.yml
Labels: pr: non-breaking

#4895 Dont require llvm for building generators
  CMakeLists.txt
  CMakePresets.json
  cmake/GitHubRelease.cmake
  docs/building.md
Labels: pr: non-breaking

#4904 Fix a false failure when using the latest SPIR-V
  tests/bugs/gh-3087-multi-entry-point.slang
  tests/bugs/gh-3087.slang
Labels: pr: non-breaking

#4898 Feature/capture unit test
  examples/example-base/example-base.cpp
  examples/example-base/example-base.h
  examples/example-base/test-base.cpp
  examples/example-base/test-base.h
  examples/hello-world/main.cpp
  examples/triangle/main.cpp
  source/slang-record-replay/record/slang-composite-component-type.cpp
  source/slang-record-replay/record/slang-composite-component-type.h
  source/slang-record-replay/record/slang-entrypoint.cpp
  source/slang-record-replay/record/slang-entrypoint.h
  source/slang-record-replay/record/slang-filesystem.cpp
  source/slang-record-replay/record/slang-filesystem.h
  source/slang-record-replay/record/slang-global-session.cpp
  source/slang-record-replay/record/slang-global-session.h
  source/slang-record-replay/record/slang-module.cpp
  source/slang-record-replay/record/slang-module.h
  source/slang-record-replay/record/slang-session.cpp
  source/slang-record-replay/record/slang-session.h
  source/slang-record-replay/record/slang-type-conformance.cpp
  source/slang-record-replay/record/slang-type-conformance.h
  source/slang-record-replay/replay/json-consumer.cpp
  source/slang-record-replay/replay/replay-consumer.cpp
  test-record-replay.sh
  tools/platform/window.h
Labels: pr: non-breaking

#4905 Make variadic generics work with interfaces and forward autodiff.
  source/slang/core.meta.slang
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-ir-autodiff-fwd.cpp
  source/slang/slang-ir-autodiff-fwd.h
  source/slang/slang-ir-autodiff-transcriber-base.cpp
  source/slang/slang-ir-autodiff-transcriber-base.h
  source/slang/slang-ir-autodiff-transpose.h
  source/slang/slang-ir-autodiff.cpp
  source/slang/slang-ir-autodiff.h
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-lower-expand-type.cpp
  source/slang/slang-ir-lower-expand-type.h
  source/slang/slang-ir-peephole.cpp
  source/slang/slang-ir-specialize.cpp
  source/slang/slang-ir-util.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-ir.h
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-mangle.cpp
  tests/language-feature/generics/variadic-0.slang
  tests/language-feature/generics/variadic-void.slang
  tests/language-feature/ifunc/diff-functor.slang
  tests/language-feature/ifunc/ifunc.slang
Labels: pr: non-breaking

#4912 Implement `-fvk-use-dx-layout`
  docs/command-line-slangc-reference.md
  include/slang.h
  source/slang-record-replay/util/emum-to-string.h
  source/slang/slang-compiler-options.cpp
  source/slang/slang-compiler-options.h
  source/slang/slang-compiler.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-layout.cpp
  source/slang/slang-ir-layout.h
  source/slang/slang-ir-lower-buffer-element-type.cpp
  source/slang/slang-ir.h
  source/slang/slang-options.cpp
  source/slang/slang-type-layout.cpp
  source/slang/slang.cpp
  tests/spirv/cbuffer-dx-layout-1.slang
  tests/spirv/cbuffer-dx-layout-2.slang
  tests/spirv/cbuffer-dx-layout-3.slang
  tests/spirv/cbuffer-dx-layout-4.slang
  tests/spirv/cbuffer-not-dx-layout.slang
  tests/spirv/structured-buffer-dx-layout.slang
  tests/spirv/tbuffer-dx-layout-1.slang
Labels: pr: non-breaking

#4900 Correct the `generic-jvp.slang` test
  tests/autodiff/generic-jvp.slang
  tests/autodiff/generic-jvp.slang.expected.txt
Labels: pr: non-breaking

#4915 Fix Varying Variable Location Assignments With Hull Shaders
  source/core/slang-uint-set.cpp
  source/core/slang-uint-set.h
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-hlsl.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-glsl-legalize.cpp
  tests/hlsl/simple-hull-shader-1.slang
  tests/hlsl/simple-hull-shader-2.slang
Labels: pr: non-breaking

#4920 Migrate examples
  examples/cpu-hello-world/main.cpp
  examples/example-base/example-base.cpp
  examples/example-base/test-base.cpp
  examples/example-base/test-base.h
  examples/ray-tracing/main.cpp
  examples/shader-object/main.cpp
  source/slang-record-replay/record/slang-module.cpp
  source/slang-record-replay/record/slang-module.h
  source/slang-record-replay/record/slang-session.cpp
  source/slang-record-replay/record/slang-session.h
  source/slang-record-replay/replay/json-consumer.cpp
  source/slang-record-replay/replay/parameter-decoder.h
  source/slang-record-replay/replay/replay-consumer.cpp
  source/slang-record-replay/replay/replay-consumer.h
  source/slang-record-replay/replay/slang-decoder.cpp
  tools/slang-unit-test/unit-test-record-replay.cpp
Labels: pr: non-breaking

#4901 Explicitly detach derivative when forming a non-differentiable struct out of differentiable args
  source/slang/slang-ast-expr.h
  source/slang/slang-check-conversion.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-lower-to-ir.cpp
  tests/autodiff/field-extract-of-make-struct.slang
  tests/autodiff/field-extract-of-make-struct.slang.expected.txt
Labels: pr: non-breaking

#4909 Add ability to specialize generic references to functions, types and more
  include/slang.h
  source/slang/slang-compiler.h
  source/slang/slang-reflection-api.cpp
  source/slang/slang-syntax.h
  source/slang/slang.cpp
  tools/slang-unit-test/unit-test-decl-tree-reflection.cpp
Labels: pr: new feature, pr: non-breaking

#4925 Avoid inlining functions with inline ASM blocks.
  source/slang/hlsl.meta.slang
  source/slang/slang-ir-inline.cpp
Labels: pr: non-breaking

#4707 Adds a warning for using `[PreferRecompute]` on methods that may contain side effects
  source/slang/core.meta.slang
  source/slang/slang-ast-modifier.h
  source/slang/slang-check-modifier.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-autodiff-rev.cpp
  source/slang/slang-ir-autodiff.cpp
  source/slang/slang-ir-autodiff.h
  source/slang/slang-lower-to-ir.cpp
  tests/autodiff/warn-on-prefer-recompute-side-effects.slang
Labels: pr: non-breaking

#4776 Script for generating a release note
  docs/scripts/release-note.sh
Labels: pr: non-breaking

#4902 Adding a document of how to update external/spirv-*
  docs/update_spirv.md
Labels: pr: non-breaking

#4799 Document notable `__ref` uses in stdlib. Remove user docs use of '__ref'.
  docs/user-guide/a1-04-interop.md
  source/slang/core.meta.slang
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#4929 Auto-cancel obsolete MDL benchmark jobs.
  .github/workflows/benchmark.yml
Labels: pr: non-breaking

#4923 Make tuple types work in autodiff.
  source/slang/diff.meta.slang
  source/slang/slang-ast-builder.cpp
  source/slang/slang-ast-builder.h
  source/slang/slang-check-expr.cpp
  source/slang/slang-ir-addr-inst-elimination.cpp
  source/slang/slang-ir-autodiff-fwd.cpp
  source/slang/slang-ir-autodiff-transpose.h
  source/slang/slang-ir-autodiff.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-lower-expand-type.cpp
  source/slang/slang-ir-lower-tuple-types.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-lower-to-ir.cpp
  tests/language-feature/tuple/tuple-autodiff.slang
Labels: pr: non-breaking

#4928 Allow capabilities to be used with `[shader("...")]`
  docs/command-line-slangc-reference.md
  source/slang/slang-ast-modifier.h
  source/slang/slang-capabilities.capdef
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-modifier.cpp
  source/slang/slang-check-shader.cpp
  source/slang/slang-compiler.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-profile.h
  source/slang/slang.cpp
  tests/language-feature/capability/explicit-shader-stage-1.slang
  tests/language-feature/capability/explicit-shader-stage-2.slang
  tests/language-feature/capability/explicit-shader-stage-3.slang
  tests/language-feature/capability/explicit-shader-stage-4.slang
  tests/language-feature/capability/explicit-shader-stage-5.slang
  tests/language-feature/capability/explicit-shader-stage-6.slang
  tests/language-feature/capability/explicit-shader-stage-7.slang
  tests/language-feature/capability/explicit-shader-stage-8.slang
  tests/language-feature/capability/explicit-shader-stage-9.slang
Labels: pr: non-breaking

#4280 Metal: Mesh Shaders
  source/slang/core.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-emit-metal.cpp
  source/slang/slang-ir-glsl-legalize.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-metal-legalize.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-ir.h
  tests/metal/simple-task.slang
Labels: pr: non-breaking

#4951 Metal: Fix metal primitive_id semantic
  source/slang/slang-ir-metal-legalize.cpp
Labels: pr: non-breaking

#4911 Ignoring construct field warnings on delegatory methods
  source/slang/slang-ir-use-uninitialized-values.cpp
  tests/diagnostics/uninitialized-fields-delegated.slang
  tests/diagnostics/uninitialized-fields.slang
Labels: pr: non-breaking

#4927 Migrate examples
  examples/autodiff-texture/main.cpp
  examples/autodiff-texture/train.slang
  examples/model-viewer/main.cpp
  examples/ray-tracing-pipeline/main.cpp
  source/slang-record-replay/replay/json-consumer.cpp
  tools/slang-unit-test/unit-test-record-replay.cpp
Labels: pr: non-breaking

#4949 Add `ReportIntersectionOptix` for optix.
  source/slang/hlsl.meta.slang
  tests/cuda/report-hit.slang
Labels: pr: non-breaking

#4956 Fix partial inference of variadic generic functions.
  source/slang/core.meta.slang
  source/slang/slang-check-overload.cpp
  tests/language-feature/generics/variadic-partial-inference.slang
Labels: pr: non-breaking

#4962 Fix typo SV_DispatchThreadIndex
  tests/ir/factorial.slang
  tests/ir/string-literal-hash-reflection.slang
  tests/ir/string-literal.slang
Labels: pr: non-breaking

#4958 Make sure `NullDifferential` and its witness are removed after autodiff.
  source/slang/core.meta.slang
  source/slang/diff.meta.slang
  source/slang/slang-ast-modifier.h
  source/slang/slang-ir-autodiff.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-lower-to-ir.cpp
  tests/language-feature/generics/variadic-0.slang
Labels: pr: non-breaking

#4960 Fix typo SV_DomainLsocation
  source/slang/slang-ir-legalize-varying-params.h
  source/slang/slang-ir-metal-legalize.cpp
Labels: pr: non-breaking

#4860 Support mixture of precompiled and non-precompiled modules
  include/slang.h
  source/compiler-core/slang-artifact-associated-impl.cpp
  source/compiler-core/slang-artifact-associated-impl.h
  source/compiler-core/slang-artifact-associated.h
  source/slang/slang-compiler-tu.cpp
  source/slang/slang-compiler.cpp
  source/slang/slang-compiler.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-link.cpp
  source/slang/slang-ir-metadata.cpp
  source/slang/slang-ir-redundancy-removal.cpp
  source/slang/slang-ir-redundancy-removal.h
  source/slang/slang-ir-util.cpp
  source/slang/slang-ir-util.h
  source/slang/slang-ir.h
  source/slang/slang-module-library.cpp
  source/slang/slang-options.cpp
  source/slang/slang.cpp
  tests/library/export-library-generics.slang
  tests/library/module-library-matrix.slang
  tests/library/precompiled-dxil-generics.slang
  tests/library/precompiled-dxil-matrix.slang
  tests/library/precompiled-dxil.slang
  tests/library/precompiled-module-library-resource.slang
Labels: pr: non-breaking

#4964 Fix redundant decorations in IRParam
  source/slang/slang-ir-link.cpp
  tests/bugs/gh-4922-nointerpolation.slang
Labels: pr: non-breaking

#4963 Support specialization constants.
  source/slang/core.meta.slang
  source/slang/slang-ast-modifier.h
  source/slang/slang-check-impl.h
  source/slang/slang-check-modifier.cpp
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-glsl.h
  source/slang/slang-emit-spirv-ops.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-parameter-binding.cpp
  source/slang/slang-parser.cpp
  source/slang/slang-type-system-shared.h
  tests/language-feature/zero-initialize/struct.slang
  tests/spirv/specialization-constant.slang
Labels: pr: non-breaking

#4967 capture component type
  examples/gpu-printing/main.cpp
  examples/hello-world/main.cpp
  source/slang-record-replay/record/output-stream.h
  source/slang-record-replay/record/record-manager.cpp
  source/slang-record-replay/record/record-manager.h
  source/slang-record-replay/record/slang-component-type.cpp
  source/slang-record-replay/record/slang-component-type.h
  source/slang-record-replay/record/slang-composite-component-type.cpp
  source/slang-record-replay/record/slang-composite-component-type.h
  source/slang-record-replay/record/slang-entrypoint.cpp
  source/slang-record-replay/record/slang-entrypoint.h
  source/slang-record-replay/record/slang-global-session.cpp
  source/slang-record-replay/record/slang-global-session.h
  source/slang-record-replay/record/slang-module.cpp
  source/slang-record-replay/record/slang-module.h
  source/slang-record-replay/record/slang-session.cpp
  source/slang-record-replay/record/slang-session.h
  source/slang-record-replay/record/slang-type-conformance.cpp
  source/slang-record-replay/record/slang-type-conformance.h
  source/slang-record-replay/replay/json-consumer.cpp
  source/slang-record-replay/replay/json-consumer.h
  source/slang-record-replay/replay/replay-consumer.cpp
  source/slang-record-replay/replay/replay-consumer.h
  source/slang-record-replay/util/emum-to-string.h
  source/slang-record-replay/util/record-format.h
  tools/slang-replay/main.cpp
  tools/slang-unit-test/unit-test-record-replay.cpp
Labels: pr: non-breaking

#4965 Updated MDL shader sources for benchmarks
  .github/workflows/benchmark.yml
  tools/benchmark/compile.py
Labels: pr: non-breaking

#4968 Support extension on generic type.
  source/slang/slang-ast-builder.h
  source/slang/slang-check-conformance.cpp
  source/slang/slang-check-constraint.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-inheritance.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-lookup.cpp
  source/slang/slang-parser.cpp
  tests/language-feature/extensions/generic-extension-1.slang
  tests/language-feature/extensions/generic-extension-2.slang
  tests/language-feature/extensions/interface-extension.slang
  tests/language-feature/extensions/this-in-extension.slang
Labels: pr: non-breaking

#4973 Fix prelude generation by using relative paths for including `slang.h`
  source/core/slang-blob.h
  source/core/slang-chunked-list.h
  source/core/slang-common.h
  source/core/slang-crypto.h
  source/core/slang-file-system.h
  source/core/slang-free-list.h
  source/core/slang-hash.h
  source/core/slang-hex-dump-util.h
  source/core/slang-http.h
  source/core/slang-linked-list.h
  source/core/slang-list.h
  source/core/slang-memory-arena.h
  source/core/slang-persistent-cache.h
  source/core/slang-platform.h
  source/core/slang-random-generator.h
  source/core/slang-shared-library.h
  source/core/slang-short-list.h
  source/core/slang-smart-pointer.h
  source/core/slang-type-convert-util.h
  source/core/slang-type-text-util.h
Labels: pr: non-breaking

#4815 User guide page for SPIR-V target specific information
  docs/user-guide/a1-01-matrix-layout.md
  docs/user-guide/a2-01-spirv-target-specific.md
  docs/user-guide/a2-target-specific-features.md
  docs/user-guide/toc.html
  source/slang/slang-options.cpp
Labels: kind:documentation, pr: non-breaking
