Repository shader-slang/slang, pull requests merged in 2024-10, with the labels that each got.

#5159 Fix diagnostics for [PreferRecompute]
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-ir-autodiff.cpp
  tests/autodiff/dont-warn-on-simple-prefer-recompute.slang
  tests/autodiff/warn-on-prefer-recompute-side-effects.slang
Labels: pr: non-breaking

#5197 Enable debug log for VK CTS workflow
  .github/workflows/vk-gl-cts-nightly.yml
Labels: pr: non-breaking

#5205 SizeOfLikeExpr has type int
  source/slang/slang-check-expr.cpp
  source/slang/slang-parser.cpp
Labels: kind:bug, pr: non-breaking

#5200 Fix crash when compiling associatedtypes with generic interface constraints.
  source/slang/hlsl.meta.slang.temp.h
  source/slang/slang-ast-decl-ref.cpp
  source/slang/slang-lower-to-ir.cpp
  tests/language-feature/generics/generic-assoc-type-constraint.slang
Labels: pr: non-breaking

#5216 Fix the broken CI
  source/slang/slang-ir.cpp
  source/slang/slang-parser.cpp
Labels: pr: non-breaking

#5217 Add path to bash to GITHUB_PATH
  .github/actions/common-setup/action.yml
Labels: pr: non-breaking

#5202 Checkout LLVM as a workflow action rather than git-clone command
  .github/actions/common-setup/action.yml
Labels: pr: non-breaking

#5124 Support custom derivatives of member functions of differentiable types
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-diagnostic-defs.h
  tests/autodiff/diff-member-func-custom-derivative.slang
  tests/autodiff/diff-member-func-custom-derivative.slang.expected.txt
  tests/autodiff/member-func-extension-custom-derivative.slang
  tests/autodiff/member-func-extension-custom-derivative.slang.expected.txt
  tests/autodiff/static-func-custom-derivative.slang
  tests/autodiff/static-func-custom-derivative.slang.expected.txt
Labels: pr: non-breaking

#5076 Allow building using external dependencies
  CMakeLists.txt
  cmake/AutoOption.cmake
  cmake/SlangTarget.cmake
  external/CMakeLists.txt
  prelude/CMakeLists.txt
  source/compiler-core/slang-spirv-core-grammar.h
  source/core/slang-dictionary.h
  source/core/slang-hash.h
  source/core/slang-lz4-compression-system.cpp
  source/slang/CMakeLists.txt
  source/slang/slang-ir-glsl-legalize.cpp
  tools/slang-test/slang-test-main.cpp
Labels: pr: non-breaking

#5128 Add interfaces for retrieving separate linkable downstream binaries
  include/slang.h
  source/slang-record-replay/record/slang-module.cpp
  source/slang-record-replay/record/slang-module.h
  source/slang/slang-compiler-tu.cpp
  source/slang/slang-compiler.h
  source/slang/slang.cpp
  tests/library/linked.spirv
  tools/gfx-unit-test/precompiled-module-2.cpp
Labels: pr: non-breaking

#5231 Refactor the code for synthesizing the body of constructor
  source/slang/slang-check-decl.cpp
Labels: pr: non-breaking

#5174 Add WGSL support for slang-test
  external/slang-tint-headers/slang-tint.h
  include/slang-gfx.h
  include/slang.h
  source/compiler-core/slang-artifact-desc-util.cpp
  source/compiler-core/slang-artifact.h
  source/compiler-core/slang-downstream-compiler-util.cpp
  source/compiler-core/slang-glslang-compiler.cpp
  source/compiler-core/slang-tint-compiler.cpp
  source/compiler-core/slang-tint-compiler.h
  source/core/slang-render-api-util.cpp
  source/core/slang-render-api-util.h
  source/core/slang-type-convert-util.cpp
  source/core/slang-type-text-util.cpp
  source/slang/slang-artifact-output-util.cpp
  source/slang/slang-compiler.cpp
  source/slang/slang-compiler.h
  source/slang/slang-emit.cpp
  source/slang/slang-options.cpp
  source/slang/slang-type-layout.cpp
  source/slang/slang.cpp
  tests/compute/atomics-buffer.slang
  tests/compute/atomics-groupshared.slang
  tests/compute/atomics.slang
  tests/compute/buffer-type-splitting.slang
  tests/compute/byte-address-buffer.slang
  tests/compute/column-major.slang
  tests/compute/constant-buffer-memory-packing.slang
  tests/compute/func-cbuffer-param.slang
  tests/compute/parameter-block.slang
  tests/compute/texture-get-dimensions.slang
  tests/compute/texture-sampling.slang
  tests/compute/texture-simple.slang
  tests/compute/texture-simpler.slang
  tests/compute/transcendental-double.slang
  tests/expected-failure-github.txt
  tests/wgsl/entry-point.slang
  tools/render-test/options.cpp
  tools/render-test/render-test-main.cpp
  tools/slang-test/slang-test-main.cpp
  tools/slang-test/test-context.h
Labels: pr: non-breaking

#5023 Look through attributes and rates when determining by reference initialization
  source/slang/slang-ir-use-uninitialized-values.cpp
  tests/bugs/gh-5022.slang
Labels: pr: non-breaking

#5232 Overhaul docgen tool and setup CI to generate stdlib reference.
  .github/workflows/release.yml
  .gitignore
  docs/build_reference.ps1
  source/slang/core.meta.slang
  source/slang/glsl.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-ast-print.cpp
  source/slang/slang-ast-print.h
  source/slang/slang-capability.cpp
  source/slang/slang-compiler.h
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-doc-ast.h
  source/slang/slang-doc-markdown-writer.cpp
  source/slang/slang-doc-markdown-writer.h
  source/slang/slang-language-server-completion.cpp
  source/slang/slang.cpp
  tests/doc/doc-req.slang
  tests/doc/doc-req.slang.expected
  tests/doc/doc.slang
  tests/doc/doc.slang.expected
  tests/metal/texture-sampler-less.slang
  tests/metal/texture.slang
  tests/wgsl/texture-gather.slang
  tests/wgsl/texture-load.slang
  tests/wgsl/texture-sampler-less.slang
  tests/wgsl/texture.slang
Labels: pr: non-breaking

#5235 Fix build for clang-14
  source/core/slang-performance-profiler.cpp
Labels: pr: non-breaking

#5241 Fix bug related to findAndCheckEntrypoint.
  source/slang/slang-ir-link.cpp
  tools/slang-unit-test/unit-test-find-check-entrypoint.cpp
Labels: pr: non-breaking

#5243 Fix spirv lowering logic around pointer to unsized array.
  source/slang/slang-check-decl.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-lower-buffer-element-type.cpp
  source/slang/slang-ir-specialize-address-space.cpp
  source/slang/slang-ir.cpp
  tests/bugs/gh-3825.slang
  tests/spirv/ptr-unsized-array.slang
Labels: pr: non-breaking

#4952 Metal: Texture write fix
  source/slang/hlsl.meta.slang
  source/slang/slang-emit-metal.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-metal-legalize.cpp
  tests/metal/texture-write.slang
Labels: pr: non-breaking

#5230 Fix precompiled glsl modules
  source/slang/slang-check-impl.h
  source/slang/slang-compiler-tu.cpp
  tests/library/precompiled-glsl.slang
Labels: pr: non-breaking

#5242 Use user defined type name in glsl buffer declarations.
  source/slang/slang-emit-glsl.cpp
  tests/bindings/hlsl-to-vulkan-global-binding.hlsl
  tests/cross-compile/texture-load.slang
Labels: pr: non-breaking

#5248 Support constant folding for static array access.
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  tests/language-feature/constants/static-array-indexing.slang
Labels: pr: non-breaking

#5250 Fix links in stdlib reference category landing page.
  source/slang/slang-doc-markdown-writer.cpp
Labels: pr: non-breaking

#5255 slang-test: retry failed test at the end.
  tools/slang-test/slang-test-main.cpp
  tools/slang-test/test-context.h
  tools/slang-test/test-reporter.h
Labels: pr: non-breaking

#5252 WGSL: Enable load & store from byte-addressible buffers
  source/slang/hlsl.meta.slang
  source/slang/slang-emit-wgsl.cpp
  tests/compute/byte-address-buffer.slang
Labels: pr: non-breaking

#5237 Add slang-wasm target
  CMakeLists.txt
  CMakePresets.json
  docs/building.md
  source/compiler-core/slang-diagnostic-sink.cpp
  source/slang-wasm/slang-wasm-bindings.cpp
  source/slang-wasm/slang-wasm.cpp
  source/slang-wasm/slang-wasm.h
Labels: pr: non-breaking

#5251 Restrict stdlib embed macros to single source file
  CMakeLists.txt
  cmake/SlangTarget.cmake
  source/slang-stdlib/CMakeLists.txt
  source/slang-stdlib/slang-embedded-stdlib-source.cpp
  source/slang-stdlib/slang-embedded-stdlib.cpp
  source/slang/CMakeLists.txt
  source/slang/slang-stdlib.cpp
Labels: pr: non-breaking

#5265 beautify the readme support table
  README.md
Labels: pr: non-breaking

#5272 Fix race condition for building stdlib headers
  source/slang-stdlib/CMakeLists.txt
Labels: pr: non-breaking

#5266 Write out summary of documentation in docgen tool.
  source/slang/slang-doc-markdown-writer.cpp
  source/slang/slang-doc-markdown-writer.h
  source/slang/slang.cpp
Labels: pr: non-breaking

#5268 Fix assert when compiling an entrypoint that calls another entrypoint.
  CMakeLists.txt
  source/slang/slang-ir-entry-point-uniforms.cpp
  tools/slang-test/slang-test-main.cpp
  tools/slang-unit-test/unit-test-find-entrypoint-nested.cpp
Labels: pr: non-breaking

#5285 Fix release build failure
  cmake/SlangTarget.cmake
  source/slang/CMakeLists.txt
Labels: pr: non-breaking

#5271 Misc build fixes.
  CMakeLists.txt
  docs/user-guide/a3-02-reference-capability-atoms.md
  source/slang-wasm/slang-wasm.cpp
  source/slang/CMakeLists.txt
  source/slang/slang-check-decl.cpp
  source/slangc/main.cpp
  tools/slang-capability-generator/capability-generator-main.cpp
  tools/slang-generate/main.cpp
Labels: pr: non-breaking

#5260 Fix unexported spReflectionEntryPoint_GetFunction
  source/slang/slang-reflection-api.cpp
Labels: pr: non-breaking

#5295 Lower minimum CMake version to 3.22
  CMakeLists.txt
  docs/building.md
  external/CMakeLists.txt
Labels: pr: non-breaking

#5301 Move C interface from slang.h to slang-deprecated.h
  examples/cpu-com-example/main.cpp
  include/slang-deprecated.h
  include/slang.h
  source/compiler-core/slang-artifact-desc-util.cpp
  source/compiler-core/slang-source-embed-util.cpp
  source/core/slang-common.h
  source/core/slang-persistent-cache.cpp
  source/core/slang-string-util.cpp
  source/slang-record-replay/record/slang-global-session.cpp
  source/slang-record-replay/replay/replay-consumer.cpp
  source/slang/slang-api.cpp
  source/slang/slang-ast-val.cpp
  source/slang/slang-compiler.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-mangle.cpp
  source/slang/slang-options.cpp
  source/slang/slang-preprocessor.cpp
  tools/render-test/slang-support.cpp
  tools/slang-test/slangc-tool.cpp
  tools/slang-unit-test/unit-test-com-host-callable.cpp
  tools/test-server/test-server-main.cpp
Labels: pr: non-breaking

#5302 review and revise building instructions
  docs/building.md
Labels: pr: non-breaking

#5297 Add stdlib documentation for attributes and interfaces.
  docs/build_reference.ps1
  source/slang/core.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-doc-markdown-writer.cpp
  source/slang/slang-doc-markdown-writer.h
  source/slang/slang-mangle.cpp
  source/slang/slang.cpp
Labels: pr: non-breaking

#5316 Fix type checking on generic extensions.
  source/slang/slang-check-inheritance.cpp
  tests/bugs/gh-5140.slang
  tests/fcpw/LICENSE
  tests/fcpw/aggregate.slang
  tests/fcpw/bounding-volumes.slang
  tests/fcpw/bvh-node.slang
  tests/fcpw/bvh-refit.cs.slang
  tests/fcpw/bvh-traversal.cs.slang
  tests/fcpw/bvh.slang
  tests/fcpw/fcpw.slang
  tests/fcpw/geometry.slang
  tests/fcpw/interaction.slang
  tests/fcpw/math-constants.slang
  tests/fcpw/ray.slang
  tests/fcpw/transform.slang
  tools/slang-unit-test/unit-test-fcpw-compile.cpp
Labels: pr: non-breaking

#5319 Fix spirv debug info for pointer types.
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-type-layout.h
  tests/spirv/debug-type-pointer-2.slang
  tests/spirv/debug-type-pointer.slang
Labels: pr: non-breaking

#5320 Fix entrypoint naming in glsl backend.
  source/slang/slang-emit-c-like.cpp
  tools/slang-unit-test/unit-test-find-entrypoint-nested.cpp
Labels: pr: non-breaking

#5315 Fix D3D12Core.dll loading problem for debug build
  CMakeLists.txt
  source/core/slang-render-api-util.cpp
  tools/render-test/slang-support.cpp
  tools/slang-test/slang-test-main.cpp
Labels: pr: non-breaking

#5337 Add 'findAndCheckEntryPoint' to wasm binding
  source/slang-wasm/slang-wasm-bindings.cpp
  source/slang-wasm/slang-wasm.cpp
  source/slang-wasm/slang-wasm.h
Labels: pr: non-breaking

#5324 Cleanup atomic intrinsics.
  prelude/slang-cuda-prelude.h
  source/slang/core.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-cuda.cpp
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-glsl.h
  source/slang/slang-emit-hlsl.cpp
  source/slang/slang-emit-metal.cpp
  source/slang/slang-emit-metal.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-intrinsic-expand.cpp
  source/slang/slang-ir-legalize-extract-from-texture-access.cpp
  source/slang/slang-ir-legalize-extract-from-texture-access.h
  source/slang/slang-ir-legalize-is-texture-access.cpp
  source/slang/slang-ir-legalize-is-texture-access.h
  source/slang/slang-ir-use-uninitialized-values.cpp
  source/slang/slang-ir.cpp
  tests/bugs/gh-3997.slang
  tests/compute/atomics-invalid-dest-type.slang
  tests/compute/nonuniformres-atomic.slang
  tests/hlsl-intrinsic/texture/float-atomics.slang
  tests/metal/atomic-byteaddressbuffer.slang
  tests/metal/atomic-intrinsics.slang
  tests/metal/atomic-texture-buffer.slang
  tests/slang-extension/atomic-int64-byte-address-buffer.slang
  tests/slang-extension/atomic-min-max-u64-byte-address-buffer.slang
  tests/slang-extension/cas-int64-byte-address-buffer.slang
  tests/slang-extension/exchange-int64-byte-address-buffer.slang
  tests/spirv/ref-this.slang
Labels: pr: non-breaking

#5330 Cleanup definition of `printf`.
  source/slang/hlsl.meta.slang
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-legalize-types.cpp
  tests/spirv/debug-printf.slang
Labels: pr: non-breaking

#5206 Remove sccache
  .github/actions/common-setup/action.yml
  docs/ci.md
Labels: pr: non-breaking

#5340 Use `VariablePointersStorageBuffer` instead of `VariablePointer` spv …
  source/slang/slang-emit-spirv.cpp
Labels: pr: non-breaking

#5346 Make slang-llvm fetching and failure more robust
  CMakeLists.txt
  cmake/FetchedSharedLibrary.cmake
  cmake/GitHubRelease.cmake
  cmake/GitVersion.cmake
  docs/building.md
Labels: pr: non-breaking

#5352 Remove use of Variable Pointer capability.
  source/slang/slang-emit-spirv.cpp
  tests/bugs/gh-3601.slang
  tests/spirv/pointer.slang
Labels: pr: non-breaking

#5341 Properly check switch case.
  source/slang/slang-ast-expr.h
  source/slang/slang-ast-iterator.h
  source/slang/slang-check-conversion.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-overload.cpp
  source/slang/slang-check-stmt.cpp
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-wgsl.cpp
  source/slang/slang-emit-wgsl.h
  source/slang/slang-language-server-ast-lookup.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-syntax.h
  tests/bugs/gh-5321.slang
  tests/diagnostics/constexpr-error.slang
  tests/diagnostics/constexpr-error.slang.expected
  tests/language-feature/enums/enum-cast.slang
  tests/language-feature/enums/enum-switch-2.slang
  tests/language-feature/enums/enum-switch.slang
  tests/language-feature/single-arg-ctor-call.slang
Labels: pr: non-breaking

#5356 Mark SPIRV artifact as non-executable.
  source/compiler-core/slang-artifact-desc-util.cpp
Labels: pr: non-breaking

#5361 Fix incorrect setting of array desc for 1d texture arrays in D3D12
  tools/gfx/d3d12/d3d12-device.cpp
Labels: pr: non-breaking

#5363 Fix UAV access for 3d texture mips
  tools/gfx/d3d12/d3d12-device.cpp
Labels: pr: non-breaking

#5358 Stdlib documentation for Atomic, Optional, Tuple
  source/slang/core.meta.slang
Labels: pr: non-breaking

#5355 Fix spirv codegen for pointer to empty structs.
  source/slang/slang-compiler-tu.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-legalize-types.cpp
  source/slang/slang-ir-lower-buffer-element-type.cpp
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-legalize-types.cpp
  tests/spirv/ptr-empty-struct.slang
  tests/spirv/ptr-unsized-array-2.slang
Labels: pr: non-breaking

#5367 Recognize a new spirv header json grammar keyword "aliases"
  source/compiler-core/slang-spirv-core-grammar.cpp
  tools/slang-lookup-generator/lookup-generator-main.cpp
Labels: pr: non-breaking

#5369 Document derivative core module functions
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#5373 Document bit operations
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#5374 Document the interfaces in the core module
  source/slang/core.meta.slang
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#5365 Fix several bugs with `specializeWithArgTypes()`
  source/slang/slang-compiler.h
  source/slang/slang-reflection-api.cpp
  source/slang/slang.cpp
  tools/slang-unit-test/unit-test-function-reflection.cpp
Labels: pr: non-breaking

#5396 Fix a few documentation typos
  docs/cpu-target.md
  docs/cuda-target.md
  docs/design/README.md
  docs/design/coding-conventions.md
  docs/design/interfaces.md
  docs/language-guide.md
Labels: pr: non-breaking

#5391 declutter top level CMakeLists.txt
  CMakeLists.txt
  cmake/LLVM.cmake
  examples/CMakeLists.txt
  prelude/CMakeLists.txt
  source/compiler-core/CMakeLists.txt
  source/core/CMakeLists.txt
  source/slang-glslang/CMakeLists.txt
  source/slang-rt/CMakeLists.txt
  source/slang-stdlib/CMakeLists.txt
  source/slang-wasm/CMakeLists.txt
  source/slangc/CMakeLists.txt
  tools/CMakeLists.txt
Labels: pr: non-breaking

#5395 Fix language server crash.
  source/slang/slang-check-decl.cpp
  tests/language-server/robustness-8.slang
Labels: pr: non-breaking

#5403 wasm: Add compile target option when creating slang session
  source/slang-wasm/slang-wasm-bindings.cpp
  source/slang-wasm/slang-wasm.cpp
  source/slang-wasm/slang-wasm.h
Labels: pr: non-breaking

#5404 Use DebugDeclare instead of DebugValue.
  source/slang/slang-emit-spirv-ops-debug-info-ext.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-addr-inst-elimination.cpp
  source/slang/slang-ir-insert-debug-value-store.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-legalize-types.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-lower-to-ir.cpp
  tests/spirv/debug-type-pointer-2.slang
  tests/spirv/debug-type-pointer.slang
Labels: pr: non-breaking

#5397 Describe experimental COM interfaces
  docs/design/README.md
  docs/design/experimental.md
  docs/user-guide/08-compiling.md
Labels: pr: non-breaking

#5402 Fix incorrect debug assert in `getLanguagePrelude`.
  source/slang/slang.cpp
Labels: pr: non-breaking

#5408 Switch back to fetching upstream llvm project
  .github/actions/common-setup/action.yml
Labels: pr: non-breaking

#5405 Replace stdlib on Slang API with CoreModule
  docs/build_reference.ps1
  docs/doc-system.md
  docs/stdlib-docgen.md
  include/slang.h
  source/core/slang-test-tool-util.cpp
  source/core/slang-test-tool-util.h
  source/slang-record-replay/record/slang-global-session.cpp
  source/slang-record-replay/record/slang-global-session.h
  source/slang-record-replay/replay/decoder-consumer.h
  source/slang-record-replay/replay/json-consumer.cpp
  source/slang-record-replay/replay/json-consumer.h
  source/slang-record-replay/replay/replay-consumer.cpp
  source/slang-record-replay/replay/replay-consumer.h
  source/slang-record-replay/replay/slang-decoder.cpp
  source/slang-record-replay/replay/slang-decoder.h
  source/slang-record-replay/util/emum-to-string.h
  source/slang-record-replay/util/record-format.h
  source/slang-stdlib/CMakeLists.txt
  source/slang-stdlib/slang-embedded-stdlib.cpp
  source/slang/slang-api.cpp
  source/slang/slang-compiler.h
  source/slang/slang-options.cpp
  source/slang/slang.cpp
  source/slangc/main.cpp
  tests/serialization/std-lib-serialize.slang
  tools/render-test/render-test-main.cpp
  tools/slang-test/slangc-tool.cpp
  tools/slang-test/test-context.h
  tools/test-server/test-server-main.cpp
Labels: pr: breaking change

#5411 Replace stdlib with core-module on files and projects
  .gitignore
  CMakeLists.txt
  docs/building.md
  source/slang-stdlib/CMakeLists.txt
  source/slang-stdlib/slang-embedded-core-module-source.cpp
  source/slang-stdlib/slang-embedded-core-module.cpp
  source/slang/CMakeLists.txt
  source/slang/slang-core-module-textures.cpp
  source/slang/slang-core-module-textures.h
  source/slang/slang-core-module.cpp
  tools/CMakeLists.txt
  tools/slang-test/parse-diagnostic-util.cpp
Labels: pr: non-breaking

#5400 Actions workflow to format code on command
  .github/workflows/format.yml
  .github/workflows/slash-command-dispatch.yml
  extras/formatting.sh
Labels: pr: non-breaking

#5418 Use github token for formatting command dispatch
  .github/workflows/slash-command-dispatch.yml
Labels: pr: non-breaking

#5414 Swap the term StdLib with Core-Module or Standard-Module in documents
  README.md
  docs/build_reference.ps1
  docs/cpu-target.md
  docs/cuda-target.md
  docs/design/autodiff/decorators.md
  docs/design/autodiff/types.md
  docs/design/capabilities.md
  docs/design/coding-conventions.md
  docs/design/interfaces.md
  docs/design/overview.md
  docs/design/serialization.md
  docs/design/stdlib-intrinsics.md
  docs/doc-system.md
  docs/gpu-feature/texture/footprint-queries.md
  docs/language-reference/04-types.md
  docs/language-reference/07-declarations.md
  docs/proposals/007-variadic-generics.md
  docs/proposals/008-tuples.md
  docs/proposals/010-new-diff-type-system.md
  docs/proposals/implementation/ast-ir-serialization.md
  docs/proposals/legacy/001-basic-interfaces.md
  docs/proposals/legacy/003-error-handling.md
  docs/stdlib-docgen.md
  docs/user-guide/00-introduction.md
  docs/user-guide/02-conventional-features.md
  docs/user-guide/07-autodiff.md
  docs/user-guide/08-compiling.md
  docs/user-guide/a1-03-obfuscation.md
  docs/user-guide/a1-04-interop.md
Labels: pr: non-breaking

#5412 Add `InterlockedAddF64` intrinsic.
  docs/user-guide/a3-02-reference-capability-atoms.md
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  tests/spirv/double-atomic-add-byte-address-buffer.slang
Labels: pr: non-breaking

#5413 Add implicit cast for generic vector types.
  source/slang/core.meta.slang
  tests/language-feature/generics/generic-vector-cast.slang
Labels: pr: non-breaking

#5419 Export language server to wasm.
  source/compiler-core/slang-language-server-protocol.h
  source/slang-wasm/CMakeLists.txt
  source/slang-wasm/slang-wasm-bindings.cpp
  source/slang-wasm/slang-wasm.cpp
  source/slang-wasm/slang-wasm.h
  source/slang/slang-language-server-completion.cpp
  source/slang/slang-language-server-completion.h
  source/slang/slang-language-server.cpp
  source/slang/slang-language-server.h
Labels: pr: non-breaking

#5420 More wasm binding for playground.
  source/slang-wasm/slang-wasm-bindings.cpp
  source/slang-wasm/slang-wasm.cpp
  source/slang-wasm/slang-wasm.h
  source/slang/slang.cpp
Labels: pr: non-breaking

#5410 Add documentation for buffer types
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#5394 Assorted auto-diff enhancements for increased performance & more streamlined auto-diff results
  source/core/slang-dictionary.h
  source/core/slang-hash.h
  source/slang/diff.meta.slang
  source/slang/slang-ir-autodiff-primal-hoist.cpp
  source/slang/slang-ir-autodiff-rev.cpp
  source/slang/slang-ir-autodiff-rev.h
  source/slang/slang-ir-autodiff-unzip.cpp
  source/slang/slang-ir-autodiff.cpp
  source/slang/slang-ir-dce.cpp
  source/slang/slang-ir-dce.h
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-layout.cpp
  source/slang/slang-ir-ssa-simplification.cpp
  source/slang/slang-ir-util.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-lower-to-ir.cpp
  tests/autodiff/high-order-backward-diff-3.slang
  tests/autodiff/high-order-backward-diff-4.slang
  tests/autodiff/path-tracer/pt-loop.slang
  tests/autodiff/reverse-continue-loop.slang
  tests/autodiff/reverse-control-flow-3.slang
  tests/autodiff/reverse-loop-checkpoint-test.slang
  tests/autodiff/reverse-loop.slang
  tests/autodiff/reverse-nested-calls.slang
  tests/autodiff/test-minimal-context.slang
Labels: pr: non-breaking

#5417 Rename a directory `source/slang-stdlib` to slang-core-module
  CMakeLists.txt
  source/slang-core-module/CMakeLists.txt
  source/slang-core-module/slang-embedded-core-module-source.cpp
  source/slang-core-module/slang-embedded-core-module.cpp
Labels: pr: non-breaking

#5415 Replace the word stdlib or standard-library with core-module for source code
  prelude/slang-cpp-scalar-intrinsics.h
  prelude/slang-cuda-prelude.h
  source/slang-core-module/slang-embedded-core-module-source.cpp
  source/slang/hlsl.meta.slang
  source/slang/slang-api.cpp
  source/slang/slang-ast-base.h
  source/slang/slang-ast-builder.cpp
  source/slang/slang-ast-builder.h
  source/slang/slang-ast-modifier.h
  source/slang/slang-ast-type.cpp
  source/slang/slang-ast-val.cpp
  source/slang/slang-check-conversion.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-overload.cpp
  source/slang/slang-check-shader.cpp
  source/slang/slang-check.h
  source/slang/slang-compiler.cpp
  source/slang/slang-compiler.h
  source/slang/slang-core-module-textures.cpp
  source/slang/slang-core-module.cpp
  source/slang/slang-doc-markdown-writer.cpp
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-ir-autodiff-fwd.cpp
  source/slang/slang-ir-autodiff-rev.cpp
  source/slang/slang-ir-glsl-legalize.cpp
  source/slang/slang-ir-inline.cpp
  source/slang/slang-ir-link.cpp
  source/slang/slang-ir-lower-combined-texture-sampler.cpp
  source/slang/slang-ir-lower-generics.cpp
  source/slang/slang-ir-obfuscate-loc.cpp
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-ir-synthesize-active-mask.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-ir.h
  source/slang/slang-lookup.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-options.cpp
  source/slang/slang-type-system-shared.h
  source/slang/slang.cpp
  tests/bugs/extension-lifetime.slang
  tests/diagnostics/bad-operator-call.slang
  tests/hlsl-intrinsic/matrix-double.slang
  tests/hlsl-intrinsic/wave.slang
Labels: pr: non-breaking

#5421 Improvements to formatting bot
  .github/actions/format-setup/action.yml
  .github/workflows/format.yml
  .github/workflows/slash-command-dispatch.yml
  extras/formatting.sh
Labels: pr: non-breaking

#5427 Correct URL in auto-format PR body
  .github/workflows/format.yml
Labels: pr: non-breaking

#5406 format cmake files
  CMakeLists.txt
  cmake/FetchedSharedLibrary.cmake
  cmake/GitHubRelease.cmake
  cmake/Glob.cmake
  cmake/LLVM.cmake
  cmake/SlangTarget.cmake
  external/CMakeLists.txt
  prelude/CMakeLists.txt
  source/core/CMakeLists.txt
  source/slang-core-module/CMakeLists.txt
  source/slang-glslang/CMakeLists.txt
  source/slang-rt/CMakeLists.txt
  source/slang-wasm/CMakeLists.txt
  source/slang/CMakeLists.txt
  tools/CMakeLists.txt
Labels: pr: non-breaking

#5422 preparation for clang format
  .clang-format
  .github/actions/format-setup/action.yml
  .github/workflows/check-formatting.yml
  examples/example-base/test-base.cpp
  examples/hello-world/vulkan-api.h
  external/.clang-format
  extras/.clang-format
  extras/formatting.sh
  include/.clang-format
  include/slang-gfx.h
  source/compiler-core/slang-artifact-desc-util.cpp
  source/compiler-core/slang-dxc-compiler.cpp
  source/compiler-core/slang-nvrtc-compiler.cpp
  source/core/slang-blob.h
  source/core/slang-chunked-list.h
  source/core/slang-common.h
  source/core/slang-crypto.h
  source/core/slang-file-system.h
  source/core/slang-free-list.h
  source/core/slang-hash.h
  source/core/slang-hex-dump-util.h
  source/core/slang-http.h
  source/core/slang-io.cpp
  source/core/slang-linked-list.h
  source/core/slang-list.h
  source/core/slang-math.h
  source/core/slang-memory-arena.h
  source/core/slang-persistent-cache.h
  source/core/slang-platform.h
  source/core/slang-random-generator.h
  source/core/slang-shared-library.h
  source/core/slang-short-list.h
  source/core/slang-smart-pointer.h
  source/core/slang-type-convert-util.h
  source/core/slang-type-text-util.cpp
  source/core/slang-type-text-util.h
  source/slang-glslang/slang-glslang.h
  source/slang-llvm/slang-llvm.cpp
  source/slang/slang-ast-iterator.h
  source/slang/slang-ast-support-types.h
  source/slang/slang-ast-val.h
  source/slang/slang-compiler.h
  source/slang/slang-emit-precedence.h
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-variable-scope-correction.h
  source/slang/slang-repro.cpp
  source/slang/slang-serialize-types.cpp
  source/slang/slang-syntax.cpp
  source/slang/slang-type-layout.h
  tools/gfx/open-gl/render-gl.cpp
  tools/gfx/simple-transient-resource-heap.h
  tools/gfx/vulkan/vk-api.h
  tools/render-test/shader-input-layout.cpp
Labels: pr: non-breaking

#5426 Use Offset instead of ConstOffset for GLSL function textureGatherOffset
  source/slang/hlsl.meta.slang
  tests/bugs/gh-5339.slang
  tests/glsl-intrinsic/intrinsic-texture.slang
Labels: pr: non-breaking

#5432 fix formatting issue
  source/slang-wasm/slang-wasm.h
Labels: pr: non-breaking

#5048 Precompiled SPIR-V import support
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-redundancy-removal.cpp
  tests/library/export-library-generics.slang
  tests/library/module-library-pointer-param.slang
  tests/library/precompiled-dxil-generics.slang
  tests/library/precompiled-spirv-generics.slang
  tests/library/precompiled-spirv-pointer-param.slang
Labels: pr: non-breaking

#5370 Put debug symbols in releases
  .github/actions/common-setup/action.yml
  .github/workflows/ci.yml
  .github/workflows/release-linux-glibc-2-17.yml
  .github/workflows/release.yml
  CMakePresets.json
  cmake/CCacheDebugInfoWorkaround.cmake
  docs/building.md
Labels: pr: non-breaking

#5428 format yaml and json
  .github/actions/format-setup/action.yml
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  .github/workflows/compile-regression-test.yml
  .github/workflows/ensure-pr-label.yml
  .github/workflows/falcor-compiler-perf-test.yml
  .github/workflows/falcor-test.yml
  .github/workflows/push-benchmark-results.yml
  .github/workflows/release-linux-glibc-2-17.yml
  .github/workflows/release.yml
  .github/workflows/slash-command-dispatch.yml
  .github/workflows/vk-gl-cts-nightly.yml
  CMakePresets.json
  docs/scripts/release-note.sh
  external/build-llvm.sh
  external/bump-glslang.sh
  extras/formatting.sh
  extras/macos-notarize.json
  extras/macos-sign.json
Labels: pr: non-breaking

#5459 fix release script
  .github/workflows/release.yml
Labels: pr: non-breaking

#5457 Correct formatting
  CMakePresets.json
Labels: pr: non-breaking

#5452 Fix vs build
  CMakePresets.json
Labels: pr: non-breaking

#5438 Add google analytics.
  docs/_layouts/user-guide.html
Labels: pr: non-breaking

#5455 Add design doc for write-only textures.
  docs/proposals/005-write-only-textures.md
Labels: pr: non-breaking

#5454 Write only texture types.
  source/slang/hlsl.meta.slang
  source/slang/slang-ast-type.cpp
  source/slang/slang-capabilities.capdef
  source/slang/slang-core-module-textures.cpp
  source/slang/slang-emit-cpp.cpp
  source/slang/slang-emit-cuda.cpp
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-hlsl.cpp
  source/slang/slang-emit-metal.cpp
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit-wgsl.cpp
  source/slang/slang-ir-specialize-resources.cpp
  source/slang/slang-ir.h
  source/slang/slang-type-system-shared.h
  source/slang/slang.cpp
  tests/wgsl/write-only-texture.slang
Labels: pr: non-breaking

#5460 Enhancements to diff script
  extras/formatting.sh
Labels: pr: non-breaking

#5436 Constant-fold for the type-casting in switch-case labels
  source/slang/slang-check-expr.cpp
  tests/bugs/gh-5372.slang
  tests/diagnostics/attribute-error.slang
Labels: pr: non-breaking

#5468 Add function of getting hash string to wasm binding
  source/slang-wasm/slang-wasm-bindings.cpp
  source/slang-wasm/slang-wasm.cpp
  source/slang-wasm/slang-wasm.h
  source/slang/slang-check-decl.cpp
Labels: pr: non-breaking
