Repository shader-slang/slang, pull requests merged in 2024-09, with the labels that each got.

#4984 Add Path::removeNonEmpty() to remove non-empty dir
  source/core/slang-io.cpp
  source/core/slang-io.h
  tools/slang-unit-test/unit-test-record-replay.cpp
Labels: pr: non-breaking

#4996 Push benchmark results to a viewable page
  .github/workflows/benchmark.yml
  .github/workflows/push-benchmark-results.yml
Labels: pr: non-breaking

#4977 Fix extension override behavior, and disallow extension on interface types.
  docs/user-guide/06-interfaces-generics.md
  source/slang/slang-check-constraint.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-inheritance.cpp
  source/slang/slang-check-overload.cpp
  source/slang/slang-diagnostic-defs.h
  tests/diagnostics/interfaces/interface-extension.slang
  tests/language-feature/extensions/extension-override.slang
Labels: pr: breaking change

#4982 Open existential on arguments after overload resolution.
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-overload.cpp
  tests/bugs/gh-4467.slang
Labels: pr: non-breaking

#4990 Fix resource specialization with `-embed-dxil`
  source/slang/slang-ir-specialize-resources.cpp
  tests/library/precompiled-module-library-resource.slang
Labels: pr: non-breaking

#4980 Preserve name in DeclRefExpr for correct highlighitng of `This`.
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-overload.cpp
  source/slang/slang-language-server-semantic-tokens.cpp
  source/slang/slang-language-server.cpp
  tests/language-server/this-type-hover.slang
Labels: pr: non-breaking

#4988 Add Documentation For Auto-Generated Constructors & Initializer Lists
  docs/user-guide/02-conventional-features.md
  docs/user-guide/toc.html
Labels: pr: non-breaking

#5008 Document All Capability Atoms and Profiles
  docs/user-guide/a2-target-specific-features.md
  docs/user-guide/a3-01-reference-capability-profiles.md
  docs/user-guide/a3-02-reference-capability-atoms.md
  docs/user-guide/a3-reference.md
  docs/user-guide/toc.html
  source/slang/slang-capabilities.capdef
  tools/slang-capability-generator/capability-generator-main.cpp
  tools/slang-capability-generator/slang-capability-diagnostic-defs.h
Labels: pr: non-breaking

#5014 Remove unused package in primary benchmark script
  .github/workflows/push-benchmark-results.yml
  tools/benchmark/compile.py
Labels: pr: non-breaking

#5013 Respect matrix layout in uniform and in/out parameters for HLSL target.
  source/slang/slang-check-decl.cpp
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-cuda.cpp
  source/slang/slang-emit-cuda.h
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-glsl.h
  source/slang/slang-emit-hlsl.cpp
  source/slang/slang-emit-hlsl.h
  source/slang/slang-emit-metal.cpp
  source/slang/slang-emit-metal.h
  source/slang/slang-type-layout.cpp
  tests/compute/constant-buffer-memory-packing.slang
  tests/language-feature/types/matrix-layout-uniform.slang
Labels: pr: non-breaking

#4986 Support `where` clause and type equality constraint.
  docs/user-guide/06-interfaces-generics.md
  docs/user-guide/toc.html
  source/slang/slang-ast-decl.h
  source/slang/slang-ast-iterator.h
  source/slang/slang-ast-support-types.h
  source/slang/slang-ast-type.h
  source/slang/slang-ast-val.h
  source/slang/slang-check-constraint.cpp
  source/slang/slang-check-conversion.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-inheritance.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir.cpp
  source/slang/slang-language-server-ast-lookup.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-parser.cpp
  source/slang/slang-syntax.cpp
  tests/bugs/eroneous-generic-parse.slang
  tests/bugs/eroneous-generic-parse.slang.expected
  tests/bugs/parser-infinite-loop.slang
  tests/bugs/parser-infinite-loop.slang.expected
  tests/language-feature/generics/where-1.slang
  tests/language-feature/generics/where-2.slang
  tests/language-feature/generics/where-3.slang
  tests/language-feature/generics/where-4.slang
Labels: pr: non-breaking

#5009 Fix spirv emit for global pointer variable.
  source/slang/slang-emit-spirv.cpp
  tests/spirv/global-pointer.slang
Labels: pr: non-breaking

#5012 Fix invalid documentsymbol error in langauge server.
  source/slang/slang-language-server-document-symbols.cpp
Labels: pr: non-breaking

#5011 Support entrypoints defined in a namespace.
  source/slang/slang-check-shader.cpp
  source/slang/slang-compiler.cpp
  source/slang/slang-compiler.h
  source/slang/slang.cpp
  tests/diagnostics/command-line/entry-point-redundant-stage.slang
  tests/language-feature/namespaces/entrypoint-in-namespace.slang
Labels: pr: non-breaking

#5010 Fix SPIRV SV_TessFactor type adaptation logic.
  source/slang/slang-ir-glsl-legalize.cpp
  tests/bugs/gh-4456.slang
Labels: pr: non-breaking

#4974 Initial -embed-spirv support
  include/slang.h
  source/slang/slang-compiler-tu.cpp
  source/slang/slang-compiler.cpp
  source/slang/slang-compiler.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-redundancy-removal.cpp
  source/slang/slang-ir-redundancy-removal.h
  source/slang/slang-ir.cpp
  source/slang/slang-options.cpp
  source/slang/slang.cpp
  tests/library/precompiled-dxil-generics.slang
  tests/library/precompiled-dxil-matrix.slang
  tests/library/precompiled-dxil.slang
  tests/library/precompiled-module-library-resource.slang
  tests/library/precompiled-spirv-generics.slang
  tools/gfx-unit-test/precompiled-module-2.cpp
Labels: pr: non-breaking

#5028 Remove incorrect UTF decode assert
  source/compiler-core/slang-source-loc.cpp
Labels: pr: non-breaking

#5024 Correct control flow in getParentBreakBlockSet
  source/slang/slang-ir-util.cpp
Labels: pr: non-breaking

#5037 Fix generic IInteger `mod` implementation.
  source/slang/core.meta.slang
  tests/bugs/gh-5026.slang
Labels: pr: non-breaking

#5006 Initial WGSL support
  include/slang.h
  source/compiler-core/slang-artifact-desc-util.cpp
  source/compiler-core/slang-artifact.h
  source/core/slang-type-text-util.cpp
  source/slang-record-replay/util/emum-to-string.h
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  source/slang/slang-compiler.cpp
  source/slang/slang-compiler.h
  source/slang/slang-doc-markdown-writer.cpp
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-wgsl.cpp
  source/slang/slang-emit-wgsl.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-link.cpp
  source/slang/slang-ir-lower-buffer-element-type.cpp
  source/slang/slang-ir-wgsl-legalize.cpp
  source/slang/slang-ir-wgsl-legalize.h
  source/slang/slang-profile.h
  source/slang/slang-type-layout.cpp
  source/slang/slang.cpp
Labels: pr: non-breaking

#5042 Fix compilation warning with uninitialized struct use in constructors
  source/slang/slang-ir-use-uninitialized-values.cpp
  tests/diagnostics/uninitialized-struct-from-constructor.slang
Labels: pr: non-breaking

#5046 Disambiguate subscript decls by preferring the one with more accessors.
  source/slang/slang-check-overload.cpp
  tests/language-feature/overloaded-subscript.slang
Labels: pr: non-breaking

#5047 Git-ignore for VIM temporary files
  .gitignore
Labels: pr: non-breaking

#5057 remove 'test-record-replay.sh'
  test-record-replay.sh
Labels: pr: non-breaking

#5060 Fix the issue in resolving the overload functions
  source/slang/slang-check-overload.cpp
  tests/bugs/overload-ambiguous.slang
Labels: pr: non-breaking

#5059 Remove includes of glslang private headers
  source/slang-glslang/slang-glslang.cpp
Labels: pr: non-breaking

#5068 release-note.sh fixes
  docs/scripts/release-note.sh
Labels: pr: non-breaking

#5078 Implement math intrinsics for WGSL
  include/slang.h
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  tests/wgsl/math.slang
  tools/slang-test/slang-test-main.cpp
  tools/slang-test/test-context.h
Labels: pr: non-breaking

#5096 Fix WGSL frexp and modf that returns a struct
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#5097 Add `IRWArray` interface, and make StructuredBuffer conform to them.
  docs/user-guide/06-interfaces-generics.md
  source/slang/core.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-ast-base.h
  source/slang/slang-ast-val.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-overload.cpp
  source/slang/slang-ir-use-uninitialized-values.cpp
  tests/diagnostics/inout-never-written.slang
  tests/language-feature/generics/irwarray.slang
Labels: pr: non-breaking

#5065 Lower the priority of looking up the rank of scope
  source/slang/slang-check-overload.cpp
  tests/bugs/overload-ambiguous-1.slang
  tests/bugs/overload-ambiguous-2.slang
  tests/bugs/overload-ambiguous.slang
  tests/diagnostics/overload-ambiguous.slang
Labels: pr: non-breaking

#5058 Report AD checkpoint contexts
  include/slang.h
  source/slang-record-replay/util/emum-to-string.h
  source/slang/slang-compiler.cpp
  source/slang/slang-compiler.h
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-addr-inst-elimination.cpp
  source/slang/slang-ir-autodiff-primal-hoist.cpp
  source/slang/slang-ir-autodiff-rev.cpp
  source/slang/slang-ir-autodiff-rev.h
  source/slang/slang-ir-autodiff-transcriber-base.cpp
  source/slang/slang-ir-autodiff-transpose.h
  source/slang/slang-ir-autodiff-unzip.cpp
  source/slang/slang-ir-autodiff-unzip.h
  source/slang/slang-ir-autodiff.cpp
  source/slang/slang-ir-clone.cpp
  source/slang/slang-ir-eliminate-phis.cpp
  source/slang/slang-ir-init-local-var.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-loop-unroll.cpp
  source/slang/slang-ir-ssa.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-options.cpp
  tests/autodiff/reverse-checkpoint-1.slang
  tests/autodiff/reverse-checkpoint-2.slang
  tests/autodiff/reverse-continue-loop.slang
  tests/autodiff/reverse-control-flow-1.slang
  tests/autodiff/reverse-control-flow-2.slang
  tests/autodiff/reverse-control-flow-3.slang
  tests/autodiff/reverse-loop-checkpoint-test.slang
  tests/autodiff/reverse-loop.slang
  tests/autodiff/reverse-nested-calls.slang
Labels: pr: non-breaking

#5071 Update auto-diff user guide
  docs/user-guide/07-autodiff.md
Labels: pr: non-breaking

#5031 Support `IDifferentiablePtrType`
  source/slang/core.meta.slang
  source/slang/slang-ast-builder.cpp
  source/slang/slang-ast-builder.h
  source/slang/slang-ast-support-types.h
  source/slang/slang-ast-type.h
  source/slang/slang-check-conformance.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-ir-autodiff-fwd.cpp
  source/slang/slang-ir-autodiff-pairs.cpp
  source/slang/slang-ir-autodiff-primal-hoist.cpp
  source/slang/slang-ir-autodiff-rev.cpp
  source/slang/slang-ir-autodiff-transcriber-base.cpp
  source/slang/slang-ir-autodiff-transcriber-base.h
  source/slang/slang-ir-autodiff-transpose.h
  source/slang/slang-ir-autodiff-unzip.cpp
  source/slang/slang-ir-autodiff.cpp
  source/slang/slang-ir-autodiff.h
  source/slang/slang-ir-check-differentiability.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir.cpp
  source/slang/slang-ir.h
  tests/autodiff/diff-ptr-type-call.slang
  tests/autodiff/diff-ptr-type-loop.slang
  tests/autodiff/diff-ptr-type-smoke.slang
Labels: pr: new feature, pr: non-breaking

#5086 Fix dx on vk with rhi
  external/CMakeLists.txt
Labels: goal:quality & productivity, pr: non-breaking

#5070 Use GITHUB_TOKEN if set
  CMakeLists.txt
  cmake/GitHubRelease.cmake
Labels: pr: non-breaking

#5114 Add WGSL intrinsics for synchronization
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
Labels: pr: non-breaking

#5110 Allow lookups of overloaded methods.
  include/slang.h
  source/slang/slang-check-shader.cpp
  source/slang/slang-compiler.h
  source/slang/slang-reflection-api.cpp
  source/slang/slang.cpp
  tools/slang-unit-test/unit-test-function-reflection.cpp
Labels: pr: breaking change

#5111 Synthesize conformance for generic requirements.
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-overload.cpp
  source/slang/slang-language-server-completion.cpp
  source/slang/slang-parser.cpp
  tests/language-feature/interfaces/generic-requirement-synth-2.slang
  tests/language-feature/interfaces/generic-requirement-synth.slang
Labels: pr: non-breaking

#5120 Re-enable slang-test for WGSL
  source/slang/hlsl.meta.slang
  tools/slang-test/slang-test-main.cpp
Labels: pr: non-breaking

#5112 Add diagnostic to verify the left hand side of a generic constraint.
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-diagnostic-defs.h
  tests/diagnostics/generic-constraint-left-hand-side.slang
Labels: pr: non-breaking

#5125 Initial `Atomic<T>` type implementation.
  docs/proposals/003-atomic-t.md
  source/slang/core.meta.slang
  source/slang/slang-ast-type.cpp
  source/slang/slang-ast-type.h
  source/slang/slang-check-expr.cpp
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-cpp.cpp
  source/slang/slang-emit-cuda.cpp
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-hlsl.cpp
  source/slang/slang-emit-hlsl.h
  source/slang/slang-emit-metal.cpp
  source/slang/slang-emit-metal.h
  source/slang/slang-emit-spirv-ops.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit-wgsl.cpp
  source/slang/slang-emit-wgsl.h
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-layout.cpp
  source/slang/slang-ir-lower-append-consume-structured-buffer.cpp
  source/slang/slang-ir-use-uninitialized-values.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-ir.h
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-type-layout.cpp
  tests/hlsl/append-structured-buffer.slang
  tests/language-feature/atomic-t/atomic-0.slang
  tests/language-feature/atomic-t/atomic-1.slang
  tests/language-feature/atomic-t/atomic-2.slang
Labels: pr: non-breaking

#5123 WGSL implement texture intrinsics except gather and sampler-less
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  source/slang/slang-emit-wgsl.cpp
  source/slang/slang-stdlib-textures.cpp
  source/slang/slang-stdlib-textures.h
  tests/wgsl/texture.slang
Labels: pr: non-breaking

#5129 Fix handling of pointer logic in wgsl backend.
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-wgsl.cpp
  source/slang/slang-emit-wgsl.h
  source/slang/slang-ir-wgsl-legalize.cpp
  tests/language-feature/atomic-t/atomic-0.slang
  tests/wgsl/inout.slang
Labels: pr: non-breaking

#5144 Fix incorrect use of pointer in WGSL
  source/slang/hlsl.meta.slang
  source/slang/slang-stdlib-textures.cpp
Labels: pr: non-breaking

#5130 Implemented Combined-texture for WGSL
  source/slang/slang-compiler.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-lower-combined-texture-sampler.cpp
  source/slang/slang-ir-lower-combined-texture-sampler.h
  source/slang/slang-type-layout.cpp
  tests/wgsl/texture-sampler-less.slang
Labels: pr: non-breaking

#5141 Feature/wgsl intrinsic texture gather
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  tests/wgsl/texture-sampler-less.slang
  tests/wgsl/texture.slang
Labels: pr: non-breaking

#5150 Fix the incorrect use of GLSL textureGather
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#5131 Enable emscripten builds to compile slang.dll to WebAssembly.
  CMakeLists.txt
  CMakePresets.json
  docs/building.md
  include/slang.h
  source/core/slang-io.cpp
  source/slang/slang-ast-dump.cpp
  source/slang/slang-parameter-binding.cpp
  source/slang/slang-workspace-version.cpp
  source/slang/slang-workspace-version.h
Labels: pr: non-breaking

#5069 Fixing bug when writing primitives in metal mesh shaders
  source/slang/slang-emit-metal.cpp
  tests/metal/simple-mesh.slang
  tests/metal/simple-task.slang
Labels: pr: non-breaking

#5145 Make release note generation script shebang portable
  docs/scripts/release-note.sh
Labels: pr: non-breaking

#5152 WGSL texture support for depth and multisampled
  source/slang/hlsl.meta.slang
  source/slang/slang-intrinsic-expand.cpp
  tests/wgsl/texture-gather.slang
  tests/wgsl/texture-load.slang
  tests/wgsl/texture.slang
Labels: pr: non-breaking

#5157 Always run AD cleanup pass.
  source/slang/slang-emit.cpp
  source/slang/slang-ir-autodiff.cpp
  tests/autodiff/no-diff-strip.slang
  tests/autodiff/no-diff-strip.slang.expected.txt
Labels: pr: non-breaking

#5155 Move texture format inference to frontend and add reflection api for it.
  include/slang-image-format-defs.h
  include/slang.h
  source/slang/slang-ast-modifier.h
  source/slang/slang-ast-support-types.h
  source/slang/slang-ast-type.cpp
  source/slang/slang-ast-type.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-check.h
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-image-format-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-resolve-texture-format.cpp
  source/slang/slang-ir-resolve-texture-format.h
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-reflection-api.cpp
  source/slang/slang-syntax.cpp
  tools/slang-unit-test/unit-test-image-format-reflection.cpp
Labels: pr: non-breaking

#5158 Implement texture_storage_Xd in WGSL
  source/slang/hlsl.meta.slang
  source/slang/slang-emit-wgsl.cpp
  tests/wgsl/texture-storage.slang
Labels: pr: non-breaking

#5171 export CMAKE_SYSTEM_PROCESSOR for cross compilation builds
  .github/workflows/release.yml
Labels: pr: non-breaking

#5170 Add fallback flag for sccache
  .github/actions/common-setup/action.yml
Labels: pr: non-breaking

#5164 Add CI step to build WebAssembly version of Slang
  .github/workflows/ci.yml
  docs/building.md
Labels: pr: non-breaking

#5177 Fix l-value computation for subscript call.
  source/slang/core.meta.slang
  source/slang/diff.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/hlsl.meta.slang.temp.h
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-overload.cpp
  tests/bugs/gh-4971-2.slang
  tests/bugs/gh-4971.slang
Labels: pr: non-breaking

#5180 Fix hull shader spirv legalization bug.
  source/slang/slang-ir-glsl-legalize.cpp
  tests/spirv/hull-shader.slang
Labels: pr: non-breaking

#5181 Fix bug in `translateGlslGlobalVar()`.
  source/slang/slang-ir-translate-glsl-global-var.cpp
  tests/bugs/gh-5027.slang
Labels: pr: non-breaking

#5182 Fix target switch lowering bug.
  source/slang/slang-lower-to-ir.cpp
Labels: pr: non-breaking

#5186 Disable wgpu on linux
  .github/workflows/release.yml
  external/CMakeLists.txt
Labels: pr: non-breaking

#5169 Add compile_commands.json to .gitignore
  .gitignore
Labels: pr: non-breaking

#5189 Switch sccache action to Mozilla-Actions version
  .github/actions/common-setup/action.yml
Labels: pr: non-breaking

#5196 Disable the building of slang-llvm when targeting wasm platform
  .github/workflows/ci.yml
Labels: pr: non-breaking
