Repository shader-slang/slang, pull requests merged in 2024-12, with the labels that each got.

#5621 [Docs] Minor fixes to auto-diff documentation
  docs/user-guide/07-autodiff.md
  source/slang/core.meta.slang
Labels: pr: non-breaking

#5708 Add WebGPU target doc
  docs/user-guide/09-targets.md
  docs/user-guide/toc.html
Labels: pr: non-breaking

#5669 Test varying inputs and outputs for wgsl
  tests/compute/constexpr.slang
  tests/metal/nested-struct-fragment-input.slang
  tests/metal/nested-struct-fragment-output.slang
  tests/metal/nested-struct-multi-entry-point-vertex.slang
  tests/metal/no-struct-vertex-output.slang
  tests/metal/sv_target-complex-1.slang
  tests/metal/sv_target-complex-2.slang
  tests/wgsl/semantic-coverage.slang
  tests/wgsl/semantic-depth.slang
  tests/wgsl/semantic-dispatch-thread-id.slang
  tests/wgsl/semantic-group-id.slang
  tests/wgsl/semantic-group-index.slang
  tests/wgsl/semantic-group-thread-id.slang
  tests/wgsl/semantic-instance-id.slang
  tests/wgsl/semantic-is-front-face.slang
  tests/wgsl/semantic-position.slang
  tests/wgsl/semantic-sample-index.slang
  tests/wgsl/semantic-vertex-id.slang
Labels: pr: non-breaking

#5675 Move c++ parsing code from slang-cpp-extractor to static library
  tools/CMakeLists.txt
  tools/slang-cpp-extractor/cpp-extractor-main.cpp
  tools/slang-cpp-extractor/macro-writer.cpp
  tools/slang-cpp-extractor/macro-writer.h
  tools/slang-cpp-extractor/unit-test.h
  tools/slang-cpp-parser/diagnostic-defs.h
  tools/slang-cpp-parser/diagnostics.cpp
  tools/slang-cpp-parser/diagnostics.h
  tools/slang-cpp-parser/file-util.cpp
  tools/slang-cpp-parser/file-util.h
  tools/slang-cpp-parser/identifier-lookup.cpp
  tools/slang-cpp-parser/identifier-lookup.h
  tools/slang-cpp-parser/node-tree.cpp
  tools/slang-cpp-parser/node-tree.h
  tools/slang-cpp-parser/node.cpp
  tools/slang-cpp-parser/node.h
  tools/slang-cpp-parser/options.cpp
  tools/slang-cpp-parser/options.h
  tools/slang-cpp-parser/parser.cpp
  tools/slang-cpp-parser/parser.h
  tools/slang-cpp-parser/unit-test.cpp
  tools/slang-cpp-parser/unit-test.h
Labels: pr: non-breaking

#5711 Fix typo in capdef file
  source/slang/slang-capabilities.capdef
Labels: pr: non-breaking

#5738 Core lib Metal math function fixes
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#5717 Conform non-suffixed integer literals
  docs/64bit-type-support.md
  docs/user-guide/02-conventional-features.md
  source/compiler-core/slang-lexer.cpp
  source/compiler-core/slang-lexer.h
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-parser.cpp
  tests/diagnostics/int-literal.slang
  tests/diagnostics/int-literal.slang.expected
  tests/hlsl-intrinsic/literal-int64.slang
  tests/hlsl-intrinsic/literal-int64.slang.expected.txt
  tests/slang-extension/atomic-int64-byte-address-buffer.slang
Labels: pr: breaking change

#5736 Add intrinsics for aligned load/store.
  docs/proposals/013-aligned-load-store.md
  source/slang/core.meta.slang
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  tests/spirv/aligned-load-store.slang
Labels: pr: non-breaking

#5746 Remove .clang-format from .gitignore
  .gitignore
Labels: pr: non-breaking

#5747 Run a do-nothing CI job for documentation changes
  .github/workflows/ci.yml
Labels: pr: non-breaking

#5735 Add emit logic for `requirePrelude` inst.
  source/slang/slang-emit-c-like.cpp
  tests/interop/require-prelude.slang
Labels: pr: non-breaking

#5740 Fix `SpvExecutionModeOutputLinesEXT`.
  source/slang/slang-check-decl.cpp
  source/slang/slang-emit-spirv.cpp
Labels: pr: non-breaking

#5731 WGPU: Add new test and explanation for disabled test
  tests/bugs/buffer-swizzle-store.slang
  tests/compute/structured-buffer-swizzle-store.slang
  tests/compute/structured-buffer-swizzle-store.slang.expected.txt
Labels: pr: non-breaking

#5758 Fix a regression that GL_EXT_samplerless_texture_functions is missing
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#5759 Relocate the step of 'Add bash to PATH'
  .github/workflows/ci.yml
Labels: pr: non-breaking

#5760 Make fvk-invert-y work on mesh shader ouptuts.
  source/slang/slang-ir-vk-invert-y.cpp
  tests/spirv/mesh-shader-invert-y.slang
Labels: pr: non-breaking

#5766 Fix compiler warning when using slang.h with gcc/clang on Windows
  include/slang.h
Labels: pr: non-breaking

#5762 Don't install .clang-format alongside headers
  CMakeLists.txt
Labels: pr: non-breaking

#5767 Remove duplicate call to install() for libslang
  CMakeLists.txt
  cmake/LLVM.cmake
  cmake/SlangTarget.cmake
  source/slang-glslang/CMakeLists.txt
  source/slang-rt/CMakeLists.txt
  source/slang/CMakeLists.txt
  source/slangc/CMakeLists.txt
  tools/CMakeLists.txt
Labels: pr: breaking change

#5763 Set prerelease and draft correctly for releases with draft in the tag
  .github/workflows/release.yml
Labels: pr: non-breaking

#5769 Set prerelease and draft correctly for centos releases
  .github/workflows/release-linux-glibc-2-17.yml
Labels: pr: non-breaking

#5734 Extended vector proposal
  docs/proposals/13-extended-length-vectors.md
Labels: pr: non-breaking, SPF:Proposal

#5716 Add wgsl missing float image format inference
  source/slang/slang-emit-wgsl.cpp
Labels: pr: non-breaking

#5772 Add API for getting last internal error message
  include/slang.h
  source/core/slang-signal.cpp
  source/core/slang-signal.h
  source/slang/slang-api.cpp
Labels: pr: non-breaking

#5777 Fix recursive function checks for Metal
  source/slang/slang-emit.cpp
  source/slang/slang-ir-check-recursion.cpp
  source/slang/slang-ir-check-recursion.h
  source/slang/slang-ir-check-recursive-type.cpp
  source/slang/slang-ir-check-unsupported-inst.cpp
  source/slang/slang-lower-to-ir.cpp
Labels: pr: non-breaking

#5778 Implement explciit binding for metal and wgsl.
  docs/user-guide/a2-02-metal-target-specific.md
  docs/user-guide/a2-03-wgsl-target-specific.md
  docs/user-guide/toc.html
  source/slang/slang-emit-wgsl.cpp
  source/slang/slang-parameter-binding.cpp
  tests/bugs/gh-471.slang
  tests/bugs/gh-775.slang
  tests/bugs/static-method.slang
  tests/bugs/static-var.slang
  tests/bugs/texture2d-gather.hlsl
  tests/bugs/type-legalize-bug-1.slang
  tests/compute/break-stmt.slang
  tests/compute/continue-stmt.slang
  tests/compute/default-initializer.slang
  tests/compute/explicit-this-expr.slang
  tests/compute/generics-constrained.slang
  tests/compute/global-init.slang
  tests/compute/implicit-generic-app.slang
  tests/compute/implicit-this-expr.slang
  tests/compute/init-list-defaults.slang
  tests/compute/inout.slang
  tests/compute/multiple-continue-sites.slang
  tests/compute/struct-default-init.slang
  tests/compute/switch-stmt.slang
  tests/compute/this-type.slang
  tests/compute/user-defined-initializer.slang
  tests/language-feature/properties/property-in-interface.slang
  tests/preprocessor/line-macro.slang
  tests/serialization/std-lib-serialize.slang
  tests/wgsl/explicit-binding.slang
Labels: pr: non-breaking

#5732 Split debug info for all targets
  .github/workflows/release.yml
  CMakeLists.txt
  CMakePresets.json
  cmake/CompilerFlags.cmake
  cmake/SlangTarget.cmake
  docs/building.md
Labels: pr: non-breaking

#5780 Support specialization constant on WGSL and Metal.
  docs/user-guide/a2-02-metal-target-specific.md
  docs/user-guide/a2-03-wgsl-target-specific.md
  docs/user-guide/toc.html
  source/slang/slang-emit-metal.cpp
  source/slang/slang-emit-metal.h
  source/slang/slang-emit-wgsl.cpp
  source/slang/slang-emit-wgsl.h
  source/slang/slang-ir-explicit-global-context.cpp
  source/slang/slang-parameter-binding.cpp
  source/slang/slang-type-layout.cpp
  tests/compute/generics-constrained.slang
  tests/spirv/specialization-constant.slang
Labels: pr: non-breaking

#5783 Emit debug info for Release builds
  .github/workflows/release-linux-glibc-2-17.yml
  .github/workflows/release.yml
  CMakeLists.txt
  cmake/SlangTarget.cmake
  docs/building.md
Labels: pr: non-breaking

#5786 Fix issue where `getTypeFullName` includes the strings from `__include` & `#include` directives
  source/slang/slang-ast-decl-ref.cpp
Labels: pr: non-breaking

#5789 Add Sampler*Shadow type aliases.
  source/slang/hlsl.meta.slang
  tests/spirv/sampler-shadow.slang
Labels: pr: non-breaking

#5796 Fix crash on recursive types.
  source/slang/slang-lower-to-ir.cpp
  tests/diagnostics/recursive-type.slang
Labels: pr: non-breaking

#5792 Report error on nested functions.
  source/slang/slang-parser.cpp
  tests/diagnostics/nested-func.slang
  tests/diagnostics/uninitialized-local-variables.slang
Labels: pr: non-breaking

#5791 Fix crash during emitCast of attributed type, allow MaxIters to take linktime const.
  source/slang/slang-ast-modifier.h
  source/slang/slang-check-modifier.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir.cpp
  source/slang/slang-lower-to-ir.cpp
  tests/bugs/gh-5781.slang
  tests/language-feature/constants/max-iters-link-time-const.slang
Labels: pr: non-breaking

#5793 Allow pointers to existential values.
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-type.cpp
  source/slang/slang-check.h
  source/slang/slang-ir-lower-buffer-element-type.cpp
  tests/bugs/gh-3825.slang
  tests/spirv/existential-ptr.slang
  tests/spirv/ptr-member-func.slang
  tests/spirv/ptr-unsized-array-3.slang
  tests/spirv/ptr-unsized-array-4.slang
  tools/render-test/render-test-main.cpp
Labels: pr: non-breaking

#5813 Fix parsing logic of for loops' initial statement.
  source/slang/slang-parser.cpp
  tests/language-feature/modules/typealias/lib.slang
  tests/language-feature/modules/typealias/main.slang
Labels: pr: non-breaking

#5814 Don't emit a warning when implicit casting from known in-range int lit to half.
  source/slang/slang-check-conversion.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-impl.h
  tests/bugs/half-coercion.slang
Labels: pr: non-breaking

#5818 Fix a crash when search for files.
  source/core/slang-string-util.cpp
  source/slang/slang.cpp
  tests/language-feature/modules/gh-5799/Common/Common.slang
  tests/language-feature/modules/gh-5799/Common/Test.slang
  tests/language-feature/modules/gh-5799/HelloTriangleFS.slang
  tests/language-feature/modules/gh-5799/Scene/Scene.slang
  tests/language-feature/modules/gh-5799/Simple.h
  tools/slang-test/slang-test-main.cpp
Labels: pr: non-breaking

#5817 Create scope for synthesized property decl.
  source/slang/slang-check-decl.cpp
  tests/bugs/dynamic-interface-property.slang
Labels: pr: non-breaking

#5807 Enable exprs for GLSL binding layout qualifiers
  source/slang/slang-ast-modifier.h
  source/slang/slang-check-impl.h
  source/slang/slang-check-modifier.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-parser.cpp
  tests/bugs/glsl-layout-define.hlsl.expected
  tests/diagnostics/unrecognized-glsl-layout-modifiers.slang
  tests/glsl-intrinsic/atomic/atomicCounterTestMultiple.slang
  tests/glsl-intrinsic/atomic/atomicErrorTest1.slang
  tests/glsl-intrinsic/atomic/atomicErrorTest3.slang
  tests/glsl-intrinsic/atomic/atomicErrorTest4.slang
  tests/glsl/layout-qualifier-exprs.slang
  tests/hlsl-intrinsic/image-swizzle-write.slang
Labels: pr: non-breaking

#5809 Correct proposal number
  docs/proposals/014-extended-length-vectors.md
Labels: pr: non-breaking

#5816 Enable WGSL tests that works for Metal related to Semantics
  tests/metal/nested-struct-fragment-input.slang
  tests/metal/nested-struct-fragment-output.slang
  tests/metal/nested-struct-multi-entry-point-vertex.slang
  tests/metal/no-struct-vertex-output.slang
  tests/metal/stage-in-2.slang
  tests/metal/sv_target-complex-1.slang
  tests/metal/sv_target-complex-2.slang
Labels: pr: non-breaking

#5819 A small mistake.
  tools/gfx/vulkan/vk-device.cpp
Labels: pr: non-breaking

#5831 Fix wgsl float texture format inference silent failure
  source/slang/slang-emit-wgsl.cpp
Labels: pr: non-breaking

#5823 Fix attribute reflection.
  include/slang.h
  source/slang/slang-check-modifier.cpp
  source/slang/slang-reflection-api.cpp
  tools/gfx/d3d12/d3d12-shader-object-layout.cpp
  tools/slang-unit-test/unit-test-attribute-reflection.cpp
  tools/slang-unit-test/unit-test-decl-tree-reflection.cpp
  tools/slang-unit-test/unit-test-function-reflection.cpp
Labels: pr: non-breaking

#5836 Fix loop hoisting logic in redundancy pass.
  source/slang/slang-ir-redundancy-removal.cpp
Labels: pr: non-breaking

#5837 Fix the logic to determine whether lower generic pass should run.
  source/slang/slang-emit.cpp
  tests/bugs/ptr-existential.slang
Labels: pr: non-breaking

#5841 Use perfect forwardnig to preserve the parameters for log
  examples/example-base/example-base.h
Labels: pr: non-breaking

#5842 LSP: fix "documentSymbol failed" error.
  source/slang/slang-language-server-document-symbols.cpp
Labels: pr: non-breaking

#5845 Fix language server check skipping when explicit module decl exists.
  source/slang/slang-check-decl.cpp
  source/slang/slang-compiler.h
  tests/language-server/check-skip-module.slang
Labels: pr: non-breaking

#5848 Fix prebuilt dependencies filenames on non-windows platforms
  cmake/FetchedSharedLibrary.cmake
Labels: pr: non-breaking

#5849 Correct casing of windows includes
  source/compiler-core/windows/slang-win-visual-studio-util.cpp
  source/core/slang-std-writers.cpp
Labels: pr: non-breaking

#5852 Add missing header for _getpid()
  source/core/windows/slang-win-process.cpp
Labels: pr: non-breaking

#5850 Reduce export size with gcc
  cmake/CompilerFlags.cmake
Labels: pr: non-breaking

#5851 Correctly distinguish between windows and MSVC
  include/slang.h
  source/compiler-core/windows/slang-win-visual-studio-util.cpp
  source/core/slang-allocator.h
  source/core/slang-platform.cpp
  source/core/slang-secure-crt.h
Labels: pr: non-breaking

#5853 Add SLANG_ENABLE_DXIL
  CMakeLists.txt
  cmake/CompilerFlags.cmake
  docs/building.md
Labels: pr: non-breaking

#5768 WGSL: Fix issue where global calls are generated
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-ir-legalize-global-values.cpp
  source/slang/slang-ir-legalize-global-values.h
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-ir-wgsl-legalize.cpp
  source/slang/slang-ir.cpp
  tests/expected-failure-github.txt
  tests/language-feature/constants/static-const-in-generic-interface.slang
Labels: pr: non-breaking

#5839 Add an example for using the reflection API
  examples/CMakeLists.txt
  examples/reflection-api/README.md
  examples/reflection-api/compute-simple.slang
  examples/reflection-api/main.cpp
  examples/reflection-api/raster-simple.slang
  include/slang.h
Labels: pr: non-breaking

#5846 use Release over RelWithDebInfo for ci
  .github/workflows/ci.yml
Labels: pr: non-breaking

#5847 Bit extract
  source/slang/core.meta.slang
  source/slang/glsl.meta.slang
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-glsl.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir.cpp
  tests/glsl-intrinsic/intrinsic-basic.slang
  tests/language-feature/bitfield/bitfield-extract.slang
  tests/language-feature/bitfield/bitfield-insert.slang
Labels: pr: non-breaking

#5857 Enable exprs for all supported GLSL layout qualifiers
  source/slang/slang-ast-modifier.h
  source/slang/slang-ast-print.cpp
  source/slang/slang-check-modifier.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-parameter-binding.cpp
  source/slang/slang-parser.cpp
  tests/glsl/layout-qualifier-exprs.slang
Labels: pr: non-breaking

#5877 install mono for toc generation
  .github/workflows/check-toc.yml
  .github/workflows/regenerate-toc.yml
Labels: pr: non-breaking

#5891 Support matrix negation in metal backend.
  source/slang/slang-emit-metal.cpp
  tests/metal/matrix-negate.slang
Labels: pr: non-breaking

#5888 Fix `getArgumentValueFloat` when arg is int.
  source/slang/slang-reflection-api.cpp
  tools/slang-unit-test/unit-test-attribute-reflection.cpp
Labels: pr: non-breaking

#5885 Fix entrypoint auto discovery logic.
  source/slang/slang.cpp
  tools/slang-unit-test/unit-test-cuda-compile.cpp
Labels: pr: non-breaking

#5895 Implement bitcast for 66-bit date type
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-hlsl.cpp
  source/slang/slang-emit-metal.cpp
  source/slang/slang-emit-metal.h
  source/slang/slang-emit-wgsl.cpp
  source/slang/slang-emit-wgsl.h
  tests/compute/bitcast-64bit.slang
  tests/compute/bitcast-64bit.slang.expected.txt
Labels: pr: non-breaking

#5890 Support specializing generic entrypoints in `findAndCheckEntryPoint`.
  source/slang/slang-check-shader.cpp
  tools/slang-unit-test/unit-test-generic-entrypoint.cpp
  tools/slang-unit-test/unit-test-glsl-compile.cpp
Labels: pr: non-breaking

#5887 Add verification logic on push and specialization constants.
  source/slang/slang-check-decl.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-parameter-binding.cpp
  tests/diagnostics/specialization-constants.slang
  tests/spirv/push-constant-space.slang
Labels: pr: non-breaking

#5879 Add slang example tests to CI
  .github/workflows/ci-examples.sh
  .github/workflows/ci.yml
  examples/autodiff-texture/main.cpp
  examples/example-base/test-base.cpp
  examples/model-viewer/main.cpp
  examples/platform-test/main.cpp
  examples/ray-tracing-pipeline/main.cpp
  examples/ray-tracing/main.cpp
  examples/shader-toy/main.cpp
  examples/triangle/main.cpp
  tests/expected-example-failure-github.txt
Labels: pr: non-breaking

#5889 Allow `Optional`, `Tuple` and `bool` to be used in varying input/output.
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-lower-buffer-element-type.cpp
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-parameter-binding.cpp
  source/slang/slang-type-layout.cpp
  source/slang/slang-type-system-shared.h
  tests/spirv/matrix-vertex-input.slang
  tests/spirv/optional-vertex-output.slang
Labels: pr: non-breaking

#5906 Fix metadata of register space and varying params.
  examples/reflection-api/README.md
  examples/reflection-api/main.cpp
  source/compiler-core/slang-artifact-associated-impl.h
  source/slang/slang-ir-metadata.cpp
  tools/slang-unit-test/unit-test-parameter-usage-reflection.cpp
Labels: pr: non-breaking

#5907 Support explicit `[vk::location(n)]` binding on metal/wgsl.
  docs/user-guide/a2-02-metal-target-specific.md
  docs/user-guide/a2-03-wgsl-target-specific.md
  source/slang/slang-parameter-binding.cpp
  tests/metal/explicit-location.slang
Labels: pr: non-breaking

#5910 Check decl nesting for namespaces.
  source/slang/slang-parser.cpp
  tests/diagnostics/invalid-namespace-nesting.slang
Labels: pr: non-breaking

#5912 Fix the parser issue for not recognize Generic<T>[N]
  source/slang/slang-parser.cpp
Labels: pr: non-breaking

#5904 Fixes for example CI integration
  tests/expected-example-failure-github.txt
Labels: pr: non-breaking

#5913 Fix issues reported by 'shellcheck'
  .github/workflows/ci-examples.sh
Labels: pr: non-breaking

#5899 Report error when generated spirv is empty.
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-spirv.cpp
  tests/spirv/empty-module.slang
Labels: pr: non-breaking

#5901 Add HLSL texture sample with status intrinsics
  source/slang/hlsl.meta.slang
  tests/hlsl-intrinsic/texture/texture-intrinsics.slang
Labels: pr: non-breaking

#5915 Enable more examples in CI
  .github/workflows/ci-examples.sh
  .github/workflows/ci.yml
  tests/expected-example-failure-github.txt
Labels: pr: non-breaking

#5918 Add base vertex and base instance system values
  docs/user-guide/a2-01-spirv-target-specific.md
  docs/user-guide/a2-02-metal-target-specific.md
  source/slang/glsl.meta.slang
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-glsl-legalize.cpp
  source/slang/slang-ir-legalize-varying-params.h
  source/slang/slang-ir-metal-legalize.cpp
  source/slang/slang-ir-wgsl-legalize.cpp
  source/slang/slang-language-server-completion.cpp
  tests/glsl-intrinsic/system-values-draw-parameters.slang
  tests/hlsl-intrinsic/system-values-draw-parameters.slang
Labels: pr: non-breaking

#5920 Fix crash during loop unrolling.
  source/slang/slang-ir-loop-unroll.cpp
  tests/ir/loop-unroll-3.slang
Labels: pr: non-breaking

#5922 Check subscript/property accessor for differentiability.
  source/slang/slang-check-decl.cpp
  source/slang/slang-syntax.cpp
  tests/autodiff/subscript.slang
Labels: pr: non-breaking

#5927 Fixed "stage:" and "result:" field names for JSON reflection
  source/slang/slang-reflection-json.cpp
  tests/bindings/hlsl-to-vulkan-array.hlsl.expected
  tests/bindings/hlsl-to-vulkan-combined.hlsl.expected
  tests/bindings/hlsl-to-vulkan-global.hlsl.expected
  tests/bindings/hlsl-to-vulkan-shift-implicit.hlsl.expected
  tests/bindings/hlsl-to-vulkan-shift.hlsl.expected
  tests/cross-compile/cpp-resource-reflection.slang.32.expected
  tests/cross-compile/cpp-resource-reflection.slang.64.expected
  tests/cuda/cuda-reflection.slang.expected
  tests/hlsl-intrinsic/sampler-feedback/sampler-feedback-basic.slang.expected
  tests/ir/string-literal-hash-reflection.slang.expected
  tests/reflection/actual-global.slang.expected
  tests/reflection/arrays.hlsl.expected
  tests/reflection/attribute.slang.expected
  tests/reflection/binding-gl.hlsl.expected
  tests/reflection/binding-push-constant-gl.hlsl.expected
  tests/reflection/buffer-layout.slang.1.expected
  tests/reflection/buffer-layout.slang.expected
  tests/reflection/cross-compile.slang.expected
  tests/reflection/default-space.slang.expected
  tests/reflection/explicit-register-space.slang.expected
  tests/reflection/gh-55.glsl.expected
  tests/reflection/global-type-params.slang.expected
  tests/reflection/global-uniforms.hlsl.expected
  tests/reflection/matrix-layout.slang.1.expected
  tests/reflection/matrix-layout.slang.expected
  tests/reflection/mix-explicit-and-implicit-spaces.slang.expected
  tests/reflection/multi-file.hlsl.expected
  tests/reflection/parameter-block-explicit-space.slang.expected
  tests/reflection/parameter-block.slang.1.expected
  tests/reflection/parameter-block.slang.2.expected
  tests/reflection/parameter-block.slang.expected
  tests/reflection/ptr/ptr-generic.slang.expected
  tests/reflection/ptr/ptr-global.slang.expected
  tests/reflection/ptr/ptr-self-reference.slang.expected
  tests/reflection/ptr/ptr-struct.slang.expected
  tests/reflection/reflect-imported-code.hlsl.expected
  tests/reflection/reflect-static.slang.expected
  tests/reflection/reflection0.hlsl.expected
  tests/reflection/resource-in-cbuffer.hlsl.expected
  tests/reflection/sample-index-input.hlsl.expected
  tests/reflection/sample-rate-input.hlsl.expected
  tests/reflection/shared-modifier.hlsl.expected
  tests/reflection/std430-layout.glsl.expected
  tests/reflection/structured-buffer.slang.expected
  tests/reflection/thread-group-size.hlsl.expected
  tests/reflection/unbounded-arrays.hlsl.1.expected
  tests/reflection/used-parameters.slang.expected
  tests/reflection/vertex-input-semantics.hlsl.expected
  tests/slang-extension/dynamic-resource-gl.slang.1.expected
Labels: pr: non-breaking

#5935 update CTS package
  .github/workflows/vk-gl-cts-nightly.yml
Labels: pr: non-breaking

#5936 Reflection API Wasm Bindings Part1
  source/slang-wasm/CMakeLists.txt
  source/slang-wasm/slang-wasm-bindings.cpp
  source/slang-wasm/slang-wasm.cpp
  source/slang-wasm/slang-wasm.h
Labels: pr: non-breaking

#5929 Support dispatchComputeIndirect and draw(Indexed)Indirect with count buffer for Vulkan
  tools/gfx/vulkan/vk-api.h
  tools/gfx/vulkan/vk-command-encoder.cpp
Labels: pr: non-breaking

#5939 Add packed 8bit builtin types
  source/slang-core-module/slang-embedded-core-module-source.cpp
  source/slang/slang-check-conversion.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-cpp.cpp
  source/slang/slang-emit-cuda.cpp
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-hlsl.cpp
  source/slang/slang-emit-metal.cpp
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit-wgsl.cpp
  source/slang/slang-ir-any-value-marshalling.cpp
  source/slang/slang-ir-byte-address-legalize.cpp
  source/slang/slang-ir-layout.cpp
  source/slang/slang-ir-lower-bit-cast.cpp
  source/slang/slang-ir-util.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-mangle.cpp
  source/slang/slang-type-layout.cpp
  source/slang/slang-type-system-shared.h
  source/slang/slang.cpp
  tests/hlsl-intrinsic/packed/packed-types-error.slang
  tests/hlsl-intrinsic/packed/packed-types-warning.slang
  tests/hlsl-intrinsic/packed/packed-types.slang
  tests/hlsl-intrinsic/packed/packed-types.slang.expected.txt
Labels: pr: non-breaking

#5932 Fix parsing GLSL SSBO arrays / bindless descriptors
  source/slang/slang-check-expr.cpp
  source/slang/slang-parser.cpp
Labels: pr: non-breaking

#5953 Prevent constant folding for specialization constants
  source/slang/slang-check-expr.cpp
Labels: pr: non-breaking

#5952 Fix invalid uninitialized-use warning on hitAttributeEXT-decorated globals
  source/slang/slang-ir-use-uninitialized-values.cpp
Labels: pr: non-breaking

#5923 Add a basic WebGPU example
  examples/wgpu-html5/README.md
  examples/wgpu-html5/build.py
  examples/wgpu-html5/example.js
  examples/wgpu-html5/index.html
  examples/wgpu-html5/shader.slang
Labels: pr: non-breaking

#5965 Fix witness lookup to prefer decls in the same parent as the inheritance decl.
  source/core/slang-list.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-syntax.cpp
  source/slang/slang-syntax.h
  tests/language-feature/interfaces/overloaded-associatedtype.slang
Labels: pr: non-breaking

#5967 Add `RaytracingAccelerationStructure::__init(uint64_t)`.
  source/slang/hlsl.meta.slang
  source/slang/slang-emit-glsl.cpp
  tests/spirv/u-to-accelstruct.slang
Labels: pr: non-breaking

#5968 LanguageServer: fix highlighting of wrapper type.
  source/slang/slang-check-decl.cpp
  source/slang/slang-language-server-ast-lookup.cpp
  source/slang/slang-language-server-semantic-tokens.cpp
Labels: pr: non-breaking

#5966 Check for undefined %id in spirv_asm block.
  source/slang/slang-check-expr.cpp
  source/slang/slang-diagnostic-defs.h
  tests/diagnostics/invalid-spv-obj.slang
Labels: pr: non-breaking

#5971 Fix `getInheritanceInfo` for `ExtractExistentialType`.
  source/slang/slang-check-impl.h
  source/slang/slang-check-inheritance.cpp
  source/slang/slang-ir-legalize-types.cpp
  source/slang/slang-syntax.cpp
  tests/language-feature/interfaces/gh-5900.slang
Labels: pr: non-breaking

#5974 Add terminateRayEXT & ignoreIntersectionEXT to glsl.meta.slang
  source/slang/glsl.meta.slang
Labels: pr: non-breaking
