Repository shader-slang/slang, pull requests merged in 2024-05, with the labels that each got.

#4065 Adds functionality to dump IR to stdout
  source/slang/slang-ir.cpp
  source/slang/slang-ir.h
Labels: goal:quality & productivity

#4092 Utilize vector operations over scalar if possible
  source/slang/hlsl.meta.slang
  tests/glsl-intrinsic/intrinsic-basic.slang
Labels: kind:cleanup, GoodFirstBug

#4132 Make sure pointer local vars have `AliasedPointer` decoration.
  source/slang/slang-emit-spirv.cpp
  tests/bugs/gh-4111.slang
Labels: pr: non-breaking

#4122 capture/replay: interface implementation 1
  build/visual-studio/slang/slang.vcxproj
  build/visual-studio/slang/slang.vcxproj.filters
  premake5.lua
  source/slang-capture-replay/capture_utility.cpp
  source/slang-capture-replay/capture_utility.h
  source/slang-capture-replay/slang-filesystem.cpp
  source/slang-capture-replay/slang-filesystem.h
  source/slang-capture-replay/slang-global-session.cpp
  source/slang-capture-replay/slang-global-session.h
  source/slang-capture-replay/slang-session.cpp
  source/slang-capture-replay/slang-session.h
  source/slang/CMakeLists.txt
  source/slang/slang-api.cpp
Labels: pr: new feature, pr: non-breaking

#4119 [gfx] Cache mutable root shader object in Vulkan
  tools/gfx/d3d12/d3d12-shader-object.h
  tools/gfx/renderer-shared.h
  tools/gfx/vulkan/vk-base.h
  tools/gfx/vulkan/vk-command-buffer.h
  tools/gfx/vulkan/vk-command-encoder.cpp
  tools/gfx/vulkan/vk-command-encoder.h
  tools/gfx/vulkan/vk-device.cpp
  tools/gfx/vulkan/vk-shader-object.h
  tools/gfx/vulkan/vk-transient-heap.cpp
Labels: pr: non-breaking

#4133 Fix NonUniformResourceIndex legalization for SPIRV.
  source/slang/slang-ir-spirv-legalize.cpp
  tests/bugs/gh-4131.slang
Labels: pr: non-breaking

#4134 Fix crash in obfuscation
  source/slang/slang-ir-obfuscate-loc.cpp
Labels: kind:bug, pr: non-breaking

#4141 Fix legalization of `kIROp_GetLegalizedSPIRVGlobalParamAddr`.
  source/slang/hlsl.meta.slang
  source/slang/slang-ir-spirv-legalize.cpp
  tests/spirv/image-atomic-array-2.slang
  tests/spirv/image-atomic-array.slang
Labels: pr: non-breaking

#4140 `slangc` tool experience improvements.
  docs/command-line-slangc-reference.md
  source/slang/slang-options.cpp
  source/slang/slang.cpp
Labels: pr: new feature, pr: non-breaking

#4139 Support [__ref] attribute to make this pass by reference.
  source/slang/core.meta.slang
  source/slang/slang-ast-modifier.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-overload.cpp
  source/slang/slang-lookup.cpp
  source/slang/slang-lower-to-ir.cpp
  tests/spirv/ref-this.slang
Labels: pr: new feature, pr: non-breaking

#4138 Support `getAddress` of a single-element vector swizzle.
  source/slang/slang-lower-to-ir.cpp
  tests/spirv/ptr-vector-member.slang
  tests/spirv/vector-member-atomic.slang
Labels: pr: non-breaking

#4137 Metal: propagate and specialize address space.
  build/visual-studio/slang/slang.vcxproj
  build/visual-studio/slang/slang.vcxproj.filters
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-metal.cpp
  source/slang/slang-emit-metal.h
  source/slang/slang-ir-metal-legalize.cpp
  source/slang/slang-ir-specialize-address-space.cpp
  source/slang/slang-ir-specialize-address-space.h
  tests/metal/out-param.slang
Labels: pr: non-breaking

#4136 Add stdlib tests for `clamp` derivatives which also checks `max` and `min` derivatives
  tests/autodiff-dstdlib/dstdlib-clamp.slang
  tests/autodiff-dstdlib/dstdlib-clamp.slang.expected.txt
Labels: pr: non-breaking

#4144 fix typo in help and docs
  docs/command-line-slangc-reference.md
  source/core/slang-type-text-util.cpp
Labels: pr: non-breaking

#4143 More Metal Intrinsics.
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-metal.cpp
  source/slang/slang-emit-metal.h
  tests/glsl-intrinsic/intrinsic-basic.slang
  tests/metal/barrier.slang
  tests/metal/discard.slang
Labels: pr: non-breaking

#4152 Fix race-condition and visual artifacts issues
  slang.h
  source/core/slang-performance-profiler.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-options.cpp
  tests/autodiff/path-tracer/pt-loop.slang
  tests/autodiff/reverse-while-loop-2.slang
  tests/cross-compile/loop-attribs.slang
  tests/ir/loop-inversion.slang
Labels: pr: breaking change

#4148 [gfx] add missing Result to IRayTracingCommandEncoder::bindPipline
  slang-gfx.h
  tools/gfx/d3d12/d3d12-command-encoder.cpp
  tools/gfx/d3d12/d3d12-command-encoder.h
  tools/gfx/debug-layer/debug-command-encoder.cpp
  tools/gfx/debug-layer/debug-command-encoder.h
  tools/gfx/gfx.slang
  tools/gfx/vulkan/vk-command-encoder.cpp
  tools/gfx/vulkan/vk-command-encoder.h
Labels: pr: non-breaking

#4149 [gfx] specify resource view buffer range in bytes
  .github/workflows/falcor-test.yml
  examples/autodiff-texture/main.cpp
  examples/ray-tracing-pipeline/main.cpp
  examples/ray-tracing/main.cpp
  slang-gfx.h
  tools/gfx-unit-test/buffer-barrier-test.cpp
  tools/gfx-unit-test/nested-parameter-block.cpp
  tools/gfx/d3d12/d3d12-command-encoder.cpp
  tools/gfx/d3d12/d3d12-device.cpp
  tools/gfx/d3d12/d3d12-resource-views.cpp
  tools/gfx/d3d12/d3d12-resource-views.h
  tools/gfx/d3d12/d3d12-shader-object.cpp
  tools/gfx/gfx.slang
  tools/gfx/vulkan/vk-command-encoder.cpp
  tools/gfx/vulkan/vk-device.cpp
  tools/render-test/render-test-main.cpp
Labels: pr: breaking change

#4066 Add LoadAligned and StoreAligned methods to ByteAddressBuffers
  source/slang/core.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-byte-address-legalize.cpp
  source/slang/slang-ir-byte-address-legalize.h
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-layout.cpp
  source/slang/slang-ir-peephole.cpp
  tests/compute/byte-address-buffer-align-error.slang
  tests/compute/byte-address-buffer-aligned.slang
  tests/compute/byte-address-buffer-array.slang
Labels: kind:enhancement, goal:client support, pr: non-breaking

#4135 Slang: Support UTF-8 with Byte Order Markers
  source/compiler-core/slang-json-lexer.cpp
  source/compiler-core/slang-source-loc.cpp
  source/core/slang-char-encode.cpp
  tests/bugs/implicit-cast.slang.expected.txt
  tests/preprocessor/utf16_be_bom_crlf.slang
  tests/preprocessor/utf16_le_bom_crlf.slang
  tests/preprocessor/utf8_bom_crlf.slang
Labels: pr: non-breaking

#4162 Fix CFG reversal logic for loops with an inner condition.
  source/slang/slang-ir-autodiff-transpose.h
  tests/autodiff/reverse-while-loop-2.slang
Labels: pr: non-breaking

#4158 Implement texture functions for Metal target
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  source/slang/slang-emit-metal.cpp
  source/slang/slang-stdlib-textures.cpp
  source/slang/slang-stdlib-textures.h
  tests/metal/texture.slang
Labels: pr: non-breaking

#4170 Remove use of `G0` and `__target_intrinsic` in stdlib.
  source/slang/core.meta.slang
  source/slang/diff.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-ast-stmt.h
  source/slang/slang-check-impl.h
  source/slang/slang-check-stmt.cpp
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-cpp.cpp
  source/slang/slang-emit-cpp.h
  source/slang/slang-emit-cuda.cpp
  source/slang/slang-emit-cuda.h
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-intrinsic-expand.cpp
  source/slang/slang-intrinsic-expand.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-lower-generic-call.cpp
  source/slang/slang-ir-lower-generic-function.cpp
  source/slang/slang-ir-specialize-function-call.cpp
  source/slang/slang-ir-specialize-resources.cpp
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-parser.cpp
  tests/cuda/cuda-array-layout.slang
  tests/cuda/cuda-array-layout.slang.expected.txt
  tests/glsl-intrinsic/intrinsic-basic.slang
  tests/spirv/global-compute.slang
Labels: pr: non-breaking

#4145 Capabilities System, CapabilitySet Logic Overhaul
  source/core/slang-linked-list.h
  source/core/slang-uint-set.cpp
  source/core/slang-uint-set.h
  source/slang/glsl.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-ast-dump.cpp
  source/slang/slang-capabilities.capdef
  source/slang/slang-capability.cpp
  source/slang/slang-capability.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-modifier.cpp
  source/slang/slang-check-shader.cpp
  source/slang/slang-check-stmt.cpp
  source/slang/slang-compiler.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-ir-link.cpp
  source/slang/slang-ir-specialize-target-switch.cpp
  source/slang/slang-ir-specialize-target-switch.h
  source/slang/slang-ir.cpp
  source/slang/slang-serialize-ast-type-info.h
  source/slang/slang.cpp
  source/slang/slang.natvis
  tests/language-feature/capability/capability1.slang
  tests/language-feature/capability/capability2.slang
  tests/language-feature/capability/capability3.slang
  tests/language-feature/capability/capability4.slang
  tests/language-feature/capability/specializeTargetSwitch.slang
  tests/metal/texture.slang
  tools/slang-capability-generator/capability-generator-main.cpp
Labels: pr: non-breaking

#4173 Fixes running examples from generated SLN
  CMakeLists.txt
Labels: pr: non-breaking

#4175 RasterizerOrder resource for spirv and metal.
  source/slang/core.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-ast-modifier.h
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-metal.cpp
  source/slang/slang-emit-metal.h
  source/slang/slang-emit-spirv-ops.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-byte-address-legalize.cpp
  source/slang/slang-ir-byte-address-legalize.h
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-ir.cpp
  tests/hlsl/raster-order-resource.slang
  tests/metal/byte-address-buffer.slang
Labels: pr: new feature, pr: non-breaking

#4179 Add member init expressions and constructor logic to docs
  docs/user-guide/03-convenience-features.md
Labels: pr: non-breaking

#4183 `-ignore-capabilities` now skips the capability pass 100%
  source/slang/slang-check-decl.cpp
  tests/language-feature/capability/intrinsic-texture-ignore-capability.slang
Labels: pr: non-breaking

#4177 capture/relay: Add capture interface classes
  build/visual-studio/slang/slang.vcxproj
  build/visual-studio/slang/slang.vcxproj.filters
  source/slang-capture-replay/capture_utility.h
  source/slang-capture-replay/slang-composite-component-type.cpp
  source/slang-capture-replay/slang-composite-component-type.h
  source/slang-capture-replay/slang-entrypoint.cpp
  source/slang-capture-replay/slang-entrypoint.h
  source/slang-capture-replay/slang-filesystem.cpp
  source/slang-capture-replay/slang-global-session.cpp
  source/slang-capture-replay/slang-module.cpp
  source/slang-capture-replay/slang-module.h
  source/slang-capture-replay/slang-session.cpp
  source/slang-capture-replay/slang-session.h
  source/slang-capture-replay/slang-type-conformance.cpp
  source/slang-capture-replay/slang-type-conformance.h
  source/slang/slang-compiler.h
  source/slang/slang.cpp
Labels: pr: non-breaking

#4180 Test binding index for combined and not-combined textures
  tests/metal/texture-binding-index.slang
Labels: pr: non-breaking

#4184 SPIR-V support for GLSL texture functions
  source/slang/glsl.meta.slang
  tests/glsl-intrinsic/intrinsic-texture.slang
Labels: pr: non-breaking

#4186 Add `-minimum-slang-optimization` to favor compile time.
  slang.h
  source/slang/slang-api.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-compiler-options.h
  source/slang/slang-compiler.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-autodiff-fwd.cpp
  source/slang/slang-ir-inline.cpp
  source/slang/slang-ir-inline.h
  source/slang/slang-ir-lower-generics.cpp
  source/slang/slang-ir-simplify-cfg.cpp
  source/slang/slang-ir-specialize-function-call.cpp
  source/slang/slang-ir-specialize-resources.cpp
  source/slang/slang-ir-specialize.cpp
  source/slang/slang-ir-ssa-simplification.cpp
  source/slang/slang-ir-ssa-simplification.h
  source/slang/slang-options.cpp
  source/slang/slang.cpp
Labels: pr: new feature, pr: non-breaking

#4190 Printing a timing of stdlib build time
  source/slang/slang.cpp
Labels: pr: non-breaking

#4193 Increase CMake version requirement from 3.20 to 3.25
  CMakeLists.txt
  CONTRIBUTION.md
Labels: pr: non-breaking

#4203 Fix all Clang-14 warnings
  source/slang/slang-capability.cpp
  source/slang/slang-check-conformance.cpp
  source/slang/slang-compiler.cpp
  source/slang/slang-ir-autodiff-unzip.h
  source/slang/slang-ir-insert-debug-value-store.cpp
  source/slang/slang-ir-lower-buffer-element-type.cpp
  source/slang/slang-ir-metal-legalize.cpp
  source/slang/slang-ir-pytorch-cpp-binding.cpp
  source/slang/slang-ir-uniformity.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-parser.cpp
  source/slang/slang-type-layout.cpp
  tools/gfx/vulkan/vk-device.cpp
  tools/slang-capability-generator/capability-generator-main.cpp
Labels: pr: non-breaking

#4214 Update vk-gl-cts-nightly.yml
  .github/workflows/vk-gl-cts-nightly.yml
Labels: pr: non-breaking

#4219 Make CTS nightly run reporting status to our slack channel.
  .github/workflows/vk-gl-cts-nightly.yml
Labels: pr: non-breaking

#4217 Fix pointers link in userguide
  docs/user-guide/toc.html
Labels: pr: non-breaking

#4224 Fix pointer example
  docs/user-guide/03-convenience-features.md
Labels: pr: non-breaking

#4225 If no sample is set with a `Texture(.*)MS[]` operation, set sample to 0.
  source/slang/hlsl.meta.slang
  tests/bugs/gh-4200.slang
Labels: pr: non-breaking

#4222 Fix clang-18 build
  source/core/slang-performance-profiler.cpp
Labels: pr: non-breaking

#3460 Add support for callable shaders in gfx
  slang-gfx.h
  tools/gfx/d3d12/d3d12-command-encoder.cpp
  tools/gfx/d3d12/d3d12-shader-table.cpp
  tools/gfx/d3d12/d3d12-shader-table.h
  tools/gfx/renderer-shared.cpp
  tools/gfx/renderer-shared.h
  tools/gfx/vulkan/vk-command-encoder.cpp
  tools/gfx/vulkan/vk-shader-table.cpp
Labels: pr: breaking change

#4226 CTS: stage some known failure tests for now
  .github/workflows/vk-gl-cts-nightly.yml
Labels: pr: non-breaking

#4227 Simplify test file names for slang-test
  tools/slang-test/options.cpp
  tools/slang-test/options.h
Labels: GoodFirstBug, kind:testing, pr: non-breaking

#4210 Print memory leak info in Debug build of slangc.exe
  source/core/slang-std-writers.cpp
  source/slangc/main.cpp
Labels: GoodFirstBug, pr: non-breaking

#4240 Add options to speedup compilation.
  build/visual-studio/slang/slang.vcxproj
  build/visual-studio/slang/slang.vcxproj.filters
  slang.h
  source/core/slang-common.h
  source/slang/hlsl.meta.slang
  source/slang/slang-compiler-options.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-dce.cpp
  source/slang/slang-ir-dce.h
  source/slang/slang-ir-inline.cpp
  source/slang/slang-ir-inline.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-legalize-types.cpp
  source/slang/slang-ir-lower-generics.cpp
  source/slang/slang-ir-lower-generics.h
  source/slang/slang-ir-lower-size-of.cpp
  source/slang/slang-ir-lower-size-of.h
  source/slang/slang-ir-peephole.cpp
  source/slang/slang-ir-specialize-resources.cpp
  source/slang/slang-ir-specialize.cpp
  source/slang/slang-ir-ssa-simplification.cpp
  source/slang/slang-ir-uniformity.cpp
  source/slang/slang-ir-util.cpp
  source/slang/slang-ir.h
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-options.cpp
Labels: pr: non-breaking

#3857 Improve compile time performance.
  source/compiler-core/slang-diagnostic-sink.cpp
  source/slang/hlsl.meta.slang
  source/slang/slang-artifact-output-util.cpp
  source/slang/slang-ast-support-types.h
  source/slang/slang-check-conversion.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-inheritance.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-autodiff-fwd.cpp
  source/slang/slang-ir-ssa-simplification.cpp
  source/slang/slang-options.cpp
  tests/bindings/multiple-parameter-blocks.slang
  tests/language-feature/extensions/extension-method-simple.slang
  tests/slang-extension/atomic-float-byte-address-buffer-cross.slang
Labels: pr: non-breaking

#4246 Fix small typo
  docs/user-guide/08-compiling.md
Labels: kind:documentation, pr: non-breaking

#4245 Fix confusion in Translation Units doc
  docs/user-guide/08-compiling.md
Labels: kind:documentation, pr: non-breaking

#4248 Update document regarding pointer
  docs/user-guide/03-convenience-features.md
  tests/spirv/pointer-from-user-guide.slang
Labels: kind:documentation, pr: non-breaking

#4247 Various issues in code snippets
  docs/user-guide/08-compiling.md
Labels: pr: non-breaking

#4228 Support SPIR-V DebugTypePointer
  source/slang/slang-emit-spirv-ops-debug-info-ext.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-util.cpp
  tests/spirv/debug-type-pointer.slang
Labels: pr: non-breaking
