Repository shader-slang/slang, pull requests merged in 2025-09, with the labels that each got.

#8345 Enable ccache for self-hosted runner
  .github/actions/common-setup/action.yml
  .github/workflows/ci.yml
  source/compiler-core/slang-nvrtc-compiler.cpp
Labels: pr: non-breaking

#8269 Fix#8085: Batch-9: Enable cuda tests
  tests/compute/byte-address-buffer-array.slang
  tests/compute/func-param-legalize.slang
  tests/compute/int-generic.slang
  tests/compute/interface-qualifiers/dyn-on-type-uses.slang
  tests/compute/nonuniformres-array-of-textures.slang
  tests/compute/nonuniformres-nested-rwstructuredbuf.slang
  tests/compute/switch-stmt.slang
Labels: pr: non-breaking

#8222 Diagnose on structured buffers containing resources
  source/slang/slang-ast-base.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-validate.cpp
  source/slang/slang-ir-validate.h
  source/slang/slang-ir.cpp
  source/slang/slang-ir.h
  tests/diagnostics/recursive-type.slang
  tests/diagnostics/structuredbuffer-resource-static.slang
  tests/diagnostics/structuredbuffer-resource-struct-array.slang
  tests/diagnostics/structuredbuffer-resource-struct-recursive-mutual.slang
  tests/diagnostics/structuredbuffer-resource-struct-recursive.slang
  tests/diagnostics/structuredbuffer-resource-struct.slang
  tests/diagnostics/structuredbuffer-resource.slang
Labels: pr: non-breaking

#8359 Split CI to build and test jobs
  .github/actions/common-setup/action.yml
  .github/actions/common-test-setup/action.yml
  .github/workflows/ci-slang-build.yml
  .github/workflows/ci-slang-test.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: pr: non-breaking

#8281 Add warnings for overflows of integer types
  source/slang/slang-parser.cpp
  tests/diagnostics/int-literal.slang
  tests/diagnostics/int-literal.slang.expected
  tests/slang-extension/atomic-int64-byte-address-buffer.slang
Labels: pr: non-breaking

#8386 Disable a few WGSL testing using Wave functions in branches
  tests/glsl-intrinsic/shader-subgroup/shader-subgroup-vote.slang
  tests/hlsl-intrinsic/wave-active-product.slang
  tests/hlsl-intrinsic/wave-active-product.slang.expected.txt
  tests/hlsl-intrinsic/wave-diverge.slang
  tests/hlsl-intrinsic/wave-is-first-lane.slang
  tests/hlsl-intrinsic/wave-is-first-lane.slang.expected.txt
Labels: pr: non-breaking

#8374 Remove unnecessary check and adust server count etc. in CI
  .github/actions/common-test-setup/action.yml
  .github/workflows/ci-slang-test.yml
  .github/workflows/ci.yml
  docs/building.md
Labels: pr: non-breaking

#8387 Relax restriction on using link-time types for shader parameters.
  docs/user-guide/a3-02-reference-capability-atoms.md
  source/slang/slang-check-decl.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-parameter-binding.cpp
  source/slang/slang-type-layout.cpp
  source/slang/slang-type-layout.h
  tests/diagnostics/incomplete-type.slang
  tools/slang-test/test-reporter.cpp
  tools/slang-unit-test/unit-test-link-time-type-reflection.cpp
Labels: pr: non-breaking

#8408 Fix #8314 - Enable tests/compute/texture-subscript.slang for CUDA
  tests/compute/texture-subscript.slang
Labels: pr: non-breaking

#8327 Enable slang_lldb.py on macos
  source/slang/slang_lldb.py
Labels: pr: non-breaking

#8413 Enable ccache in slang bulid for CTS test
  .github/workflows/vk-gl-cts-nightly.yml
Labels: pr: non-breaking

#8416 Fix language server auto-complete regression in debug build.
  source/slang/slang-check-expr.cpp
  tests/language-server/completion-in-initexpr.slang
Labels: pr: non-breaking

#8326 Check if debugVar for is debuggable types in the legalization pass
  source/slang/slang-ir-legalize-types.cpp
  tests/spirv/debug-var-generic-param.slang
Labels: pr: non-breaking

#8380 CUDA: Fix compiler crash with unsized array field - nonuniformres-as-…
  source/slang/slang-emit.cpp
  source/slang/slang-ir-collect-global-uniforms.cpp
  source/slang/slang-ir-collect-global-uniforms.h
  tests/compute/nonuniformres-as-function-parameter.slang
Labels: pr: non-breaking

#8425 Fix pointers and C-like layout in varying parameters
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-parameter-binding.cpp
  source/slang/slang-type-layout.cpp
  tests/spirv/c-layout-buffer-3.slang
Labels: pr: non-breaking

#8392 Fix crash when compiling specialized generic entrypoint containing a static const decl.
  source/slang/slang-linkable.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-target-program.cpp
  tools/slang-unit-test/unit-test-gh8184.cpp
Labels: pr: non-breaking

#8428 Fix segfault in SPIR-V header processing in SpirvInstructionHelper
  source/slang/slang-emit.cpp
Labels: pr: non-breaking

#8470 Use self-hosted runner for Windows release build
  .github/actions/common-setup/action.yml
  .github/workflows/release.yml
Labels: pr: non-breaking

#8473 include limits.h in slang-platform.cpp
  source/core/slang-platform.cpp
Labels: pr: non-breaking

#8495 Check if any required jobs failed (allow success or skipped)
  .github/workflows/ci.yml
Labels: pr: non-breaking

#8488 Revise SPIRV-Headers update instructions in documentation
  docs/update_spirv.md
Labels: pr: non-breaking

#8504 Fixed typo in `SemanticsVisitor::_readAggregateValueFromInitializerList`
  source/slang/slang-check-conversion.cpp
Labels: pr: non-breaking

#8502 Reduce the maxprocesses to 3 for slangpy test
  .github/workflows/ci-slang-test.yml
Labels: pr: non-breaking

#8448 Add RHI Device Caching and Test Prefix Exclusion
  tools/render-test/options.cpp
  tools/render-test/options.h
  tools/render-test/render-test-main.cpp
  tools/render-test/slang-test-device-cache.cpp
  tools/render-test/slang-test-device-cache.h
  tools/slang-test/options.cpp
  tools/slang-test/options.h
  tools/slang-test/slang-test-main.cpp
  tools/slang-test/test-context.cpp
  tools/slang-test/test-context.h
Labels: pr: non-breaking

#8492 Adding slang-test option to ignore abort popup message
  .github/workflows/ci-slang-test.yml
  tools/render-test/options.cpp
  tools/slang-test/options.cpp
  tools/slang-test/options.h
  tools/slang-test/slang-test-main.cpp
  tools/slang-test/test-context.cpp
  tools/test-server/test-server-main.cpp
Labels: pr: non-breaking

#8433 Remove unnecessary Load and Store pair
  source/slang/slang-ir-dce.h
  source/slang/slang-ir-redundancy-removal.cpp
  source/slang/slang-ir-transform-params-to-constref.cpp
  tests/metal/vector-get-element-ptr.slang
Labels: pr: non-breaking, CoPilot

#8381 Remove `cooperative-vector` tests from expected CI failures
  tests/expected-failure-github.txt
Labels: pr: non-breaking

#8487 Diagnostic on use of unsupported entry point modifiers
  source/slang/slang-check-shader.cpp
  source/slang/slang-diagnostic-defs.h
  tests/diagnostics/entry-point-mod-errors.slang
Labels: pr: non-breaking

#8534 Add SPV_NV_bindless_texture support
  docs/command-line-slangc-reference.md
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-metal.cpp
  source/slang/slang-emit-metal.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-insts-stable-names.lua
  source/slang/slang-ir-insts.lua
  source/slang/slang-ir.cpp
  tests/language-feature/descriptor-handle/desc-handle-nv-bindless-texture.slang
  tests/metal/atomic-texture-buffer.slang
Labels: pr: non-breaking

#8482 cmake: install config files into the correct directory for find_package()
  CMakeLists.txt
Labels: pr: non-breaking

#8446 Enable metal tests
  tests/hlsl-intrinsic/atomic/atomic-intrinsics-64bit.slang
  tests/hlsl-intrinsic/atomic/atomic-intrinsics.slang
  tests/metal/8bit-vector-types.slang
  tests/metal/atomic-byteaddressbuffer.slang
  tests/metal/atomic-intrinsics.slang
  tests/metal/atomic-texture-buffer.slang
  tests/metal/atomic-texture-texture1d.slang
  tests/metal/atomic-texture-texture1d.slang.2.expected.txt
  tests/metal/atomic-texture-texture1d.slang.3.expected.txt
  tests/metal/atomic-texture-texture2d.slang
  tests/metal/atomic-texture-texture2d.slang.2.expected.txt
  tests/metal/atomic-texture-texture2d.slang.3.expected.txt
  tests/metal/atomic-texture-texture3d.slang
  tests/metal/atomic-texture-texture3d.slang.2.expected.txt
  tests/metal/atomic-texture-texture3d.slang.3.expected.txt
  tests/metal/barrier.slang
  tests/metal/barycentrics.slang
  tests/metal/byte-address-buffer.slang
  tests/metal/byte-address-buffer.slang.2.expected.txt
  tests/metal/byte-address-buffer.slang.3.expected.txt
  tests/metal/depth-texture.slang
  tests/metal/discard.slang
  tests/metal/empty-struct-remove.slang
  tests/metal/explicit-location.slang
  tests/metal/groupshared.slang
  tests/metal/math.slang
  tests/metal/matrix-bool-lowering.slang
  tests/metal/matrix-integer-lowering.slang
  tests/metal/matrix-negate.slang
  tests/metal/metal-pointer-params.slang
  tests/metal/metal-pointer-uniform.slang
  tests/metal/multi-entry-point-params.slang
  tests/metal/nested-parameter-block-reflection.slang
  tests/metal/out-param.slang
  tests/metal/pointer-literals.slang
  tests/metal/simple-compute.slang
  tests/metal/simple-mesh.slang
  tests/metal/simple-task.slang
  tests/metal/stage-in-2.slang
  tests/metal/stage-in.slang
  tests/metal/sv_target-complex-1.slang
  tests/metal/sv_target-complex-2.slang
  tests/metal/sv_target.slang
  tests/metal/system-val-conversion.slang
  tests/metal/test_buffer.slang
  tests/metal/test_descriptor_handle.slang
  tests/metal/texture-multisample.slang
  tests/metal/texture-store-vector.slang
  tests/metal/texture-write.slang
  tests/metal/texture.slang
  tests/metal/thread_position_in_threadgroup.slang
  tests/metal/vector-argument-buffer-layout.slang
  tests/metal/vector-get-element-ptr.slang
  tests/pipeline/rasterization/mesh/dead-loop.slang
Labels: pr: non-breaking, DiscordRequest

#8567 Handle getEquivalentStructuredBuffer(castDynamicResource) in byte address legalization pass.
  source/slang/slang-ir-byte-address-legalize.cpp
  tests/language-feature/descriptor-handle/byte-address-buffer-handle.slang
Labels: pr: non-breaking
