Repository shader-slang/slang, pull requests merged in 2025-07, with the labels that each got.

#7555 Remove redundant [payload] attribute (Fix #7528)
  source/slang/core.meta.slang
  source/slang/slang-ast-modifier.h
  source/slang/slang-emit-hlsl.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-lower-to-ir.cpp
Labels: pr: non-breaking

#7561 Allow a compiler warning on MacOS
  cmake/CompilerFlags.cmake
Labels: pr: non-breaking

#7067 Allow Link time constant array length sizing, warn on unsupported functionality
  include/slang-deprecated.h
  include/slang.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-reflection-api.cpp
  tests/bugs/link-time-constant-array-size-lib.slang
  tests/bugs/link-time-constant-array-size-main.slang
  tests/library/ambiguous-extern-export-entry.slang.expected
  tools/gfx-unit-test/link-time-constant-array-size-lib.slang
  tools/gfx-unit-test/link-time-constant-array-size-main.slang
  tools/gfx-unit-test/link-time-constant-array-size.cpp
Labels: pr: non-breaking

#7569 Misc language server improvements.
  source/compiler-core/slang-json-value.cpp
  source/slang/slang-ast-decl-ref.cpp
  source/slang/slang-ast-print.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-content-assist-info.h
  source/slang/slang-language-server-auto-format.h
  source/slang/slang-language-server-completion.cpp
  source/slang/slang-language-server.cpp
  source/slang/slang-language-server.h
  tests/language-server/existential-decl-path.slang
  tests/language-server/override-completion-2.slang
  tests/language-server/smoke.slang.expected.txt
Labels: pr: non-breaking

#7579 Defer immutable buffer loads when emitting spirv.
  lock
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-spirv-ops.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-defer-buffer-load.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-specialize-function-call.cpp
  source/slang/slang-ir.cpp
  tests/diagnostics/parameter-block-to-mutating-func.slang
  tests/glsl-intrinsic/intrinsic-basic.slang
  tests/spirv/aligned-load-store.slang
  tests/spirv/fetch-array-from-parameter-block.slang
  tests/spirv/large-struct.slang
  tests/spirv/pointer-data-marshal.slang
  tests/spirv/ptr-unsized-array-2.slang
  tests/spirv/ref-this.slang
  tests/spirv/subgroup-size-2.slang
  tests/vkray/callable.slang
  tests/vkray/closesthit.slang
  tests/vkray/entry-point-params.slang
Labels: pr: non-breaking

#7568 Fix for emitting ArrayStride decoration for arrays of opaque types
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-util.cpp
  source/slang/slang-ir-util.h
  tests/language-feature/constants/unsized-opaque-array.slang
Labels: pr: non-breaking

#7532 Fix diagnostics not appearing when semantic tokens are disabled (#7477)
  source/slang/slang-language-server.cpp
  source/slang/slang.cpp
Labels: pr: non-breaking

#7587 Don't run full gpu tests on merge queue.
  .github/workflows/ci.yml
Labels: pr: non-breaking

#7372 add task shader alias
  docs/command-line-slangc-reference.md
  docs/user-guide/a3-02-reference-capability-atoms.md
  source/slang/slang-capabilities.capdef
  source/slang/slang-options.cpp
  source/slang/slang-profile-defs.h
Labels: pr: non-breaking

#7596 Run full check on merge_queue, but not on push.
  .github/copilot-instructions.md
  .github/workflows/ci.yml
Labels: pr: non-breaking

#7594 [HLSL, SPIRV_1_3] Hoist OpSelect returning a composite into `if`/`else`
  source/slang/slang-compiler.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-legalize-composite-select.cpp
  source/slang/slang-ir-legalize-composite-select.h
  source/slang/slang-ir-spirv-legalize.cpp
  tests/bugs/op-select-return-composite.slang
Labels: pr: non-breaking

#7600 Remove swiftshader from github action
  .github/actions/common-setup/action.yml
Labels: pr: non-breaking

#7608 Fix for mixed block/embedded usage of structs in SPIRV
  source/slang/slang-ir-spirv-legalize.cpp
  tests/bugs/gh-7431.slang
Labels: pr: non-breaking

#7604 Language Server Enhancements
  source/slang/slang-ast-iterator.h
  source/slang/slang-ast-print.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-overload.cpp
  source/slang/slang-compiler.h
  source/slang/slang-language-server-ast-lookup.cpp
  source/slang/slang-language-server.cpp
  source/slang/slang-language-server.h
  source/slang/slang-workspace-version.cpp
  source/slang/slang.cpp
  tests/language-server/ctor-hover.slang
  tests/language-server/ctor-signature.slang
  tests/language-server/smoke.slang.expected.txt
  tools/slang-test/slang-test-main.cpp
  tools/slangd/main.cpp
Labels: pr: non-breaking

#7626 Language server: sort completion candidate by relevance.
  source/slang/slang-language-server-ast-lookup.cpp
  source/slang/slang-language-server-ast-lookup.h
  source/slang/slang-language-server-completion.cpp
  source/slang/slang-language-server-completion.h
  tests/language-server/completion-sorting-1.slang
  tests/language-server/completion-sorting-2.slang
  tests/language-server/completion-sorting-3.slang
  tests/language-server/completion-sorting-4.slang
  tests/language-server/completion-sorting-5.slang
  tools/slang-test/slang-test-main.cpp
Labels: pr: non-breaking

#7619 Use fossil for IR serialization
  source/slang/slang-ir.h
  source/slang/slang-serialize-ast.cpp
  source/slang/slang-serialize-container.cpp
  source/slang/slang-serialize-container.h
  source/slang/slang-serialize-ir-types.h
  source/slang/slang-serialize-ir.cpp
  source/slang/slang-serialize-ir.h
  source/slang/slang-serialize-source-loc.h
  source/slang/slang-serialize-types.h
  source/slang/slang.cpp
Labels: pr: non-breaking

#7652 Fix a bug in examples/reflection-api
  examples/reflection-api/main.cpp
Labels: pr: non-breaking

#7638 Add <help-category> list and hint on usage in slangc -h
  docs/command-line-slangc-reference.md
  source/core/slang-command-options-writer.cpp
  source/slang/slang-options.cpp
Labels: pr: non-breaking

#7661 Fix typo for rgb10_a2 in image format table
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#7664 Avoid inserting underscore to _snorm format name if it has one already
  source/slang/slang-syntax.cpp
  tests/bindings/vk-image-format.slang
Labels: pr: non-breaking

#7655 no_diff diagnostics improvement
  source/slang/diff.meta.slang
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-ir-check-differentiability.cpp
  tests/autodiff/dynamic-dispatch-bwd-diff.slang
  tests/autodiff/dynamic-dispatch-generic-2.slang
  tests/autodiff/dynamic-object-bwd-diff.slang
  tests/autodiff/material2/DiffuseMaterial.slang
  tests/autodiff/material2/GlossyMaterial.slang
  tests/autodiff/material2/MxLayeredMaterial.slang
  tests/autodiff/member-func-extension-custom-derivative.slang
  tests/autodiff/nondiff-call.slang
  tests/diagnostics/const-to-nodiff-function-diagnostic-improvement.slang
  tests/diagnostics/const-to-nodiff-function-diagnostic-improvement1.slang
  tests/diagnostics/force-no-diff-this.slang
Labels: pr: non-breaking

#7653 Fix `slangc --help` text for `-reflection-json`
  docs/command-line-slangc-reference.md
  source/slang/slang-options.cpp
Labels: pr: non-breaking

#7659 Fix CommittedRayInstanceCustomIndex generating wrong SPIR-V opcode
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#7712 Only append slangc --help value categories if explicitly specified
  source/core/slang-command-options-writer.cpp
Labels: pr: non-breaking

#7710 Configure the surface with right format
  examples/example-base/example-base.cpp
Labels: pr: non-breaking

#7688 Fix metal segfault by check vectorValue before accessing
  source/slang/slang-ir-metal-legalize.cpp
  tests/metal/texture-store-vector.slang
Labels: pr: non-breaking, CoPilot

#7706 Enable (at least a sub-set of) CoopVec tests that are disabled
  tests/cooperative-vector/add.slang
  tests/cooperative-vector/array.slang
  tests/cooperative-vector/atan.slang
  tests/cooperative-vector/clamp.slang
  tests/cooperative-vector/comparison.slang
  tests/cooperative-vector/conversion.slang
  tests/cooperative-vector/copyFrom.slang
  tests/cooperative-vector/div.slang
  tests/cooperative-vector/exp.slang
  tests/cooperative-vector/fill.slang
  tests/cooperative-vector/fma.slang
  tests/cooperative-vector/inout.slang
  tests/cooperative-vector/load-store-arbitrary-array-vec.slang
  tests/cooperative-vector/load-store-arbitrary-array.slang
  tests/cooperative-vector/load-store-groupshared.slang
  tests/cooperative-vector/load-store-rwbyteaddressbuffer.slang
  tests/cooperative-vector/load-store-rwstructuredbuffer.slang
  tests/cooperative-vector/log.slang
  tests/cooperative-vector/matrix-mul-bias-mut.slang
  tests/cooperative-vector/matrix-mul-bias-packed-mut.slang
  tests/cooperative-vector/matrix-mul-bias-packed.slang
  tests/cooperative-vector/matrix-mul-bias-rw-packed.slang
  tests/cooperative-vector/matrix-mul-bias-rw.slang
  tests/cooperative-vector/matrix-mul-bias-rwbyteaddress-packed.slang
  tests/cooperative-vector/matrix-mul-bias-structuredbuffer-packed.slang
  tests/cooperative-vector/matrix-mul-bias.slang
  tests/cooperative-vector/matrix-mul-byteaddress.slang
  tests/cooperative-vector/matrix-mul-mut.slang
  tests/cooperative-vector/matrix-mul-packed-mut.slang
  tests/cooperative-vector/matrix-mul-packed.slang
  tests/cooperative-vector/matrix-mul-rw-packed.slang
  tests/cooperative-vector/matrix-mul-rw.slang
  tests/cooperative-vector/matrix-mul-rwbyteaddress-packed.slang
  tests/cooperative-vector/matrix-mul-structuredbuffer-packed.slang
  tests/cooperative-vector/matrix-mul.slang
  tests/cooperative-vector/max.slang
  tests/cooperative-vector/min.slang
  tests/cooperative-vector/mod.slang
  tests/cooperative-vector/mul.slang
  tests/cooperative-vector/neg.slang
  tests/cooperative-vector/out.slang
  tests/cooperative-vector/outer-product-structuredbuffer.slang
  tests/cooperative-vector/outer-product.slang
  tests/cooperative-vector/parameter.slang
  tests/cooperative-vector/reduce-sum-accumulate-structuredbuffer.slang
  tests/cooperative-vector/reduce-sum-accumulate.slang
  tests/cooperative-vector/return.slang
  tests/cooperative-vector/scalar-mul.slang
  tests/cooperative-vector/simple.slang
  tests/cooperative-vector/step.slang
  tests/cooperative-vector/struct.slang
  tests/cooperative-vector/sub.slang
  tests/cooperative-vector/subscript-in-func.slang
  tests/cooperative-vector/subscript.slang
  tests/cooperative-vector/tanh.slang
  tests/cooperative-vector/unary.slang
  tests/cooperative-vector/variadic-init-cast.slang
  tests/cooperative-vector/variadic-init.slang
  tests/expected-failure-via-glsl.txt
Labels: pr: non-breaking

#7731 Fixup address spaces after inlining.
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-inline.cpp
  source/slang/slang-ir-specialize-address-space.cpp
  source/slang/slang-ir-specialize-address-space.h
  tests/spirv/pointer-access.slang
Labels: pr: non-breaking

#7732 Update claude instructions to help with debugging.
  .github/workflows/claude.yml
  CLAUDE.md
Labels: pr: non-breaking

#7734 Add WorkgroupCount function
  source/slang/glsl.meta.slang
  source/slang/hlsl.meta.slang
  tests/pipeline/rasterization/mesh/task-simple.slang
Labels: pr: non-breaking

#7682 Let `flake.nix` users run `extras/formatting.sh`
  docs/building.md
  flake.lock
  flake.nix
Labels: pr: non-breaking

#7756 Fix language server crash.
  source/slang/slang-check-decl.cpp
  source/slang/slang-parser.cpp
  source/slang/slang-syntax.cpp
  tests/bugs/generic-type-arg-overloaded.slang
  tests/bugs/generic-type-arg-overloaded.slang.expected
  tests/language-server/robustness-9.slang
Labels: pr: non-breaking

#7683 Fix `slang-generate` segfault when parsing `$(()...)`
  source/slang/core.meta.slang
  tools/slang-generate/main.cpp
Labels: pr: non-breaking

#7663 Emit additional diagnostic for invalid pointer taking operations
  source/slang/core.meta.slang
  source/slang/slang-ast-support-types.cpp
  source/slang/slang-ast-support-types.h
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-overload.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-ir-fuse-satcoop.cpp
  tests/diagnostics/implicit-cast-lvalue.slang.expected
  tests/diagnostics/invalid-constant-pointer-taking.slang
  tests/diagnostics/methods/mutating-method-on-rvalue.slang.expected
  tests/diagnostics/setter-method.slang.expected
Labels: pr: non-breaking

#7740 Fix GLSL memory layout qualifiers not applied to uniform buffers or cbuffers
  source/slang/slang-parser.cpp
  tests/glsl/layout-scalar-qualifier.slang
Labels: pr: non-breaking, CoPilot

#7754 Document why failing VVL coop-vec tests cannot be enabled & minor cleanup/bug-fix
  source/slang/hlsl.meta.slang
  tests/cooperative-vector/atan.slang
  tests/cooperative-vector/clamp.slang
  tests/cooperative-vector/copyFrom.slang
  tests/cooperative-vector/div.slang
  tests/cooperative-vector/exp.slang
  tests/cooperative-vector/fill.slang
  tests/cooperative-vector/fma.slang
  tests/cooperative-vector/load-store-arbitrary-array-vec.slang
  tests/cooperative-vector/load-store-groupshared.slang
  tests/cooperative-vector/log.slang
  tests/cooperative-vector/matrix-mul-bias-mut.slang
  tests/cooperative-vector/matrix-mul-bias-packed-mut.slang
  tests/cooperative-vector/matrix-mul-bias-packed.slang
  tests/cooperative-vector/matrix-mul-bias-rw-packed.slang
  tests/cooperative-vector/matrix-mul-bias-rw.slang
  tests/cooperative-vector/matrix-mul-bias-rwbyteaddress-packed.slang
  tests/cooperative-vector/matrix-mul-bias-structuredbuffer-packed.slang
  tests/cooperative-vector/matrix-mul-bias.slang
  tests/cooperative-vector/matrix-mul-byteaddress.slang
  tests/cooperative-vector/matrix-mul-mut.slang
  tests/cooperative-vector/matrix-mul-packed-mut.slang
  tests/cooperative-vector/matrix-mul-packed.slang
  tests/cooperative-vector/matrix-mul-rw-packed.slang
  tests/cooperative-vector/matrix-mul-rw.slang
  tests/cooperative-vector/matrix-mul-rwbyteaddress-packed.slang
  tests/cooperative-vector/matrix-mul-structuredbuffer-packed.slang
  tests/cooperative-vector/matrix-mul.slang
  tests/cooperative-vector/max.slang
  tests/cooperative-vector/min.slang
  tests/cooperative-vector/mul.slang
  tests/cooperative-vector/outer-product-structuredbuffer.slang
  tests/cooperative-vector/outer-product.slang
  tests/cooperative-vector/reduce-sum-accumulate-structuredbuffer.slang
  tests/cooperative-vector/reduce-sum-accumulate.slang
  tests/cooperative-vector/scalar-mul.slang
  tests/cooperative-vector/simple.slang
  tests/cooperative-vector/step.slang
  tests/cooperative-vector/sub.slang
  tests/cooperative-vector/subscript.slang
  tests/cooperative-vector/tanh.slang
  tests/cooperative-vector/unary.slang
  tests/cooperative-vector/variadic-init-bad-length.slang
  tests/cooperative-vector/variadic-init-cast.slang
  tests/cooperative-vector/variadic-init.slang
  tests/expected-failure-github.txt
  tests/expected-failure-via-glsl.txt
Labels: pr: non-breaking

#7768 Correct help text for `-dump-intermediate-prefix`
  docs/command-line-slangc-reference.md
  source/slang/slang-options.cpp
Labels: pr: non-breaking

#7711 Diagnose on initExpr of a global `const` decl
  source/slang/slang-check-decl.cpp
  source/slang/slang-diagnostic-defs.h
  tests/diagnostics/global-const-uniform-with-init.slang
  tests/diagnostics/global-uniform.slang
  tests/diagnostics/global-uniform.slang.expected
Labels: pr: non-breaking, CoPilot

#7779 Strip debug info only for the SpvOpExtInst of debug import type
  source/slang/slang-emit.cpp
Labels: pr: non-breaking

#7800 bump and pin cmake formatter version
  .github/actions/format-setup/action.yml
  CMakeLists.txt
  extras/formatting.sh
Labels: pr: non-breaking

#7781 Document IR changes
  docs/design/ir-instruction-definition.md
  source/slang/slang-ir-insts.lua
Labels: pr: non-breaking

#7803 Further increase claude action limits.
  .github/workflows/claude.yml
Labels: pr: non-breaking

#7751 Perf improvements to IR serialization
  .gitignore
  prelude/slang-cpp-prelude.h
  source/core/slang-common.h
  source/core/slang-performance-profiler.cpp
  source/slang/slang-ir-insts-stable-names.lua
  source/slang/slang-ir-insts.lua
  source/slang/slang-ir.h
  source/slang/slang-ir.h.lua
  source/slang/slang-serialize-container.cpp
  source/slang/slang-serialize-fossil.cpp
  source/slang/slang-serialize-ir.cpp
  source/slang/slang-serialize-ir.h
  tests/ir/dump-module-info.slang
Labels: pr: non-breaking

#7764 Fix duplicate mangled names for interface requirements
  source/slang/slang-ir-util.cpp
  source/slang/slang-ir-util.h
  source/slang/slang-lower-to-ir.cpp
Labels: pr: non-breaking, CoPilot

#7798 Improve lookup performance.
  source/slang/slang-ast-decl.cpp
  source/slang/slang-ast-decl.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-inheritance.cpp
  source/slang/slang-check-modifier.cpp
  source/slang/slang-language-server.cpp
  source/slang/slang-language-server.h
  source/slang/slang-lookup.cpp
  source/slang/slang-parser.cpp
Labels: pr: non-breaking

#7792 Fix BitCast emitting bit shifts with too small integer types
  source/slang/slang-ir-extract-value-from-type.cpp
Labels: pr: non-breaking

#7812 Prelink ForceInlined functions during lowering.
  source/slang/slang-ast-decl.h
  source/slang/slang-ir-link.cpp
  source/slang/slang-ir-link.h
  source/slang/slang-lower-to-ir.cpp
Labels: pr: non-breaking

#7687 Lower int/uint/bool matrices to arrays for SPIRV
  source/slang/hlsl.meta.slang
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-legalize-binary-operator.cpp
  source/slang/slang-ir-legalize-matrix-types.cpp
  source/slang/slang-ir-legalize-matrix-types.h
  source/slang/slang-ir-util.cpp
  source/slang/slang-ir-validate.cpp
  tests/compute/integer-matrix-diagnostic.slang
  tests/spirv/matrix-bool-lowering.slang
  tests/spirv/matrix-integer-lowering.slang
Labels: client support, pr: non-breaking

#7818 Claude: increase tool timeout setting.
  .claude/settings.json
Labels: pr: non-breaking

#7831 Fix D3D12 test failure without Windows Developer mode
  tools/render-test/render-test-main.cpp
Labels: pr: non-breaking

#7835 Add command-line arguments to examples
  examples/example-base/example-base.cpp
  examples/example-base/example-base.h
  examples/example-base/test-base.cpp
  examples/example-base/test-base.h
  examples/model-viewer/main.cpp
  examples/platform-test/main.cpp
  examples/ray-tracing-pipeline/main.cpp
  examples/ray-tracing/main.cpp
  examples/shader-toy/main.cpp
  examples/triangle/main.cpp
Labels: pr: non-breaking

#7855 Fix Conditioanl<T, false> fields with a semantic.
  source/slang/slang-check-impl.h
  source/slang/slang-check-overload.cpp
  source/slang/slang-check-type.cpp
  source/slang/slang-parameter-binding.cpp
  tests/language-feature/types/conditional-varying.slang
  tests/spirv/spec-constant-generic.slang
  tools/slang-unit-test/unit-test-conditional-vertex-input.cpp
Labels: pr: non-breaking

#7821 Add CI to check ir module versioning
  .github/workflows/ci.yml
  .github/workflows/comment-ir-version-check.yml
  extras/check-inst-version-changes.sh
  source/slang/slang-ir.h
Labels: pr: non-breaking

#7858 Fix crash when private ctor is used for coercion.
  source/slang/slang-check-conversion.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-overload.cpp
  tests/autodiff/diff-assoctype-generic-interface.slang
  tests/diagnostics/private-visibility.slang
  tests/language-server/private-ctor-call/bsdfs.slang
  tests/language-server/private-ctor-call/lambert_diffuse_btdf.slang
  tests/language-server/private-ctor-call/test-main.slang
Labels: pr: non-breaking

#7837 Fix scalar to array conversion for tessellation factors
  source/slang/slang-ir-glsl-legalize.cpp
  tests/pipeline/tessellation/scalar-tessellation-factor.slang
Labels: pr: non-breaking, CoPilot

#7871 Fix passing a capability as a string into Slang crashes/is-invalid
  source/slang/slang-check-shader.cpp
  tests/language-feature/capability/capability-as-string.slang
Labels: pr: breaking change

#6901 Add slang-ast files to gitignore
  .gitignore
Labels: pr: non-breaking

#7882 Include Inst UID in some assert failure messages.
  source/slang/slang-emit-spirv.cpp
Labels: pr: non-breaking

#7850 Add test for Metal pointer uniform parameter
  tests/metal/metal-pointer-uniform.slang
Labels: pr: non-breaking

#7890 Organize code better by splitting some big files
  source/compiler-core/slang-diagnostic-sink.cpp
  source/compiler-core/slang-diagnostic-sink.h
  source/core/slang-type-convert-util.h
  source/core/slang-type-text-util.h
  source/slang/slang-base-type-info.cpp
  source/slang/slang-base-type-info.h
  source/slang/slang-check-impl.h
  source/slang/slang-code-gen.cpp
  source/slang/slang-code-gen.h
  source/slang/slang-compile-request.cpp
  source/slang/slang-compile-request.h
  source/slang/slang-compiler-api.cpp
  source/slang/slang-compiler-api.h
  source/slang/slang-compiler-fwd.h
  source/slang/slang-compiler.cpp
  source/slang/slang-compiler.h
  source/slang/slang-container-pool.cpp
  source/slang/slang-emit-dependency-file.cpp
  source/slang/slang-emit-dependency-file.h
  source/slang/slang-end-to-end-request.cpp
  source/slang/slang-end-to-end-request.h
  source/slang/slang-entry-point.cpp
  source/slang/slang-entry-point.h
  source/slang/slang-global-session.cpp
  source/slang/slang-global-session.h
  source/slang/slang-linkable-impls.cpp
  source/slang/slang-linkable-impls.h
  source/slang/slang-linkable.cpp
  source/slang/slang-linkable.h
  source/slang/slang-module.cpp
  source/slang/slang-module.h
  source/slang/slang-pass-through.cpp
  source/slang/slang-pass-through.h
  source/slang/slang-profile.cpp
  source/slang/slang-profile.h
  source/slang/slang-serialize-ast.cpp
  source/slang/slang-session.cpp
  source/slang/slang-session.h
  source/slang/slang-target-program.cpp
  source/slang/slang-target-program.h
  source/slang/slang-target.cpp
  source/slang/slang-target.h
  source/slang/slang-translation-unit.cpp
  source/slang/slang-translation-unit.h
  source/slang/slang.cpp
Labels: pr: non-breaking

#7636 Avoid early specialization for witness tables in SimplifyIR
  source/slang/slang-ir-remove-unused-generic-param.cpp
  tests/language-feature/interfaces/generic-value-parameter-via-interface.slang
Labels: pr: non-breaking

#7891 Fix for Generic Function Redefinition Error
  source/slang/slang-ir-util.cpp
  tests/language-feature/generics/generic-interface-linkage-2.slang
Labels: pr: non-breaking

#7904 Fix nv_viewport_mask semantic to emit SpvBuiltInViewportMaskNV
  source/slang/slang-emit-spirv.cpp
Labels: pr: non-breaking

#7868 Fix mesh shader reflection JSON output
  include/slang.h
  source/slang/slang-reflection-json.cpp
Labels: pr: non-breaking, CoPilot

#7937 Fix failing CoopVec tests
  tests/cooperative-vector/reduce-sum-accumulate-structuredbuffer.slang
  tests/cooperative-vector/reduce-sum-accumulate.slang
  tests/expected-failure-github.txt
Labels: pr: non-breaking

#7953 Improve multi-level branch elimination to handle continue blocks
  source/slang/slang-ir-eliminate-multilevel-break.cpp
  tests/bugs/gh-7748-switch-continue-bug.slang
Labels: pr: non-breaking

#7930 Improve diagnostics over ambiguous references.
  source/slang/hlsl.meta.slang
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-overload.cpp
  tests/diagnostics/ambiguous-member-base/lib.slang
  tests/diagnostics/ambiguous-member-base/user.slang
Labels: pr: non-breaking

#7962 Detect uses of uninitialized resource fields
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-detect-uninitialized-resources.cpp
  source/slang/slang-ir-detect-uninitialized-resources.h
  tests/diagnostics/uninitialized-resource-field.slang
Labels: pr: non-breaking

#7913 [Language Server]: Show signature help on generic parameters.
  source/slang/hlsl.meta.slang
  source/slang/slang-ast-expr.h
  source/slang/slang-ast-print.cpp
  source/slang/slang-ast-print.h
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-overload.cpp
  source/slang/slang-language-server-ast-lookup.cpp
  source/slang/slang-language-server.cpp
  source/slang/slang-parser.cpp
  tests/diagnostics/extension-visibility.slang
  tests/diagnostics/generic-type-inference-fail.slang
  tests/language-server/generic-signature-1.slang
  tests/language-server/generic-signature-2.slang
  tests/language-server/generic-signature-3.slang
  tests/language-server/generic-signature.slang
  tests/language-server/robustness-6.slang
  tests/language-server/tuple-completion.slang
  tools/gfx-unit-test/gfx-test-util.cpp
Labels: pr: non-breaking

#7843 Fix Metal invalid as_type cast for 64-bit RWByteAddressBuffer.Store values
  source/slang/slang-ir-byte-address-legalize.cpp
  tests/compute/byte-address-buffer-64bit.slang
  tests/compute/byte-address-buffer-64bit.slang.expected.txt
  tests/metal/byte-address-buffer.slang
Labels: pr: non-breaking

#7973 Fix ICE when immutable value is passed to a bwd_diff function.
  source/slang/slang-check-expr.cpp
  tests/diagnostics/implicit-cast-lvalue.slang.expected
  tests/diagnostics/lvalue-in-bwd-diff.slang
  tests/diagnostics/methods/mutating-method-on-rvalue.slang.expected
Labels: pr: non-breaking

#7972 Disable debug-layers temporarlily on CI
  .github/workflows/ci.yml
Labels: pr: non-breaking

#7983 Disable more CI workflows on master push.
  .github/workflows/benchmark.yml
  .github/workflows/check-cmdline-ref.yml
  .github/workflows/check-formatting.yml
  .github/workflows/check-toc.yml
  .github/workflows/falcor-compiler-perf-test.yml
  .github/workflows/falcor-test.yml
Labels: pr: non-breaking

#7995 [Language Server]: Don't eagerly check file upon open doc.
  source/slang/slang-language-server.cpp
Labels: pr: non-breaking

#7993 disallow `static const` variables without default-value
  source/slang/slang-check-decl.cpp
  source/slang/slang-diagnostic-defs.h
  tests/bugs/static-const-without-default-value.slang
Labels: pr: non-breaking, CoPilot

#7996 Reduce merge_group CI workload.
  .github/workflows/ci.yml
Labels: pr: non-breaking

#7963 msvc style bitfield packing
  docs/command-line-slangc-reference.md
  include/slang.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-options.cpp
  tests/language-feature/bitfield/msvc-mixed.slang
  tests/language-feature/bitfield/msvc-repr-mixed.slang
  tests/language-feature/bitfield/msvc-repr.slang
  tests/language-feature/bitfield/msvc-simple.slang
  tests/language-feature/bitfield/msvc-sizeof.slang
  tests/language-feature/bitfield/msvc-zero-width.slang
  tests/language-feature/bitfield/repr-mixed.slang
  tests/language-feature/bitfield/repr.slang
Labels: pr: non-breaking

#8005 Fix bug in lock-file slang-unit-test
  source/core/slang-io.cpp
  tools/slang-unit-test/unit-test-lock-file.cpp
Labels: pr: non-breaking

#7566 Add matrix select intrinsic
  source/slang/core.meta.slang
  source/slang/slang-ir-legalize-composite-select.cpp
  source/slang/slang-ir-legalize-matrix-types.cpp
  source/slang/slang-ir.cpp
  tests/hlsl-intrinsic/matrix-cast-to-vector.slang
  tests/language-feature/matrix-select.slang
Labels: client support, pr: non-breaking
