Repository shader-slang/slang, pull requests merged in 2025-05, with the labels that each got.

#6969 Smoke test WASM as a part of CI
  .github/workflows/ci.yml
  CMakePresets.json
  source/compiler-core/slang-json-value.cpp
  tests/wasm/smoke/rand_float.slang
  tests/wasm/smoke/smoke-test.js
Labels: pr: non-breaking

#6904 Modify markdown writing to produce readthedocs pages
  source/slang/slang-doc-markdown-writer.cpp
Labels: pr: non-breaking

#6975 Update falcor perf test path
  .github/workflows/falcor-compiler-perf-test.yml
Labels: pr: non-breaking

#6976 Fix comment typos in the triangle's main.cpp example
  examples/triangle/main.cpp
Labels: pr: non-breaking

#6983 Disable an always failing test, partial resident test with dx12
  tests/expected-failure-github.txt
  tests/hlsl-intrinsic/texture/partial-resident-texture-combined.slang
Labels: pr: non-breaking

#6971 Fix build on GCC 15
  source/core/slang-writer.cpp
  source/core/slang-writer.h
  source/slang-glslang/slang-glslang.h
Labels: pr: non-breaking

#6985 Fix seg-fault in cudaCodeGenBug test
  tools/slang-fiddle/slang-fiddle-scrape.cpp
  tools/slang-unit-test/unit-test-find-check-entrypoint.cpp
Labels: pr: non-breaking

#6973 Add IREnumType to distinguish enums from ints and each other
  source/slang/slang-emit.cpp
  source/slang/slang-ir-any-value-marshalling.cpp
  source/slang/slang-ir-autodiff-fwd.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-layout.cpp
  source/slang/slang-ir-lower-enum-type.cpp
  source/slang/slang-ir-lower-enum-type.h
  source/slang/slang-ir-util.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-ir.h
  source/slang/slang-lower-to-ir.cpp
  tests/bugs/gh-6964.slang
Labels: pr: non-breaking

#6994 Correct incorrect enum usage on metal
  tools/gfx/metal/metal-device.cpp
Labels: pr: non-breaking

#6897 Add countbits 16-bit and 8-bit support (#6433)
  prelude/slang-cpp-scalar-intrinsics.h
  prelude/slang-cuda-prelude.h
  source/slang/hlsl.meta.slang
  tests/hlsl-intrinsic/countbits.slang
  tests/hlsl-intrinsic/countbits16.slang
  tests/hlsl-intrinsic/countbits64.slang
  tests/hlsl-intrinsic/countbits8.slang
Labels: pr: non-breaking

#7003 Add a new capability hlsl_2018 that avoid using select/and/or
  source/slang/slang-capabilities.capdef
  source/slang/slang-emit-hlsl.cpp
  tests/compute/logic-no-short-circuit-evaluation.slang
Labels: pr: non-breaking

#7006 Fix the intermittent failures of tests/autodiff/auto-differential-type
  source/core/slang-stream.cpp
Labels: pr: non-breaking

#6997 Add interger pack/unpack intrinsic to glsl
  source/slang/glsl.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-ir-extract-value-from-type.cpp
  tests/glsl/interger_pack.slang
Labels: pr: non-breaking

#6989 Parse char literals as integers
  source/compiler-core/slang-lexer.cpp
  source/compiler-core/slang-lexer.h
  source/slang/slang-parser.cpp
  tests/front-end/char-literal.slang
Labels: pr: non-breaking

#6902 Output default parameter values on language server hover
  source/slang/slang-ast-print.cpp
  source/slang/slang-ast-print.h
  source/slang/slang-language-server.cpp
  tests/language-server/default-values.slang
  tests/language-server/default-values.slang.expected.txt
Labels: pr: non-breaking

#7018 bitcast require the input has same width with result type
  source/slang/slang-ir-extract-value-from-type.cpp
  tests/glsl/interger_pack.slang
  tests/language-feature/bit-cast/float-bit-cast.slang
Labels: pr: non-breaking

#7004 [CUDA] Fix surface write intrinsics
  prelude/slang-cuda-prelude.h
Labels: pr: non-breaking

#7042 Restore Properties section name in stdlib reference
  source/slang/slang-doc-markdown-writer.cpp
Labels: pr: non-breaking

#7009 Destroy unused witness table after hoisting
  source/slang/slang-ir-autodiff.cpp
Labels: pr: non-breaking

#6671 Fixed name mangling of generic extensions
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-mangle.cpp
  tests/language-feature/extensions/generic-extension-3.slang
  tests/language-feature/extensions/generic-extension-4.slang
Labels: pr: non-breaking

#6786 Fix various intptr_t issues by defining its width in `getIntTypeInfo`
  include/slang.h
  prelude/slang-cpp-host-prelude.h
  prelude/slang-cpp-prelude.h
  prelude/slang-cpp-types-core.h
  source/slang/slang-emit-cuda.cpp
  source/slang/slang-ir-any-value-marshalling.cpp
  source/slang/slang-ir.cpp
  tests/language-feature/types/intptr.slang
  tests/language-feature/types/intptr.slang.expected.txt
Labels: pr: non-breaking

#7044 Update build to allow setting more external paths
  CMakeLists.txt
  external/CMakeLists.txt
  tools/CMakeLists.txt
  tools/gfx/vulkan/glslang-module.h
  tools/gfx/vulkan/vk-shader-program.cpp
  tools/platform/gui.h
  tools/platform/model.cpp
  tools/platform/vector-math.h
Labels: pr: non-breaking

#7051 Fix SPIRV unsigned to signed widening casts
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-ir.h
  tests/spirv/int-cast-unsigned-to-signed.slang
Labels: pr: non-breaking

#6621 Add debug information for slang inling
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-spirv-ops-debug-info-ext.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-autodiff-fwd.cpp
  source/slang/slang-ir-autodiff-rev.cpp
  source/slang/slang-ir-autodiff.cpp
  source/slang/slang-ir-inline.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-inst-pass-base.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-strip-debug-info.cpp
  source/slang/slang-ir-validate.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-lower-to-ir.cpp
  tests/language-feature/function-calls/forceinline-basic-block-inline-order.slang
  tests/language-feature/function-calls/forceinline-basic-block.slang
  tests/language-feature/function-calls/forceinline-multiple-blocks.slang
  tests/language-feature/function-calls/forceinline-multiple-cases.slang
Labels: pr: non-breaking

#7053 Fix local constants in switch cases
  source/slang/slang-lower-to-ir.cpp
  tests/bugs/switch-local-const.slang
Labels: pr: non-breaking

#7054 Add a new option "-capability" to slang-test and render-test
  tools/render-test/options.cpp
  tools/render-test/options.h
  tools/render-test/slang-support.cpp
  tools/slang-test/options.cpp
  tools/slang-test/options.h
  tools/slang-test/slang-test-main.cpp
Labels: pr: non-breaking

#7012 cuda: Add more formats for texture read/write
  prelude/slang-cuda-prelude.h
  tests/compute/rw-texture-simple.slang
  tests/compute/rw-texture-simple.slang.expected.txt
  tests/compute/texture-subscript-cuda.slang
  tests/compute/texture-subscript-cuda.slang.expected.txt
  tests/compute/texture-subscript-uint-cuda.slang
Labels: pr: non-breaking

#7028 cluster acceleration structure optix 6431
  docs/user-guide/a3-02-reference-capability-atoms.md
  source/slang/glsl.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  source/slang/slang-emit-spirv.cpp
  tests/cuda/optix-cluster.slang
  tests/glsl-intrinsic/raytracing/glsl-rayAnyhit-cluster.slang
  tests/glsl-intrinsic/raytracing/ray-query-cluster-intrinsics.slang
  tests/hlsl-intrinsic/ray-tracing/ray-query-cluster-intrinsics.slang
  tests/hlsl-intrinsic/ray-tracing/ray-query-intrinsics.slang
  tests/hlsl-intrinsic/ray-tracing/rt-cluster-intrinsics-chit.slang
  tests/hlsl-intrinsic/shader-execution-reordering/hit-object-trace-ray.slang
Labels: pr: non-breaking

#7059 missing namespace std:: with nullptr_t (fails with clang)
  source/slang/slang-serialize-ast.cpp
  source/slang/slang-serialize.h
Labels: pr: non-breaking

#7046 Ensure to emit 32-bit type for bitfield operations for SPIRV
  source/slang/slang-ir-spirv-legalize.cpp
  tests/language-feature/bitfield/bitfield-insert-extract-non32bit.slang
Labels: pr: non-breaking

#7074 Make CUDA version capabilities reach NVRTC
  docs/user-guide/a3-02-reference-capability-atoms.md
  source/slang/slang-capabilities.capdef
  source/slang/slang-compiler.cpp
  tests/diagnostics/local-line.slang
  tools/gfx/cuda/cuda-device.cpp
Labels: pr: non-breaking

#7066 Add half-precision matrix type aliases in GLSL
  source/slang/glsl.meta.slang
  tests/glsl/float16_types.slang
Labels: pr: non-breaking

#6720 Support Array Sizes using Generic arguments to be initialized via {}
  source/slang/slang-ast-expr.h
  source/slang/slang-check-conversion.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-lower-to-ir.cpp
  tests/initializer-list/generic-array-init.slang
Labels: pr: non-breaking

#7080 Fix invalid memory dereference in lower-to-ir
  source/slang/slang-lower-to-ir.cpp
Labels: pr: non-breaking

#7076 Error out on invalid vector sizes
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-validate.cpp
  source/slang/slang-ir-validate.h
  tests/diagnostics/invalid-vector-element-count.slang
Labels: pr: non-breaking

#7048 Make Command Line Reference readthedocs compatible
  .github/workflows/check-cmdline-ref.yml
  .github/workflows/regenerate-cmdline-ref.yml
  .github/workflows/slash-command-dispatch.yml
  docs/command-line-slangc-reference.md
  source/core/slang-command-options-writer.cpp
  source/core/slang-command-options.cpp
  tools/slang-capability-generator/capability-generator-main.cpp
Labels: pr: non-breaking

#6871 support specialization constant sized array
  source/slang/slang-ast-builder.cpp
  source/slang/slang-ast-decl-ref.cpp
  source/slang/slang-ast-val.cpp
  source/slang/slang-ast-val.h
  source/slang/slang-check-constraint.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-type.cpp
  source/slang/slang-doc-markdown-writer.cpp
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-lower-buffer-element-type.cpp
  source/slang/slang-ir-util.cpp
  source/slang/slang-ir-util.h
  source/slang/slang-ir.cpp
  source/slang/slang-ir.h
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-mangle.cpp
  source/slang/slang-reflection-api.cpp
  source/slang/slang-type-layout.cpp
  source/slang/slang.cpp
  tests/spirv/spec-constant-sized-array-1.slang
  tests/spirv/spec-constant-sized-array-2.slang
  tests/spirv/spec-constant-sized-array-3.slang
  tests/spirv/spec-constant-sized-array-4.slang
Labels: pr: non-breaking

#7086 Stop escaping markdown between backticks
  source/slang/slang-doc-markdown-writer.cpp
Labels: pr: non-breaking

#7090 Infer type while constant folding causes failure
  source/slang/slang-check-decl.cpp
  tests/bugs/infer-var-type-constant-folding.slang
Labels: pr: non-breaking

#7068 Remove readonly keyword from buffer pointer definitions
  source/slang/slang-emit-glsl.cpp
  tests/hlsl-intrinsic/const-buffer-pointer.slang
Labels: pr: non-breaking

#7108 Support the new CoopVec builtins
  docs/command-line-slangc-reference.md
  docs/user-guide/a3-02-reference-capability-atoms.md
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-hlsl.cpp
  source/slang/slang.cpp
  tests/cooperative-vector/add.slang
  tests/cooperative-vector/atan.slang
  tests/cooperative-vector/clamp.slang
  tests/cooperative-vector/comparison.slang
  tests/cooperative-vector/conversion.slang
  tests/cooperative-vector/copyFrom.slang
  tests/cooperative-vector/div.slang
  tests/cooperative-vector/exp.slang
  tests/cooperative-vector/fill.slang
  tests/cooperative-vector/fma.slang
  tests/cooperative-vector/load-store-groupshared.slang
  tests/cooperative-vector/load-store-rwbyteaddressbuffer.slang
  tests/cooperative-vector/load-store-rwstructuredbuffer.slang
  tests/cooperative-vector/log.slang
  tests/cooperative-vector/matrix-mul-bias-mut.slang
  tests/cooperative-vector/matrix-mul-bias-packed-mut.slang
  tests/cooperative-vector/matrix-mul-bias-packed.slang
  tests/cooperative-vector/matrix-mul-bias-rw-packed.slang
  tests/cooperative-vector/matrix-mul-bias-rw.slang
  tests/cooperative-vector/matrix-mul-bias-rwbyteaddress-packed.slang
  tests/cooperative-vector/matrix-mul-bias-structuredbuffer-packed.slang
  tests/cooperative-vector/matrix-mul-bias.slang
  tests/cooperative-vector/matrix-mul-byteaddress.slang
  tests/cooperative-vector/matrix-mul-mut.slang
  tests/cooperative-vector/matrix-mul-packed-mut.slang
  tests/cooperative-vector/matrix-mul-packed.slang
  tests/cooperative-vector/matrix-mul-rw-packed.slang
  tests/cooperative-vector/matrix-mul-rw.slang
  tests/cooperative-vector/matrix-mul-rwbyteaddress-packed.slang
  tests/cooperative-vector/matrix-mul-structuredbuffer-packed.slang
  tests/cooperative-vector/matrix-mul.slang
  tests/cooperative-vector/max.slang
  tests/cooperative-vector/min.slang
  tests/cooperative-vector/mod.slang
  tests/cooperative-vector/mul.slang
  tests/cooperative-vector/outer-product-structuredbuffer.slang
  tests/cooperative-vector/outer-product.slang
  tests/cooperative-vector/reduce-sum-accumulate-structuredbuffer.slang
  tests/cooperative-vector/reduce-sum-accumulate.slang
  tests/cooperative-vector/scalar-mul.slang
  tests/cooperative-vector/simple.slang
  tests/cooperative-vector/step.slang
  tests/cooperative-vector/sub.slang
  tests/cooperative-vector/subscript.slang
  tests/cooperative-vector/tanh.slang
  tests/cooperative-vector/unary.slang
  tests/cooperative-vector/variadic-init-cast.slang
  tests/cooperative-vector/variadic-init.slang
Labels: pr: breaking change

#7027 Add new coopmat2 functions: Reduce and Transpose
  docs/command-line-slangc-reference.md
  docs/user-guide/a3-02-reference-capability-atoms.md
  source/slang/core.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  source/slang/slang-emit-spirv-ops.h
  tests/cooperative-matrix/add.slang
  tests/cooperative-matrix/array.slang
  tests/cooperative-matrix/comparison.slang
  tests/cooperative-matrix/conversion.slang
  tests/cooperative-matrix/copyFrom.slang
  tests/cooperative-matrix/diagnostics/mat-mul-add-different-scope.slang
  tests/cooperative-matrix/diagnostics/mat-mul-add-incorrect-matrix-use.slang
  tests/cooperative-matrix/div.slang
  tests/cooperative-matrix/fill.slang
  tests/cooperative-matrix/inout.slang
  tests/cooperative-matrix/length.slang
  tests/cooperative-matrix/load-store-arbitrary-array-vec.slang
  tests/cooperative-matrix/load-store-arbitrary-array.slang
  tests/cooperative-matrix/load-store-groupshared.slang
  tests/cooperative-matrix/load-store-rwbyteaddressbuffer.slang
  tests/cooperative-matrix/load-store-rwstructuredbuffer.slang
  tests/cooperative-matrix/map-element-single.slang
  tests/cooperative-matrix/mat-mul-add-spirv-matrix-operands.slang
  tests/cooperative-matrix/mat-mul-add.slang
  tests/cooperative-matrix/mod.slang
  tests/cooperative-matrix/mul.slang
  tests/cooperative-matrix/out.slang
  tests/cooperative-matrix/parameter.slang
  tests/cooperative-matrix/reduce.slang
  tests/cooperative-matrix/return.slang
  tests/cooperative-matrix/scalar-mul.slang
  tests/cooperative-matrix/struct.slang
  tests/cooperative-matrix/sub.slang
  tests/cooperative-matrix/subscript-in-func.slang
  tests/cooperative-matrix/subscript.slang
  tests/cooperative-matrix/transpose.slang
  tests/cooperative-matrix/unary_neg.slang
Labels: pr: non-breaking

#7084 Remove compiler option no longer needed from the example
  examples/hello-world/main.cpp
Labels: pr: non-breaking

#7082 Re-enable spirv-validation, because the issue is no longer repro
  tests/bugs/gh-3780.slang
  tests/spirv/mesh-primitive.slang
Labels: pr: non-breaking

#7060 Support tensor addressing
  docs/command-line-slangc-reference.md
  docs/user-guide/a3-02-reference-capability-atoms.md
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  source/slang/slang-emit-spirv-ops.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-ir.h
  tests/cooperative-matrix/load-store-tensorlayout.slang
  tests/cooperative-matrix/load-store-tensorview.slang
Labels: pr: non-breaking

#7105 Rename 'main' on some backends
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  tests/diagnostics/entry-point-main-warning.slang
Labels: pr: non-breaking

#7121 Implement spec const for generic parameter
  source/slang/slang-check-type.cpp
  source/slang/slang-ir-clone.cpp
  source/slang/slang-ir-specialize.cpp
  source/slang/slang-ir-util.cpp
  source/slang/slang-ir-util.h
  source/slang/slang-ir.cpp
  source/slang/slang-lower-to-ir.cpp
  tests/spirv/spec-constant-generic.slang
Labels: pr: non-breaking

#7087 Implement C++ style default member initializer
  source/slang/slang-check-decl.cpp
  tests/initializer-list/cpp-style-default-member-init.slang
Labels: pr: non-breaking

#7118 Add checking for hlsl register semantic.
  source/slang/slang-ast-type.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-type.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang.cpp
  tests/bindings/binding-spv-storage-class.slang
  tests/compute/nonuniformres-as-function-parameter.slang
  tests/diagnostics/invalid-buffer.slang
  tests/diagnostics/register-bindings.slang
  tests/diagnostics/register-bindings.slang.expected
  tests/hlsl/invalid-semantic.slang
Labels: pr: non-breaking

#7128 Fix slangc path used by cmdline reference doc regeneration action
  .github/workflows/check-cmdline-ref.yml
  .github/workflows/regenerate-cmdline-ref.yml
Labels: pr: non-breaking

#7091 Fix broken -emit-spirv-via-glsl test option
  docs/command-line-slangc-reference.md
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  source/slang/slang-emit-glsl.cpp
  tests/bugs/gh-4305.slang
  tests/cooperative-matrix/return.slang
  tests/cooperative-vector/atan.slang
  tests/cooperative-vector/clamp.slang
  tests/cooperative-vector/conversion.slang
  tests/cooperative-vector/exp.slang
  tests/cooperative-vector/fma.slang
  tests/cooperative-vector/log.slang
  tests/cooperative-vector/matrix-mul-bias-packed-mut.slang
  tests/cooperative-vector/matrix-mul-bias-packed.slang
  tests/cooperative-vector/max.slang
  tests/cooperative-vector/min.slang
  tests/cooperative-vector/scalar-mul.slang
  tests/cooperative-vector/step.slang
  tests/cooperative-vector/tanh.slang
  tests/glsl/integer_pack.slang
  tests/hlsl-intrinsic/countbits.slang
  tests/hlsl-intrinsic/countbits16.slang
  tests/hlsl-intrinsic/countbits64.slang
  tests/hlsl-intrinsic/countbits8.slang
  tests/hlsl-intrinsic/wave-rotate/wave-rotate-clustered.slang
  tests/hlsl-intrinsic/wave-rotate/wave-rotate.slang
  tests/language-feature/bit-cast/struct-bit-cast-2.slang
  tests/language-feature/bit-cast/struct-reinterpret.slang
  tests/language-feature/bitfield/bitfield-insert-extract-non32bit.slang
  tests/spirv/spec-constant-generic.slang
  tests/spirv/spec-constant-sized-array-1.slang
  tests/spirv/spec-constant-sized-array-2.slang
  tests/spirv/spec-constant-sized-array-3.slang
  tests/spirv/spec-constant-sized-array-4.slang
  tools/render-test/slang-support.cpp
Labels: pr: non-breaking

#7139 Fix RWStructuredBuffer emission
  source/slang/slang-emit-cpp.cpp
  tests/cuda/compile-to-cuda.slang
Labels: pr: non-breaking

#7129 Allow lambda exprs without captures to coerce to `functype`.
  source/slang/slang-ast-modifier.h
  source/slang/slang-ast-support-types.h
  source/slang/slang-ast-synthesis.cpp
  source/slang/slang-ast-synthesis.h
  source/slang/slang-check-conversion.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  tests/language-feature/lambda/coerce-failure.slang
  tests/language-feature/lambda/coerce-to-functype.slang
Labels: pr: non-breaking

#7117 Fix HLSL ByteAddressBuffer Load* parameter integer type
  source/slang/hlsl.meta.slang
  tests/compute/byte-address-buffer-align-error.slang
  tests/compute/byte-address-buffer-aligned.slang
  tests/compute/byte-address-buffer-array.slang
  tests/compute/byte-address-buffer.slang
  tests/metal/byte-address-buffer.slang
  tests/metal/system-val-conversion.slang
Labels: pr: breaking change

#7113 Enforce rule that `export`/`extern` (non cpp) must be `const`
  source/slang/slang-check-decl.cpp
  source/slang/slang-diagnostic-defs.h
  tests/language-feature/constants/link-time-vardecl-must-be-static-const-or-neither.slang
Labels: pr: breaking change

#7131 Fix correct bindings for bindless resource model [SPIRV and GLSL]
  docs/user-guide/03-convenience-features.md
  source/slang/hlsl.meta.slang
  source/slang/slang-ir-lower-dynamic-resource-heap.cpp
  tests/language-feature/descriptor-handle/desc-handle-2.slang
  tests/language-feature/descriptor-handle/desc-handle-default.slang
  tests/language-feature/descriptor-handle/desc-handle-vk-mutable-descriptor.slang
Labels: pr: breaking change

#7010 Address structured buffer `GetDimensions` issues for WGSL, GLSL and SPIRV
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-lower-buffer-element-type.cpp
  tests/cross-compile/get-dimensions-stride-struct.slang
  tests/cross-compile/get-dimensions-stride.slang
Labels: pr: non-breaking

#7085 Enable Windows full debug testsuite in CI
  .github/workflows/ci.yml
  examples/example-base/example-base.cpp
  examples/reflection-parameter-blocks/main.cpp
  include/slang-gfx.h
  tests/language-feature/defer/deferred-loop.slang
  tests/language-feature/defer/scoped.slang
  tools/gfx-unit-test/buffer-barrier-test.cpp
  tools/gfx-unit-test/existing-device-handle-test.cpp
  tools/gfx-unit-test/get-buffer-resource-handle-test.cpp
  tools/gfx-unit-test/get-cmd-buffer-handle-test.cpp
  tools/gfx-unit-test/get-cmd-queue-handle-test.cpp
  tools/gfx-unit-test/get-texture-resource-handle-test.cpp
  tools/gfx-unit-test/gfx-test-util.cpp
  tools/gfx/d3d12/d3d12-device.cpp
  tools/gfx/d3d12/d3d12-helper-functions.cpp
  tools/gfx/render.cpp
  tools/gfx/vulkan/vk-device.cpp
  tools/gfx/vulkan/vk-helper-functions.cpp
  tools/gfx/vulkan/vk-helper-functions.h
  tools/slang-test/options.cpp
  tools/slang-test/options.h
  tools/slang-test/slang-test-main.cpp
  tools/slang-test/test-context.h
  tools/slang-test/test-reporter.cpp
  tools/unit-test/slang-unit-test.h
Labels: pr: non-breaking

#6956 Fix: Preserve inout param modifications with OptiX IgnoreHit()
  source/slang/slang-emit.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-legalize-varying-params.cpp
  source/slang/slang-ir-undo-param-copy.cpp
  source/slang/slang-ir-undo-param-copy.h
  source/slang/slang-ir.cpp
  tests/cuda/optix-ignore-hit.slang
Labels: pr: non-breaking

#7057 Support Vulkan memory model
  docs/command-line-slangc-reference.md
  docs/user-guide/a2-01-spirv-target-specific.md
  docs/user-guide/a3-02-reference-capability-atoms.md
  docs/user-guide/toc.html
  source/slang/slang-capabilities.capdef
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-ir-spirv-legalize.h
  tests/cooperative-matrix/add.slang
  tests/cooperative-matrix/array.slang
  tests/cooperative-matrix/comparison.slang
  tests/cooperative-matrix/conversion.slang
  tests/cooperative-matrix/copyFrom.slang
  tests/cooperative-matrix/div.slang
  tests/cooperative-matrix/fill.slang
  tests/cooperative-matrix/inout.slang
  tests/cooperative-matrix/length.slang
  tests/cooperative-matrix/load-store-arbitrary-array-vec.slang
  tests/cooperative-matrix/load-store-arbitrary-array.slang
  tests/cooperative-matrix/load-store-groupshared.slang
  tests/cooperative-matrix/load-store-rwbyteaddressbuffer.slang
  tests/cooperative-matrix/load-store-rwstructuredbuffer.slang
  tests/cooperative-matrix/load-store-tensorlayout.slang
  tests/cooperative-matrix/load-store-tensorview.slang
  tests/cooperative-matrix/map-element-single.slang
  tests/cooperative-matrix/mat-mul-add-spirv-matrix-operands.slang
  tests/cooperative-matrix/mat-mul-add.slang
  tests/cooperative-matrix/mod.slang
  tests/cooperative-matrix/mul.slang
  tests/cooperative-matrix/out.slang
  tests/cooperative-matrix/parameter.slang
  tests/cooperative-matrix/reduce.slang
  tests/cooperative-matrix/return.slang
  tests/cooperative-matrix/scalar-mul.slang
  tests/cooperative-matrix/struct.slang
  tests/cooperative-matrix/sub.slang
  tests/cooperative-matrix/subscript-in-func.slang
  tests/cooperative-matrix/subscript.slang
  tests/cooperative-matrix/transpose.slang
  tests/cooperative-matrix/unary_neg.slang
  tests/diagnostics/extension-full-name.slang.actual
  tests/hlsl/simple/globallycoherent.hlsl
  tests/spirv/coherent-2.slang
  tests/spirv/coherent-texture.slang
  tests/spirv/coherent.slang
Labels: pr: non-breaking

#7148 Make example and unit test more robust
  examples/gpu-printing/gpu-printing.cpp
  tools/slang-unit-test/unit-test-compile-benchmark.cpp
Labels: pr: non-breaking

#7150 Map `SV_VertexID` to `gl_VertexIndex-gl_BaseVertex`, add `SV_Vulkan*ID` semantics
  docs/user-guide/a2-01-spirv-target-specific.md
  docs/user-guide/a2-02-metal-target-specific.md
  docs/user-guide/a2-03-wgsl-target-specific.md
  docs/user-guide/toc.html
  source/slang/glsl.meta.slang
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-glsl-legalize.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-legalize-varying-params.cpp
  source/slang/slang-ir-legalize-varying-params.h
  source/slang/slang-ir-spirv-legalize.cpp
  tests/spirv/pointer-2.slang
  tests/spirv/sv-vertex-id.slang
  tests/spirv/sv-vulkan-instance-vertex-id.slang
Labels: pr: breaking change

#7167 Update build to allow setting external lua path
  CMakeLists.txt
  tools/CMakeLists.txt
  tools/slang-fiddle/slang-fiddle-lua.cpp
Labels: pr: non-breaking, Dev Reviewed

#7161 [CUDA] Add template specializations for signed integer texture fetches
  prelude/slang-cuda-prelude.h
Labels: pr: non-breaking

#7175 Fix retry logic and skip high intermittent test failure
  .github/workflows/ci.yml
  tools/slang-test/slang-test-main.cpp
Labels: pr: non-breaking

#7126 Generalize serialization system used for AST
  docs/design/serialization.md
  source/core/slang-riff.h
  source/slang/slang-ast-base.h
  source/slang/slang-ast-decl.h
  source/slang/slang-ast-dump.cpp
  source/slang/slang-ast-support-types.h
  source/slang/slang-serialize-ast.cpp
  source/slang/slang-serialize-ast.h
  source/slang/slang-serialize-container.cpp
  source/slang/slang-serialize-riff.cpp
  source/slang/slang-serialize-riff.h
  source/slang/slang-serialize.h
  tools/slang-fiddle/slang-fiddle-scrape.cpp
Labels: pr: non-breaking

#7173 Add inverse hyperbolic derivatives
  source/slang/diff.meta.slang
  source/slang/hlsl.meta.slang
  tests/autodiff-dstdlib/dstdlib-inverse-hyperbolic.slang
Labels: pr: non-breaking

#7198 Fix incorrect way of type checking inside of CoopVec Multiply
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#7172 Initial `dyn` keyword support & `-std <std-revision>` compiler option
  docs/command-line-slangc-reference.md
  docs/user-guide/a3-02-reference-capability-atoms.md
  include/slang.h
  source/core/slang-type-text-util.cpp
  source/core/slang-type-text-util.h
  source/slang/slang-ast-modifier.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-modifier.cpp
  source/slang/slang-compiler-options.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-options.cpp
  source/slang/slang-parser.cpp
  tests/compute/dynamic-dispatch-bindless-texture.slang
  tests/compute/interface-qualifiers/dyn-on-type-uses.slang
  tests/compute/interface-qualifiers/some-and-dyn-vardecl-uses.slang
Labels: pr: breaking change

#7213 Make sizeof(T) & alignof(T) of generic types work as compile-time constants
  source/slang/slang-ast-val.cpp
  source/slang/slang-ast-val.h
  source/slang/slang-check-expr.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-mangle.cpp
  tests/hlsl-intrinsic/size-of/size-of-compile-time.slang
Labels: pr: non-breaking

#7168 Amend documentation for how bindless with Vulkan works for clarity #7165
  docs/user-guide/03-convenience-features.md
Labels: pr: non-breaking

#7079 Implement default initializer list for C-Style type member
  source/slang/slang-check-conversion.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-ir-autodiff-transpose.h
  tests/diagnostics/extension-full-name.slang.expected
  tests/diagnostics/mismatching-types.slang.expected
  tests/initializer-list/c-style-type.slang
  tests/initializer-list/default-init-c-style-member.slang
  tests/initializer-list/generic-array-init.slang
  tests/initializer-list/partial-init.slang
  tests/initializer-list/struct-visibility-diagnostic-1.slang
  tests/initializer-list/struct-visibility-diagnostic-2.slang
  tests/initializer-list/struct-visibility-diagnostic-3.slang
Labels: pr: non-breaking

#7214 Add default constructor for Ptr type
  source/slang/slang-check-conversion.cpp
  tests/spirv/pointer-default-constructor.slang
Labels: pr: non-breaking

#6822 Add CoopVec load/store pointer overloads
  source/slang/hlsl.meta.slang
  source/slang/slang-emit-spirv.cpp
  tests/cooperative-vector/load-store-pointer.slang
Labels: pr: non-breaking

#6916 Implement throw & catch statements
  docs/user-guide/03-convenience-features.md
  docs/user-guide/toc.html
  source/slang/slang-ast-iterator.h
  source/slang/slang-ast-stmt.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-stmt.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-lower-error-handling.cpp
  source/slang/slang-ir-lower-result-type.cpp
  source/slang/slang-ir-marshal-native-call.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-language-server-ast-lookup.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-parser.cpp
  tests/language-feature/error-handling/basic.slang
  tests/language-feature/error-handling/catch-all.slang
  tests/language-feature/error-handling/defer-interaction.slang
  tests/language-feature/error-handling/generics.slang
  tests/language-feature/error-handling/non-trivial-error-type.slang
  tests/language-feature/error-handling/throw-in-defer.slang
  tests/language-feature/error-handling/throw-type-mismatch.slang
  tests/language-feature/error-handling/throw-without-throws.slang
  tests/language-feature/error-handling/try-in-defer.slang
Labels: pr: new feature, pr: non-breaking

#7203 List all source files in debug source file list
  source/slang/slang-ir-link.cpp
Labels: pr: non-breaking

#7103 Add full support for SPV_NV_shader_subgroup_partitioned
  docs/command-line-slangc-reference.md
  docs/user-guide/a3-02-reference-capability-atoms.md
  docs/wave-intrinsics.md
  source/slang/glsl.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  tests/hlsl-intrinsic/wave-mask/wave-active-product.slang
  tests/hlsl-intrinsic/wave-mask/wave-diverge.slang
  tests/hlsl-intrinsic/wave-mask/wave-matrix.slang
  tests/hlsl-intrinsic/wave-mask/wave-prefix-product.slang
  tests/hlsl-intrinsic/wave-mask/wave-prefix-sum.slang
  tests/hlsl-intrinsic/wave-mask/wave-vector.slang
  tests/hlsl-intrinsic/wave-multi/wave-multi-bitwise.slang
  tests/hlsl-intrinsic/wave-multi/wave-multi-min-max.slang
  tests/hlsl-intrinsic/wave-multi/wave-multi-prefix-bitwise.slang
  tests/hlsl-intrinsic/wave-multi/wave-multi-prefix-max.slang
  tests/hlsl-intrinsic/wave-multi/wave-multi-prefix-min.slang
  tests/hlsl-intrinsic/wave-multi/wave-multi-prefix-scalar-functional.slang
  tests/hlsl-intrinsic/wave-multi/wave-multi-prefix-scalar-functional.slang.expected.txt
  tests/hlsl-intrinsic/wave-multi/wave-multi-prefix-sum-product.slang
  tests/hlsl-intrinsic/wave-multi/wave-multi-prefix.slang
  tests/hlsl-intrinsic/wave-multi/wave-multi-sum-product.slang
  tests/language-feature/capability/testing-framework-with-profiles.slang
Labels: pr: breaking change

#7236 Fix issues with properties from interfaces
  source/slang/slang-check-expr.cpp
  source/slang/slang-parser.cpp
  tests/bugs/gh-7232.slang
Labels: pr: non-breaking

#7240 Fix nullptr_t compiling failure
  source/core/slang-riff.h
Labels: pr: non-breaking

#7218 Enable slang-rhi integration testing
  .github/workflows/ci.yml
Labels: pr: non-breaking, Dev Opened

#7224 Change default descriptor binding to be VkMutable
  docs/user-guide/03-convenience-features.md
  source/slang/hlsl.meta.slang
  tests/language-feature/descriptor-handle/desc-handle-default.slang
  tests/language-feature/descriptor-handle/desc-handle-vk-mutable-descriptor.slang
Labels: pr: breaking change

#7268 fix doc's website table & grammer
  docs/user-guide/03-convenience-features.md
Labels: pr: non-breaking

#7230 Language version + tuple syntax.
  docs/command-line-slangc-reference.md
  docs/user-guide/11-language-version.md
  docs/user-guide/a3-02-reference-capability-atoms.md
  docs/user-guide/toc.html
  include/slang.h
  source/core/slang-type-text-util.cpp
  source/core/slang-type-text-util.h
  source/slang-record-replay/record/parameter-recorder.cpp
  source/slang-record-replay/replay/json-consumer.cpp
  source/slang-record-replay/replay/parameter-decoder.cpp
  source/slang/slang-ast-decl.h
  source/slang/slang-ast-expr.h
  source/slang/slang-ast-iterator.h
  source/slang/slang-capabilities.capdef
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-compiler-options.cpp
  source/slang/slang-compiler-options.h
  source/slang/slang-compiler.cpp
  source/slang/slang-compiler.h
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-language-server-ast-lookup.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-options.cpp
  source/slang/slang-parser.cpp
  source/slang/slang-preprocessor.cpp
  source/slang/slang-preprocessor.h
  source/slang/slang-serialize-ast.cpp
  source/slang/slang-type-layout.cpp
  source/slang/slang.cpp
  tests/language-feature/lang-version.slang
  tests/language-feature/tuple/tuple-syntax.slang
Labels: pr: non-breaking

#7276 Remove a workaround disabling dxc-fetch
  external/CMakeLists.txt
Labels: pr: non-breaking

#7158 Fix SPIRV `OpSpecConstantOp` emit
  source/slang/slang-check-expr.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-clone.cpp
  source/slang/slang-ir-util.cpp
  source/slang/slang-ir-util.h
  source/slang/slang-ir.cpp
  tests/spirv/spec-constant-int-val-float-to-int-cast.slang
  tests/spirv/spec-constant-operations.slang
Labels: pr: non-breaking

#7273 Enable LSS hit object test
  prelude/slang-cuda-prelude.h
  source/slang/hlsl.meta.slang
  tests/cuda/lss-test.slang
Labels: pr: non-breaking

#7222 Add a memory-mappable binary serialization format
  docs/design/serialization.md
  source/core/slang-blob-builder.cpp
  source/core/slang-blob-builder.h
  source/core/slang-internally-linked-list.cpp
  source/core/slang-internally-linked-list.h
  source/core/slang-memory-arena.h
  source/core/slang-relative-ptr.cpp
  source/core/slang-relative-ptr.h
  source/core/slang-riff.h
  source/slang/slang-fossil.cpp
  source/slang/slang-fossil.h
  source/slang/slang-serialize-ast.cpp
  source/slang/slang-serialize-fossil.cpp
  source/slang/slang-serialize-fossil.h
  source/slang/slang-serialize-riff.cpp
  source/slang/slang-serialize-riff.h
  source/slang/slang-serialize.h
Labels: pr: non-breaking

#7283 Ensure we do not have an `initExpr` on a `VarDecl` inside an `InterfaceDecl`
  source/slang/slang-check-decl.cpp
  tests/bugs/static-const-init-expr-with-interface-1.slang
  tests/bugs/static-const-init-expr-with-interface-2.slang
Labels: pr: non-breaking

#6677 Add check for the variable requirement
  source/slang/hlsl.meta.slang
  source/slang/slang-ast-builder.cpp
  source/slang/slang-ast-builder.h
  source/slang/slang-ast-type.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-parser.cpp
  source/slang/slang-type-layout.cpp
  tests/bugs/gh-3429.slang
  tests/language-feature/capability/var-capability-incompatible.slang
  tests/language-feature/capability/var-capability-wgsl-2.slang
  tests/language-feature/capability/var-capability-wgsl.slang
  tests/language-feature/capability/var-implicit-capability-wgsl.slang
Labels: pr: breaking change
