Repository shader-slang/slang, pull requests merged in 2025-06, with the labels that each got.

#7279 Fix test-server debug issues with gfx-unit-test-tool (#7119)
  tools/slang-test/slang-test-main.cpp
  tools/test-server/test-server-main.cpp
Labels: pr: non-breaking

#7227 Use MatrixResultSignedComponents on OpCooperativeVectorMatrixMulNV
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#7291 Fix compile error in debug build
  source/slang/slang-serialize-fossil.cpp
Labels: pr: non-breaking

#7300 Add a new slang-test option `-enable-debug-layers`
  .github/workflows/ci.yml
  source/compiler-core/slang-test-server-protocol.h
  tools/render-test/render-test-main.cpp
  tools/slang-test/options.cpp
  tools/slang-test/options.h
  tools/slang-test/slang-test-main.cpp
  tools/slang-test/test-context.h
  tools/test-server/test-server-main.cpp
Labels: pr: non-breaking

#7317 Disable 23 tests that fail assertions
  .github/workflows/ci.yml
  tests/bugs/import-with-error.slang
  tests/diagnostics/missing-return-target.slang
  tests/diagnostics/recursive-import.slang
  tests/diagnostics/unbound-loop.slang
  tests/diagnostics/uninitialized-resource-type.slang
  tests/glsl-intrinsic/shader-subgroup/shader-subgroup-arithmetic_Exclusive.slang
  tests/glsl-intrinsic/shader-subgroup/shader-subgroup-arithmetic_Inclusive.slang
  tests/glsl-intrinsic/shader-subgroup/shader-subgroup-arithmetic_None.slang
  tests/ir/dump-module.slang
  tests/language-feature/modules/error-in-nested-import/error-in-nested-import.slang
  tests/language-server/robustness-2.slang
  tests/language-server/robustness-3.slang
  tests/language-server/robustness-4.slang
  tests/language-server/robustness-5.slang
  tests/language-server/robustness-6.slang
  tests/language-server/robustness-7.slang
  tests/language-server/robustness-8.slang
  tests/language-server/scalar-member.slang
  tests/language-server/smoke.slang
  tests/language-server/this-type-hover.slang
  tests/language-server/typename-enum-intval.slang
  tests/language-server/vector-member.slang
  tests/spirv/empty-module.slang
Labels: pr: non-breaking

#7339 Fix rpc errors on slang-unit-tests
  source/compiler-core/slang-test-server-protocol.cpp
Labels: pr: non-breaking

#7260 Make interface types non c-style in Slang2026.
  docs/command-line-slangc-reference.md
  include/slang.h
  source/core/slang-string-escape-util.cpp
  source/core/slang-string-escape-util.h
  source/slang-record-replay/record/slang-session.cpp
  source/slang-record-replay/record/slang-session.h
  source/slang-record-replay/util/record-format.h
  source/slang/core.meta.slang
  source/slang/diff.meta.slang
  source/slang/slang-ast-natural-layout.cpp
  source/slang/slang-check-conversion.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-shader.cpp
  source/slang/slang-compiler-options.cpp
  source/slang/slang-compiler.h
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-autodiff-fwd.cpp
  source/slang/slang-ir-autodiff-fwd.h
  source/slang/slang-ir-autodiff-transcriber-base.cpp
  source/slang/slang-ir-autodiff-transpose.h
  source/slang/slang-ir-autodiff.cpp
  source/slang/slang-ir-autodiff.h
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-lower-existential.cpp
  source/slang/slang-ir-lower-optional-type.cpp
  source/slang/slang-ir-marshal-native-call.cpp
  source/slang/slang-ir-peephole.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-options.cpp
  source/slang/slang-parser.cpp
  source/slang/slang-type-layout.cpp
  source/slang/slang.cpp
  tests/autodiff/optional.slang
  tests/initializer-list/existential-is-not-c-like.slang
  tests/language-feature/interfaces/optional-none.slang
  tests/language-feature/interfaces/zero-init-interface.slang
  tests/language-feature/nested-optional.slang
Labels: pr: non-breaking

#7281 Fix missing debug info for the included slang file
  source/compiler-core/slang-source-loc.h
  source/slang/slang-compiler.h
  source/slang/slang.cpp
Labels: pr: non-breaking

#7344 Implement isnan and isinf for WGSL with bitwise operations
  source/slang/hlsl.meta.slang
  tests/expected-failure-github.txt
Labels: pr: non-breaking

#7346 Check the supported backends in CI
  .github/workflows/ci.yml
  tests/render/check-backend-support-on-ci.slang
Labels: pr: non-breaking

#7356 Fix somme mis-define of capability
  source/slang/slang-capabilities.capdef
Labels: pr: non-breaking

#7358 Clean up a dead code forgot to delete
  tools/slang-unit-test/unit-test-record-replay.cpp
Labels: pr: non-breaking

#7345 Disable Link-Time-Optimization by default
  .github/workflows/release.yml
  CMakeLists.txt
  docs/building.md
  source/core/slang-blob.h
  source/core/slang-file-system.h
  source/core/slang-memory-file-system.h
  source/core/slang-shared-library.h
  source/core/slang-zip-file-system.cpp
  source/slang-llvm/slang-llvm.cpp
  source/slang/slang-emit-vm.cpp
  source/slang/slang-serialize-ast.cpp
  source/slang/slang-serialize.h
  source/slang/slang-vm-bytecode.cpp
  source/slang/slang-workspace-version.h
Labels: pr: non-breaking

#7178 Add command line option for separate debug info
  docs/command-line-slangc-reference.md
  include/slang.h
  source/compiler-core/slang-artifact-associated-impl.cpp
  source/compiler-core/slang-artifact-associated-impl.h
  source/compiler-core/slang-artifact-associated.h
  source/compiler-core/slang-artifact-impl.cpp
  source/compiler-core/slang-artifact-impl.h
  source/compiler-core/slang-artifact.h
  source/compiler-core/slang-spirv-core-grammar.h
  source/slang-record-replay/record/slang-component-type.cpp
  source/slang-record-replay/record/slang-component-type.h
  source/slang-record-replay/record/slang-entrypoint.h
  source/slang-record-replay/record/slang-module.h
  source/slang-record-replay/record/slang-type-conformance.h
  source/slang/slang-compiler-options.h
  source/slang/slang-compiler.cpp
  source/slang/slang-compiler.h
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-spirv-ops-debug-info-ext.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-link.cpp
  source/slang/slang-ir-strip-debug-info.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-options.cpp
  source/slang/slang.cpp
  tests/spirv/separate-debug.slang
  tools/slang-unit-test/unit-test-separate-debug.cpp
Labels: pr: non-breaking, Dev Opened

#7242 Mediate access to ContainerDecl members
  source/slang/slang-ast-base.h
  source/slang/slang-ast-decl-ref.cpp
  source/slang/slang-ast-decl.cpp
  source/slang/slang-ast-decl.h
  source/slang/slang-ast-dump.cpp
  source/slang/slang-ast-iterator.h
  source/slang/slang-ast-support-types.h
  source/slang/slang-ast-synthesis.h
  source/slang/slang-ast-type.cpp
  source/slang/slang-ast-val.cpp
  source/slang/slang-check-constraint.cpp
  source/slang/slang-check-conversion.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-modifier.cpp
  source/slang/slang-check-overload.cpp
  source/slang/slang-check-shader.cpp
  source/slang/slang-check-stmt.cpp
  source/slang/slang-check-type.cpp
  source/slang/slang-compiler.cpp
  source/slang/slang-doc-ast.cpp
  source/slang/slang-doc-markdown-writer.cpp
  source/slang/slang-language-server-ast-lookup.cpp
  source/slang/slang-language-server-document-symbols.cpp
  source/slang/slang-language-server.cpp
  source/slang/slang-lookup.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-parser.cpp
  source/slang/slang-reflection-api.cpp
  source/slang/slang-serialize-ast.cpp
  source/slang/slang-syntax.cpp
  source/slang/slang-syntax.h
  source/slang/slang-type-layout.cpp
  source/slang/slang.cpp
Labels: pr: non-breaking

#7363 Add release workflow targeting glibc2.27 with ubuntu 18
  .github/workflows/release-linux-glibc-2-27.yml
Labels: pr: non-breaking

#7286 Add optix support for coopvec
  docs/command-line-slangc-reference.md
  docs/user-guide/a3-02-reference-capability-atoms.md
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-cpp.cpp
  tests/cooperative-vector/exp2.slang
  tests/cooperative-vector/log2.slang
  tests/cuda/optix-coopvec.slang
Labels: pr: non-breaking

#6943 Legalise out parameters for vertex shaders on metal
  source/core/slang-list.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-legalize-varying-params.cpp
  source/slang/slang-ir-lower-out-parameters.cpp
  source/slang/slang-ir-lower-out-parameters.h
  source/slang/slang-ir-util.h
  source/slang/slang-ir.cpp
  tests/metal/simple-vertex-position-implicit-semantic.slang
  tests/metal/simple-vertex-position-out-struct.slang
  tests/metal/simple-vertex-position-return-struct.slang
  tests/metal/simple-vertex-position-return-value-and-out.slang
  tests/metal/simple-vertex-position-return-value.slang
  tests/metal/simple-vertex-position.slang
  tests/metal/stage-in.slang
Labels: pr: non-breaking

#7384 remove unnecessary use of std::bit_cast
  source/slang/slang-ir.h
Labels: pr: non-breaking

#7282 Fix IR layout of 3-element vectors in cbuffers for -fvk-use-dx-layout
  docs/user-guide/a2-04-glsl-target-specific.md
  docs/user-guide/a2-target-specific-features.md
  docs/user-guide/toc.html
  source/slang/slang-ir-layout.cpp
  source/slang/slang-ir-layout.h
  tests/expected-failure.txt
  tests/hlsl/cbuffer-float3-offsets-aligned.slang
  tests/hlsl/cbuffer-float3-offsets-unaligned.slang
Labels: pr: non-breaking

#7392 Include CPU test on Windows CI
  .github/workflows/ci.yml
Labels: pr: non-breaking

#7402 Fix an issue in extension override.
  source/slang/hlsl.meta.slang
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-inheritance.cpp
  source/slang/slang-check-overload.cpp
  tests/language-feature/extensions/extension-override-2.slang
Labels: pr: non-breaking

#7368 Add DebugLine before IfElse
  source/slang/slang-lower-to-ir.cpp
Labels: pr: non-breaking

#7418 Fix incorrect CMAKE define `SLANG_ENABLE_IR_BREAK_ALLOC,`
  CMakeLists.txt
Labels: pr: non-breaking

#7419 Diagnose on use of struct inheritance.
  source/slang/slang-check-decl.cpp
  source/slang/slang-diagnostic-defs.h
  tests/diagnostics/inheritance-1.slang
  tests/diagnostics/inheritance-2.slang
  tests/hlsl-intrinsic/size-of/align-of.slang
  tests/hlsl-intrinsic/size-of/size-of.slang
  tests/initializer-list/struct-inherit.slang
  tests/language-feature/inheritance/derived-struct-init-list.slang
  tests/language-feature/inheritance/struct-inherit-interface-requirement.slang
  tests/language-feature/inheritance/struct-inheritance-imported.slang
  tests/language-feature/inheritance/struct-inheritance.slang
  tests/language-feature/initializer-lists/inheritance-generic.slang
  tests/language-feature/struct-field-initializers/struct-field-initializer-extension-inheritance.slang
  tests/language-feature/struct-field-initializers/struct-field-initializer-inherited-chain.slang
  tests/language-feature/struct-field-initializers/struct-field-initializer-init-inheritance-write-to-same.slang
  tests/language-feature/struct-field-initializers/struct-field-initializer-static.slang
Labels: pr: non-breaking

#7382 Improve exported build targets
  cmake/SlangTarget.cmake
Labels: pr: non-breaking

#7433 Fix issue of missing scope for 'Differential' type
  source/slang/slang-check-expr.cpp
  tests/bugs/gh-6756.slang
Labels: pr: non-breaking

#7434 Fix issue that struct with member is not its Differential type
  source/slang/slang-check-expr.cpp
  tests/autodiff/differential-type-syntheize-diagnostics.slang
Labels: pr: non-breaking

#7444 Fix a bug in empty array legalization.
  source/slang/slang-ir-legalize-empty-array.cpp
  tests/language-feature/0-array-2.slang
Labels: pr: non-breaking

#7413 Print CUDA version on CI servers
  .github/workflows/ci.yml
Labels: pr: non-breaking

#7393 Skip processing import declarations after errors
  source/slang/slang.cpp
  tests/bugs/missing-import-attribution.slang
Labels: pr: non-breaking

#7415 Bump the min shader model version for CUDA 12.8+
  source/compiler-core/slang-nvrtc-compiler.cpp
Labels: pr: non-breaking

#7449 "kDefaultTargetFlags" exposing TU-local entity with modules
  include/slang.h
Labels: pr: non-breaking

#7445 Disable periadic diagnostic update on language-server on CI
  source/slang/slang-language-server.cpp
  source/slang/slang-language-server.h
  tools/slang-test/test-context.cpp
Labels: pr: non-breaking

#7458 Require `override` keyword for overriding default interface methods.
  docs/user-guide/06-interfaces-generics.md
  source/slang/slang-ast-modifier.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-modifier.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-parser.cpp
  tests/diagnostics/missing-override.slang
  tests/language-feature/interfaces/default-method-generic-interface.slang
  tests/language-feature/interfaces/override-default-method.slang
Labels: pr: non-breaking

#7456 AD cleanup for 'break' replacement
  source/slang/slang-ir-autodiff-cfg-norm.cpp
Labels: pr: non-breaking

#7334 Fix slangpy not using correct slang backend
  .github/workflows/ci.yml
Labels: pr: non-breaking, Dev Opened

#7459 Update CMake version to 3.26
  .github/workflows/ci.yml
  CMakeLists.txt
Labels: pr: non-breaking

#7475 Fix out of bound buffer access in the preprocessor.
  source/compiler-core/slang-lexer.cpp
Labels: pr: non-breaking

#7377 Fix additional VVL violations
  tests/hlsl-intrinsic/texture/partial-resident-texture-combined.slang
  tests/hlsl-intrinsic/texture/partial-resident-texture.slang
  tests/hlsl-intrinsic/texture/texture-intrinsics.slang
  tests/metal/texture.slang
  tools/gfx/vulkan/vk-device.cpp
  tools/render-test/shader-input-layout.cpp
  tools/render-test/shader-input-layout.h
  tools/render-test/shader-renderer-util.cpp
  tools/render-test/shader-renderer-util.h
Labels: pr: non-breaking

#7474 Delete GFX User Guide
  CONTRIBUTING.md
  README.md
  docs/build_toc.ps1
  docs/build_toc.sh
  docs/gfx-user-guide/01-getting-started.md
  docs/gfx-user-guide/index.md
  docs/gfx-user-guide/nav.html
  docs/gfx-user-guide/toc.html
  docs/gfx-user-guide/unsupported-formats.md
Labels: pr: non-breaking

#7438 Use 1-based argument index for DebugLocalVariable
  source/slang/slang-emit-spirv-ops-debug-info-ext.h
Labels: pr: non-breaking

#7481 Fix coopvector neg intrinsic.
  source/slang/hlsl.meta.slang
  tests/cooperative-vector/neg.slang
Labels: pr: non-breaking

#7471 Fix retry logic for unit test
  .github/workflows/ci.yml
  tests/cpu-program/cpu-hello-world-test.slang
  tests/cpu-program/cpu-hello-world-test.slang.expected
  tests/expected-failure-github-runner.txt
  tests/expected-failure-no-gpu.txt
  tests/expected-failure-via-glsl.txt
  tools/slang-test/slang-test-main.cpp
  tools/slang-unit-test/unit-test-record-replay.cpp
Labels: pr: non-breaking

#7505 Add default implementation for determinant so that it works with `-target cpu`
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#7512 Document supported compiler versions in building.md
  .github/workflows/ci.yml
  docs/building.md
  extras/verify-documented-compiler-version.sh
Labels: pr: non-breaking

#7374 Fix generation of wgsl case arms
  source/slang/slang-emit-wgsl.cpp
  tests/wgsl/switch-case.slang
Labels: pr: non-breaking

#7515 Fix ambiguous reference for 'extern' and 'export'
  source/slang/slang-check-overload.cpp
  tests/library/ambiguous-extern-export-entry.slang
  tests/library/ambiguous-extern-export-lib1.slang
  tests/library/ambiguous-extern-export-lib2.slang
Labels: pr: non-breaking

#7527 Fix the invalid SPIRV decoration issue
  source/slang/slang-emit-spirv.cpp
  tests/spirv/array-stride-decoration-1.slang
  tests/spirv/array-stride-decoration-2.slang
  tests/spirv/array-stride-decoration-3.slang
  tests/spirv/array-stride-decoration-4.slang
Labels: pr: non-breaking

#7540 Move separate-debug-info arg to target options
  docs/command-line-slangc-reference.md
  source/slang/slang-options.cpp
Labels: pr: non-breaking

#7544 Fix undefined behaviour after IRInst::removeAndDeallocate
  source/slang/slang-ir.cpp
Labels: pr: non-breaking

#7422 Minimal optional constraints
  docs/user-guide/06-interfaces-generics.md
  source/slang/slang-ast-modifier.h
  source/slang/slang-ast-support-types.h
  source/slang/slang-ast-val.cpp
  source/slang/slang-ast-val.h
  source/slang/slang-check-conformance.cpp
  source/slang/slang-check-constraint.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-check-overload.cpp
  source/slang/slang-check-stmt.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-ir-lower-generic-call.cpp
  source/slang/slang-ir-lower-generic-function.cpp
  source/slang/slang-ir-specialize-dispatch.cpp
  source/slang/slang-ir-witness-table-wrapper.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-parser.cpp
  tests/language-feature/generics/where-optional-1.slang
  tests/language-feature/generics/where-optional-2.slang
  tests/language-feature/generics/where-optional-3.slang
  tests/language-feature/generics/where-optional-4.slang
  tests/language-feature/generics/where-optional-5.slang
  tests/language-feature/interface-as-rhs-error.slang
Labels: pr: new feature, pr: non-breaking

#7552 Support the GLSL/SPIR-V Built-in variable `DeviceIndex`
  docs/command-line-slangc-reference.md
  docs/user-guide/a2-01-spirv-target-specific.md
  docs/user-guide/a3-02-reference-capability-atoms.md
  source/slang/glsl.meta.slang
  source/slang/slang-capabilities.capdef
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-glsl-legalize.cpp
  source/slang/slang-ir-legalize-varying-params.h
  source/slang/slang-language-server-completion.cpp
  tests/spirv/device-index-glsl-syntax.slang
  tests/spirv/device-index-hlsl-syntax.slang
Labels: pr: non-breaking

#7545 Implement IFloat.scale for vectors, matrices
  source/slang/core.meta.slang
  tests/bugs/gh-7156-ifloat-scale.slang
Labels: pr: non-breaking

#7550 Add MLP training examples.
  examples/CMakeLists.txt
  examples/mlp-training-coopvec/README.md
  examples/mlp-training-coopvec/adam.slang
  examples/mlp-training-coopvec/common.slang
  examples/mlp-training-coopvec/kernels.slang
  examples/mlp-training-coopvec/mlp-training-coopvec.cpp
  examples/mlp-training-coopvec/mlp.slang
  examples/mlp-training-coopvec/mlvec.slang
  examples/mlp-training-coopvec/network.slang
  examples/mlp-training/README.md
  examples/mlp-training/adam.slang
  examples/mlp-training/common.slang
  examples/mlp-training/kernels.slang
  examples/mlp-training/mlp-training.cpp
  examples/mlp-training/mlp_sw.slang
  examples/mlp-training/mlvec_sw.slang
  examples/mlp-training/network.slang
  source/slang/core.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-ast-modifier.h
  source/slang/slang-check-conversion.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-shader.cpp
  tests/language-feature/capability/capabilitySimplification2.slang
Labels: pr: non-breaking

#7563 Emit sample index when constructing a `OpImageTexelPointer`
  source/slang/slang-emit-spirv.cpp
  tests/compute/spirv-array-texel-pointer-atomic.slang
  tests/compute/spirv-multisampled-array-texel-pointer-atomic.slang
Labels: pr: non-breaking
