Repository shader-slang/slang, pull requests merged in 2025-01, with the labels that each got.

#5943 Fix reflection for metal vector [[id]] location.
  source/slang/slang-type-layout.cpp
  tests/metal/vector-argument-buffer-layout.slang
Labels: pr: non-breaking

#5975 Add missing IR_LEAF_ISA for MetalMeshType
  source/slang/slang-ir.h
Labels: pr: non-breaking

#5978 Fixed Session::queryInterface not returning OK when querying for IUnknown/ISlangUnknown
  source/slang/slang.cpp
Labels: pr: non-breaking

#5980 Allow explicit test root
  source/core/slang-io.cpp
  tools/slang-test/options.cpp
  tools/slang-test/options.h
  tools/slang-test/slang-test-main.cpp
Labels: pr: non-breaking

#5956 Fix parameter location reflection for pure data paramblocks.
  source/slang/slang-ir-metadata.cpp
  tools/slang-unit-test/unit-test-parameter-usage-reflection.cpp
Labels: pr: non-breaking

#5945 Create DirectDeclRef when creating Decl to prevent invalid dedup.
  source/slang/slang-ast-base.cpp
  source/slang/slang-ast-base.h
  source/slang/slang-ast-builder.h
  source/slang/slang.cpp
  source/slang/slang.natvis
  tools/slang-unit-test/unit-test-module-ptr.cpp
Labels: pr: non-breaking

#6003 Make 'shared' keyword map to 'groupshared' in GLSL mode
  source/slang/slang-parser.cpp
Labels: pr: non-breaking

#5998 CI: Build the full slang-wasm.[js|wasm] targets instead of just the s…
  .github/workflows/ci.yml
Labels: pr: non-breaking

#6006 Fix GLSL mix(T,T,bool) SPIR-V output
  source/slang/glsl.meta.slang
Labels: pr: non-breaking

#6009 Add support for textureLod with sampler2DArrayShadow in GLSL compatibility mode
  source/slang/glsl.meta.slang
Labels: pr: non-breaking

#5993 Properly set D3D12SDKPath
  tools/slang-test/slang-test-main.cpp
Labels: pr: non-breaking

#6001 Use disassemble API from SPIRV-Tools
  source/compiler-core/slang-downstream-compiler.h
  source/compiler-core/slang-glslang-compiler.cpp
  source/compiler-core/slang-json-rpc-connection.cpp
  source/slang-glslang/slang-glslang.cpp
  source/slang-glslang/slang-glslang.h
  source/slang-llvm/slang-llvm.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-spirv-val.cpp
  source/slang/slang-spirv-val.h
  tests/diagnostics/illegal-func-decl.slang
  tests/language-feature/capability/capability3.slang
  tests/language-feature/capability/capability7.slang
  tests/language-feature/capability/conflicting-profile-stage-for-entry-point.slang
Labels: pr: non-breaking

#5984 Fix some robustness issues in the examples
  examples/hello-world/main.cpp
  examples/ray-tracing-pipeline/main.cpp
  examples/ray-tracing/main.cpp
  tests/expected-example-failure-github.txt
  tools/gfx/d3d12/d3d12-device.cpp
Labels: pr: non-breaking

#5996 Add example showing how to use Slang/WASM
  examples/wgpu-slang-wasm/README.md
  examples/wgpu-slang-wasm/example.js
  examples/wgpu-slang-wasm/index.html
  examples/wgpu-slang-wasm/shader.slang
Labels: pr: non-breaking

#5919 Lower varying parameters as pointers instead of SSA values.
  source/slang/core.meta.slang
  source/slang/glsl.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-ast-decl.h
  source/slang/slang-ast-dump.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-cpp.cpp
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-hlsl.cpp
  source/slang/slang-emit-hlsl.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-fix-entrypoint-callsite.cpp
  source/slang/slang-ir-fix-entrypoint-callsite.h
  source/slang/slang-ir-glsl-legalize.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-legalize-varying-params.cpp
  source/slang/slang-ir-legalize-varying-params.h
  source/slang/slang-ir-lower-buffer-element-type.cpp
  source/slang/slang-ir-metal-legalize.cpp
  source/slang/slang-ir-resolve-varying-input-ref.cpp
  source/slang/slang-ir-resolve-varying-input-ref.h
  source/slang/slang-ir-translate-glsl-global-var.cpp
  source/slang/slang-ir-vk-invert-y.cpp
  source/slang/slang-ir-wgsl-legalize.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-parser.cpp
  tests/bugs/gh-841.slang
  tests/bugs/vk-structured-buffer-load.hlsl
  tests/cross-compile/glsl-generic-in.slang
  tests/glsl-intrinsic/fragment-processing/fragment-processing.slang
  tests/glsl/matrix-mul.slang
  tests/hlsl-intrinsic/fragment-interpolate.slang
  tests/pipeline/rasterization/get-attribute-at-vertex-nv.slang
  tests/pipeline/rasterization/get-attribute-at-vertex-nv.slang.glsl
  tests/pipeline/rasterization/get-attribute-at-vertex-nv.slang.hlsl
  tests/pipeline/rasterization/get-attribute-at-vertex.slang
  tests/pipeline/rasterization/varying-to-inout.slang
  tests/spirv/array-uniform-param.slang
  tests/spirv/matrix-vertex-input.slang
  tests/spirv/nested-entrypoint.slang
  tests/spirv/optional-vertex-output.slang
  tests/vkray/anyhit.slang
  tests/vkray/anyhit.slang.glsl
  tools/render-test/render-test-main.cpp
Labels: pr: non-breaking

#5973 Add backtraces to examples
  .github/workflows/ci-examples.sh
  examples/CMakeLists.txt
  examples/autodiff-texture/main.cpp
  examples/cpu-com-example/main.cpp
  examples/cpu-hello-world/main.cpp
  examples/example-base/example-base.h
  examples/example-main/main.cpp
  examples/example-winmain/main.cpp
  examples/gpu-printing/main.cpp
  examples/hello-world/main.cpp
  examples/model-viewer/main.cpp
  examples/nv-aftermath-example/main.cpp
  examples/platform-test/main.cpp
  examples/ray-tracing-pipeline/main.cpp
  examples/ray-tracing/main.cpp
  examples/reflection-api/main.cpp
  examples/shader-object/main.cpp
  examples/shader-toy/main.cpp
  examples/stacktrace-windows/common.cpp
  examples/stacktrace-windows/common.h
  examples/triangle/main.cpp
  tools/platform/window.h
Labels: pr: non-breaking

#6021 slang-test: Ensure runtime is consistent
  tools/CMakeLists.txt
Labels: pr: non-breaking

#6004 Add SampleCmpLevel intrinsics
  source/slang/hlsl.meta.slang
  tests/cross-compile/glsl-samplecmplevelzero.slang
  tests/hlsl-intrinsic/texture-lod-shadow.slang
  tests/hlsl-intrinsic/texture/texture-intrinsics.slang
  tests/metal/texture-sampler-less.slang
  tests/metal/texture.slang
  tests/spirv/sampler-shadow.slang
Labels: pr: non-breaking

#6030 Add parentheses to make precedence explicit
  source/slang/slang-emit-c-like.cpp
  tests/wgsl/operator-precedence.slang
  tests/wgsl/operator-precedence.slang.expected.txt
Labels: pr: non-breaking

#6019 Pass compiler specific args to GCC and Visual Studio too
  source/compiler-core/slang-gcc-compiler-util.cpp
  source/compiler-core/slang-visual-studio-compiler-util.cpp
Labels: pr: non-breaking

#5866 [Auto-diff] Overhaul auto-diff type tracking + Overhaul dynamic dispatch for differentiable functions
  source/slang/slang-check-decl.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-autodiff-fwd.cpp
  source/slang/slang-ir-autodiff-fwd.h
  source/slang/slang-ir-autodiff-pairs.cpp
  source/slang/slang-ir-autodiff-primal-hoist.cpp
  source/slang/slang-ir-autodiff-rev.cpp
  source/slang/slang-ir-autodiff-transcriber-base.cpp
  source/slang/slang-ir-autodiff-transpose.h
  source/slang/slang-ir-autodiff-unzip.cpp
  source/slang/slang-ir-autodiff-unzip.h
  source/slang/slang-ir-autodiff.cpp
  source/slang/slang-ir-autodiff.h
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-link.cpp
  source/slang/slang-ir-lower-generics.cpp
  source/slang/slang-ir-specialize.cpp
  source/slang/slang-ir-specialize.h
  source/slang/slang-lower-to-ir.cpp
  tests/autodiff/dynamic-dispatch-material.slang
  tests/autodiff/dynamic-dispatch-material.slang.expected.txt
  tests/autodiff/material2/DiffuseMaterial.slang
  tests/autodiff/material2/GlossyMaterial.slang
  tests/autodiff/material2/MxLayeredMaterial.slang
Labels: pr: non-breaking

#6051 Upgrade actions/upload-artifact from v3 to v4
  .github/workflows/ci.yml
Labels: pr: non-breaking

#6035 Fix implicit string conversion breaking NativeStrings
  source/slang/core.meta.slang
  source/slang/slang-check-conversion.cpp
  tests/cpu-program/string-passing.slang
  tests/cpu-program/string-passing.slang.expected
Labels: pr: non-breaking

#6052 Support a storage class, NodePayloadAMDX, for SPIRV work-graphs
  source/slang/core.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-emit-spirv-ops.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-type-system-shared.h
  tests/workgraphs/consumer.slang
Labels: pr: non-breaking

#6018 Add CalculateLevelOfDetail* overloads for comparison samplers
  source/slang/hlsl.meta.slang
  tests/cross-compile/glsl-calculatelevelofdetail.slang
  tests/hlsl-intrinsic/texture/texture-calculate-level-of-detail.slang
  tests/metal/texture-sampler-less.slang
  tests/metal/texture.slang
Labels: pr: non-breaking

#6056 Add exhaustive associativity test for WGSL
  source/slang/slang-emit-c-like.cpp
  tests/wgsl/associativity.slang
  tests/wgsl/associativity.slang.expected.txt
Labels: pr: non-breaking

#6028 Initial implementation of SP#015 `DescriptorHandle<T>`.
  docs/proposals/015-bindless-t.md
  docs/proposals/015-descriptor-handle.md
  docs/user-guide/03-convenience-features.md
  docs/user-guide/toc.html
  include/slang.h
  source/slang/hlsl.meta.slang
  source/slang/slang-ast-type.h
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-cpp.h
  source/slang/slang-emit-hlsl.cpp
  source/slang/slang-emit-metal.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit-wgsl.cpp
  source/slang/slang-emit-wgsl.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-float-non-uniform-resource-index.cpp
  source/slang/slang-ir-float-non-uniform-resource-index.h
  source/slang/slang-ir-glsl-legalize.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-layout.cpp
  source/slang/slang-ir-legalize-types.cpp
  source/slang/slang-ir-lower-combined-texture-sampler.cpp
  source/slang/slang-ir-lower-dynamic-resource-heap.cpp
  source/slang/slang-ir-lower-dynamic-resource-heap.h
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-ir.cpp
  source/slang/slang-ir.h
  source/slang/slang-lookup.cpp
  source/slang/slang-mangle.cpp
  source/slang/slang-options.cpp
  source/slang/slang-type-layout.cpp
  tests/compute/nonuniformres-array-of-textures.slang
  tests/compute/nonuniformres-nested-rwstructuredbuf.slang
  tests/language-feature/descriptor-handle/desc-handle-0.slang
  tests/language-feature/descriptor-handle/desc-handle-1.slang
  tests/language-feature/descriptor-handle/desc-handle-2.slang
  tests/language-feature/descriptor-handle/desc-handle-3.slang
Labels: pr: non-breaking

#6042 Fix Metal type layout reflection for nested parameter blocks.
  source/slang/slang-type-layout.cpp
  source/slang/slang-type-layout.h
  tests/metal/nested-parameter-block-reflection.slang
Labels: pr: non-breaking

#6047 Fix potential test failures due to SPIRV validation failure
  tests/diagnostics/uninitialized-fields-delegated.slang
  tests/diagnostics/uninitialized-fields.slang
  tests/diagnostics/uninitialized-globals.slang
  tests/diagnostics/uninitialized-local-variables.slang
  tests/diagnostics/uninitialized-out-parameters.slang
  tests/diagnostics/uninitialized-struct-from-constructor.slang
  tests/diagnostics/uninitialized-use-functions.slang
Labels: pr: non-breaking

#6022 Add overload for select to handle Optional<T>
  source/slang/core.meta.slang
Labels: pr: non-breaking

#6054 Fix `markNonContextParamsAsSideEffectFree`.
  source/slang/slang-ir-autodiff-rev.cpp
  source/slang/slang-ir-autodiff-unzip.cpp
  source/slang/slang-ir-inst-defs.h
  tests/autodiff/max-iters.slang
  tests/autodiff/property.slang
  tests/autodiff/trivial-primal.slang
Labels: pr: non-breaking

#6055 Fix CUDA reflection for acceleration structure handle size.
  source/slang/slang-reflection-json.cpp
  source/slang/slang-type-layout.cpp
  source/slang/slang-type-layout.h
  tests/reflection/acceleration-structure.slang
Labels: pr: non-breaking

#6071 Find OptiX headers
  docs/cuda-target.md
  source/compiler-core/slang-nvrtc-compiler.cpp
Labels: pr: non-breaking

#6076 Don't initialize temp var for out parameters when generating the backward diff function
  source/slang/slang-ir-autodiff-rev.cpp
  tests/autodiff/out-parameters-2.slang
Labels: pr: non-breaking

#6077 Fix simplify if-else
  source/slang/slang-ir-simplify-cfg.cpp
  tests/bugs/simplify-if-else.slang
Labels: pr: non-breaking

#6067 Fix #5354, change diagnostic definition error message and expect output in test
  source/slang/slang-diagnostic-defs.h
  tests/diagnostics/missing-return.slang.expected
Labels: pr: non-breaking

#5963 Implement specialization constant support in numthreads / local_size
  source/slang/slang-ast-modifier.h
  source/slang/slang-check-impl.h
  source/slang/slang-check-modifier.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-ir-collect-global-uniforms.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-legalize-varying-params.cpp
  source/slang/slang-ir-metal-legalize.cpp
  source/slang/slang-ir-translate-glsl-global-var.cpp
  source/slang/slang-ir-util.cpp
  source/slang/slang-ir-util.h
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-parser.cpp
  source/slang/slang-reflection-api.cpp
  tests/glsl/compute-shader-layout-id.slang
  tests/spirv/spec-constant-numthreads.slang
Labels: pr: non-breaking

#6062 Fix formatting and documentation on DescriptorHandle.
  cmake/SlangTarget.cmake
  source/slang/hlsl.meta.slang
Labels: pr: non-breaking

#6084 Fix issue with specialization using arithmetic expressions
  source/slang/slang-ir-specialize.cpp
  source/slang/slang.cpp
Labels: pr: non-breaking

#6089 Fix optix varying legalization.
  source/slang/slang-ir-legalize-varying-params.cpp
  tests/cuda/optix-hit-attributes.slang
Labels: pr: non-breaking

#6063 Reuse code for Metal and WGSL entry point legalization
  source/slang/slang-ir-legalize-varying-params.cpp
  source/slang/slang-ir-legalize-varying-params.h
  source/slang/slang-ir-metal-legalize.cpp
  source/slang/slang-ir-wgsl-legalize.cpp
Labels: pr: non-breaking

#6059 Implement AnyValue marshalling for 8-bit integers
  source/slang/slang-ir-any-value-marshalling.cpp
  tests/compute/pack-any-value-8bit.slang
  tests/compute/pack-any-value-8bit.slang.expected.txt
Labels: pr: non-breaking

#6044 Emit errors when seeing a matrix with row/col count of 1
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit.cpp
Labels: pr: non-breaking

#6098 Inline global constants that contains opaque handles for legalization.
  source/slang/slang-ast-decl.h
  source/slang/slang-check-conformance.cpp
  source/slang/slang-check-decl.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-legalize-global-values.cpp
  source/slang/slang-ir-legalize-global-values.h
  source/slang/slang-ir-legalize-types.cpp
  tests/bugs/gh-4874-2.slang
  tests/bugs/gh-4874.slang
  tests/diagnostics/variable-redeclaration.slang.expected
Labels: pr: non-breaking

#6101 Fix argument buffer tier2 layout computation.
  source/slang/slang-type-layout.cpp
  tools/slang-unit-test/unit-test-argument-buffer-tier-2-reflection.cpp
Labels: pr: non-breaking

#6103 support SV_ViewIndex for Metal
  source/slang/slang-ir-legalize-varying-params.cpp
  tests/hlsl-intrinsic/system-values-draw-parameters.slang
Labels: pr: non-breaking

#6068 Implement Packed Dot Product intrinsics
  source/slang/hlsl.meta.slang
  tests/hlsl-intrinsic/dot-accumulate.slang
  tests/hlsl-intrinsic/dot-accumulate.slang.expected.txt
Labels: pr: non-breaking

#6070 C-like emitter: Add parenthesis when combining relational and bitwise…
  source/slang/slang-emit-c-like.cpp
  tests/metal/byte-address-buffer.slang
Labels: pr: non-breaking

#6110 Fix cyclic lookups with UnscopedEnums
  source/slang/slang-ast-support-types.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-expr.cpp
  source/slang/slang-check-impl.h
  source/slang/slang-lookup.cpp
  source/slang/slang-lookup.h
  tests/language-feature/enums/unscoped-enum-explicit-type-2.slang
Labels: pr: non-breaking

#6099 Fix resource specialization issue where store insts from inlined calls are not considered properly.
  source/slang/slang-ir-specialize-resources.cpp
Labels: pr: non-breaking

#6106 Move global variable initialization into entry points for WGSL
  source/slang/slang-emit.cpp
  tests/wgsl/global-call.slang
  tests/wgsl/global-call.slang.expected.txt
Labels: pr: non-breaking

#6111 Fix prebound parameter pack - argument list matching logic.
  source/slang/slang-ast-decl-ref.cpp
  source/slang/slang-check-overload.cpp
  tests/language-feature/generics/prebound-variadic-pack.slang
  tests/language-feature/generics/variadic-tuple-field.slang
Labels: pr: non-breaking

#6114 Fix `-capability` arg in SPIRV debug command line output.
  source/slang/slang-compiler-options.cpp
  tests/spirv/cmd-arg-debug-info.slang
Labels: pr: non-breaking

#6116 Fix WGSL entry point parameter location attributes
  source/slang/slang-ir-legalize-varying-params.cpp
  tests/metal/nested-struct-fragment-input.slang
  tests/metal/stage-in-2.slang
  tests/wgsl/nested-varying-input.slang
Labels: pr: non-breaking

#6066 Fix nullptr in generic specialization
  source/slang/slang-ir-clone.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-link.cpp
  source/slang/slang-ir.cpp
Labels: pr: non-breaking

#6094 Avoid using the backend validation when using test server
  tools/render-test/options.cpp
  tools/render-test/options.h
  tools/render-test/render-test-main.cpp
  tools/slang-test/slang-test-main.cpp
Labels: pr: non-breaking

#6123 Fix interface requirement lowering for generic accessors
  source/slang/slang-lower-to-ir.cpp
  tests/autodiff/generic-accessors.slang
Labels: pr: non-breaking

#6115 Refactor _Texture to constrain on texel types.
  source/slang/glsl.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-check-inheritance.cpp
  source/slang/slang-emit-cpp.cpp
  source/slang/slang-ir-peephole.cpp
  tests/diagnostics/illegal-texel-type.slang
  tests/glsl-intrinsic/compute-derivative/intrinsic-derivative-function-in-compute.slang
  tests/glsl-intrinsic/intrinsic-texture.slang
  tests/language-feature/capability/intrinsic-texture-ignore-capability.slang
  tests/metal/texture-sampler-less.slang
  tests/metal/texture.slang
  tests/wgsl/texture-gather.slang
  tests/wgsl/texture-load.slang
  tests/wgsl/texture-sampler-less.slang
  tests/wgsl/texture-storage.slang
  tests/wgsl/texture.slang
Labels: pr: breaking change

#6124 Allow __subscript<T> syntax.
  source/slang/slang-parser.cpp
  tests/language-feature/generics/generic-subscript.slang
Labels: pr: non-breaking

#6107 Add groupshared atomic array test.
  tests/spirv/groupshared-array-atomic.slang
  tools/render-test/render-test-main.cpp
Labels: pr: non-breaking

#6122 Add diagnostic for function body followed by a `;`.
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-parser.cpp
  tests/language-feature/empty-struct-method.slang
Labels: pr: non-breaking

#6121 Fix circularity issue when checking multiple generic interface constraints.
  source/slang/slang-check-inheritance.cpp
  tests/language-feature/generics/multi-generic-interface-constraint.slang
Labels: pr: non-breaking

#6095 test-server should use d3d12core.dll from bin directory
  tests/expected-failure-github.txt
  tests/hlsl-intrinsic/texture/partial-resident-texture.slang
  tools/test-server/test-server-main.cpp
Labels: pr: non-breaking

#5981 Implement Quad Control intrinsics
  docs/user-guide/a3-02-reference-capability-atoms.md
  source/slang/core.meta.slang
  source/slang/hlsl.meta.slang
  source/slang/slang-ast-modifier.h
  source/slang/slang-capabilities.capdef
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-c-like.h
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-glsl.h
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-insts.h
  source/slang/slang-lower-to-ir.cpp
  tests/hlsl-intrinsic/quad-control/quad-control-comp-functionality.slang
  tests/hlsl-intrinsic/quad-control/quad-control-comp-functionality.slang.expected.txt
  tests/hlsl-intrinsic/quad-control/quad-control-frag-many-entry-points.slang
  tests/hlsl-intrinsic/quad-control/quad-control-frag.slang
Labels: pr: non-breaking

#6126 Make -depfile work for binary slang-modules
  source/slang/slang-compiler.cpp
Labels: pr: non-breaking

#6127 Fix reinterpret<T> for 64-bit types
  source/slang/slang-ir-any-value-marshalling.cpp
Labels: pr: non-breaking

#6134 Fix def-use issue from multi-level break elimination
  source/slang/slang-ir-autodiff-cfg-norm.cpp
  source/slang/slang-ir-eliminate-multilevel-break.cpp
  source/slang/slang-ir-util.cpp
  source/slang/slang-ir-util.h
  tests/autodiff/loop-mutating-array.slang
Labels: pr: non-breaking

#6129 Fix generic witness table SequentialIDDecorations
  source/slang/slang-ir-specialize-dispatch.cpp
Labels: pr: non-breaking

#6143 Catch all exceptions from loadModule* API calls.
  source/slang/slang.cpp
Labels: pr: non-breaking

#6131 Remove unnecessary parameters from Metal entry point signature
  source/slang/slang-emit.cpp
  source/slang/slang-ir-entry-point-uniforms.cpp
  source/slang/slang-ir-explicit-global-context.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-legalize-types.cpp
  source/slang/slang-ir-strip-cached-dict.cpp
  source/slang/slang-ir-strip-cached-dict.h
  source/slang/slang-ir-strip-legalization-insts.cpp
  source/slang/slang-ir-strip-legalization-insts.h
  source/slang/slang-ir-strip-witness-tables.cpp
  source/slang/slang-ir-strip-witness-tables.h
  tests/metal/multi-entry-point-params.slang
Labels: pr: non-breaking

#6141 Use SPIRV integer vector dot product instructions
  source/slang/hlsl.meta.slang
  tests/hlsl-intrinsic/vector-dot-int.slang
  tests/hlsl-intrinsic/vector-dot-int.slang.expected.txt
Labels: pr: non-breaking

#6093 Add validation for destination of atomic operations
  source/slang/glsl.meta.slang
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit.cpp
  source/slang/slang-ir-insts.h
  source/slang/slang-ir-specialize-address-space.cpp
  source/slang/slang-ir-spirv-legalize.cpp
  source/slang/slang-ir-validate.cpp
  source/slang/slang-ir-validate.h
  tests/glsl-intrinsic/atomic/invalidDest.slang
Labels: pr: non-breaking

#6152 Cache and reuse glsl module.
  docs/user-guide/08-compiling.md
  include/slang.h
  source/slang-record-replay/record/parameter-recorder.cpp
  source/slang-record-replay/record/parameter-recorder.h
  source/slang-record-replay/record/slang-global-session.cpp
  source/slang-record-replay/record/slang-global-session.h
  source/slang-record-replay/replay/decoder-consumer.h
  source/slang-record-replay/replay/decoder-helper.cpp
  source/slang-record-replay/replay/json-consumer.cpp
  source/slang-record-replay/replay/json-consumer.h
  source/slang-record-replay/replay/parameter-decoder.cpp
  source/slang-record-replay/replay/parameter-decoder.h
  source/slang-record-replay/replay/replay-consumer.cpp
  source/slang-record-replay/replay/replay-consumer.h
  source/slang-record-replay/replay/slang-decoder.cpp
  source/slang-record-replay/util/record-format.h
  source/slang/slang-api.cpp
  source/slang/slang-compiler.h
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-language-server.cpp
  source/slang/slang.cpp
  source/slangc/main.cpp
  tools/slang-test/test-context.cpp
  tools/slang-unit-test/unit-test-glsl-compile.cpp
  tools/test-server/test-server-main.cpp
Labels: pr: non-breaking

#6162 Fix incorrect resolve of specialization instance
  source/slang/slang-ir-use-uninitialized-values.cpp
  tests/diagnostics/uninitialized-generic.slang
  tests/diagnostics/uninitialized-local-variables.slang
Labels: pr: non-breaking

#6158 Fix static build and install
  CMakeLists.txt
  cmake/SlangTarget.cmake
  docs/building.md
  prelude/CMakeLists.txt
  source/compiler-core/CMakeLists.txt
  source/core/CMakeLists.txt
  source/slang-rt/CMakeLists.txt
  source/slang/CMakeLists.txt
  tools/CMakeLists.txt
Labels: pr: non-breaking

#6169 Improve error message on generic value parameters decls
  source/slang/slang-ast-support-types.h
  source/slang/slang-check-decl.cpp
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-syntax.cpp
  tests/diagnostics/generic-value-parameter-must-have-type.slang
Labels: pr: non-breaking

#6163 Add bgra8 format
  include/slang-image-format-defs.h
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-emit-glsl.cpp
  source/slang/slang-emit-spirv.cpp
  source/slang/slang-emit-wgsl.cpp
  source/slang/slang-emit-wgsl.h
  tests/diagnostics/image-format-unsupported-by-backend.slang
  tests/hlsl-intrinsic/quad-control/quad-control-comp-functionality.slang
  tests/wgsl/texture-storage.slang
Labels: pr: non-breaking

#6160 Add intptr_t abs/min/max operations for CPU & CUDA targets
  prelude/slang-cpp-scalar-intrinsics.h
  prelude/slang-cuda-prelude.h
  source/slang/slang-intrinsic-expand.cpp
Labels: pr: non-breaking

#6153 Some usability improvements to formatting script
  extras/formatting.sh
Labels: pr: non-breaking

#6168 Fix depth texture sampling on Metal.
  source/slang/hlsl.meta.slang
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-emit-metal.cpp
  source/slang/slang-ir-inst-defs.h
  source/slang/slang-ir-metal-legalize.cpp
  source/slang/slang-ir.cpp
  tests/metal/depth-texture.slang
  tests/metal/texture.slang
Labels: pr: non-breaking

#6190 Using sparse checkout for MDL-SDK
  .github/workflows/benchmark.yml
  .github/workflows/push-benchmark-results.yml
Labels: pr: non-breaking

#6177 Fix an incorrect iteration with a workList
  source/slang/slang-ir-variable-scope-correction.cpp
Labels: pr: non-breaking

#6198 Properly plumbing layout for global varyings.
  source/slang/slang-check-decl.cpp
  source/slang/slang-check-shader.cpp
  source/slang/slang-ir-translate-glsl-global-var.cpp
  source/slang/slang-lower-to-ir.cpp
  source/slang/slang-parameter-binding.cpp
  tests/glsl/in-layout.slang
Labels: pr: non-breaking

#6161 Add an example for reflection of parameter blocks
  examples/CMakeLists.txt
  examples/reflection-parameter-blocks/README.md
  examples/reflection-parameter-blocks/common.slang
  examples/reflection-parameter-blocks/main.cpp
  examples/reflection-parameter-blocks/shader.slang
  examples/reflection-parameter-blocks/vulkan-api.cpp
  examples/reflection-parameter-blocks/vulkan-api.h
Labels: pr: non-breaking

#6178 Fix CompileOptions defined in targetDesc not loaded into TargetRequest.
  source/slang/slang.cpp
  tools/slang-unit-test/unit-test-type-conformance.cpp
Labels: pr: non-breaking

#6196 Delete invalid ASSERT in `isTypeOperandEqual`.
  source/slang/slang-ir.cpp
  tests/bugs/gh-6194.slang
Labels: pr: non-breaking

#6186 Added const version for the operator[] in Matrix
  prelude/slang-cpp-types-core.h
Labels: pr: non-breaking

#6173 Allow requiring glsl language extensions on structs
  source/slang/slang-emit-c-like.cpp
  source/slang/slang-lower-to-ir.cpp
  tests/language-feature/glsl-extension.slang
Labels: pr: non-breaking

#6156 Add slangpy proposal
  docs/proposals/016-slangpy.md
Labels: pr: non-breaking, SPF:Proposal

#6209 Proposal for Cooperative Vector in Slang
  docs/proposals/019-cooperative-vector.md
Labels: pr: non-breaking

#6205 Fix UIntSet calcSubtract to handle mismatched buffer sizes
  source/core/slang-uint-set.cpp
  tests/language-feature/capability/profile-implicitly-upgraded.slang
Labels: pr: non-breaking

#6204 Fix exact-match witness synthesis for static functions
  source/slang/slang-check-decl.cpp
  tests/language-feature/interfaces/non-static-method-implemented-by-static.slang
  tests/language-feature/interfaces/non-static-method-implemented-by-static.slang.expected.txt
  tests/language-feature/interfaces/static-method-not-implemented.slang
Labels: pr: non-breaking

#6182 Implement WaveMultiPrefix* for SPIRV and GLSL
  docs/user-guide/a3-02-reference-capability-atoms.md
  source/slang/hlsl.meta.slang
  source/slang/slang-capabilities.capdef
  tests/hlsl-intrinsic/wave-multi-prefix-scalar-functional.slang
  tests/hlsl-intrinsic/wave-multi-prefix-scalar-functional.slang.expected.txt
  tests/hlsl-intrinsic/wave-multi-prefix.slang
  tests/hlsl-intrinsic/wave-multi-prefix.slang.expected.txt
  tests/language-feature/capability/capabilitySimplification1.slang
  tests/language-feature/capability/capabilitySimplification3.slang
Labels: pr: non-breaking

#6212 Fix loophole in hoisting where an `OpVar`'s uses might not be properly registered for replacement
  source/slang/slang-ir-autodiff-primal-hoist.cpp
  source/slang/slang-ir-autodiff-primal-hoist.h
Labels: pr: non-breaking

#6215 Fix the type coerce issue
  source/slang/slang-check-decl.cpp
  tests/language-feature/initializer-lists/inheritance-generic.slang
Labels: pr: non-breaking

#6207 Fix combined sampler documentation and warning
  docs/user-guide/a2-01-spirv-target-specific.md
  source/slang/slang-diagnostic-defs.h
  source/slang/slang-parameter-binding.cpp
  tests/diagnostics/hlsl-to-vulkan-sampler-diagnostic.hlsl
  tests/diagnostics/hlsl-to-vulkan-sampler-diagnostic.hlsl.1.expected
  tests/diagnostics/hlsl-to-vulkan-sampler-diagnostic.hlsl.expected
  tests/diagnostics/hlsl-to-vulkan-shift-diagnostic.hlsl
  tests/diagnostics/hlsl-to-vulkan-shift-diagnostic.hlsl.expected
  tests/diagnostics/vk-bindings.slang.expected
Labels: pr: non-breaking

#6224 Fix ConstantIntVal::toText when the val is a enum.
  source/slang/slang-ast-decl.h
  source/slang/slang-ast-val.cpp
  source/slang/slang-check-decl.cpp
  tests/language-server/typename-enum-intval.slang
Labels: pr: non-breaking

#6227 Add coop-vec insts to non-differentiable insts list
  source/slang/slang-ir-autodiff-fwd.cpp
Labels: pr: non-breaking

#6231 Declare `VariablePointers` capability when needed.
  source/slang/slang-emit-spirv.cpp
  tests/spirv/variable-pointer.slang
Labels: pr: non-breaking

#6202 [Docs] Auto-diff documentation overhaul
  docs/user-guide/07-autodiff.md
  docs/user-guide/toc.html
  source/slang/core.meta.slang
  source/slang/diff.meta.slang
Labels: pr: non-breaking

#6233 Distribute slang-glsl-module.bin in release packages.
  CMakeLists.txt
  include/slang.h
  source/slang-glsl-module/CMakeLists.txt
  source/slang-glsl-module/slang-embedded-glsl-module.cpp
  source/slang-record-replay/util/emum-to-string.h
  source/slang/slang-api.cpp
  source/slang/slang-options.cpp
  source/slangc/CMakeLists.txt
Labels: pr: non-breaking

#6193 Respect per-target debug options
  source/slang/slang-emit.cpp
  source/slang/slang-ir-strip-debug-info.cpp
  source/slang/slang-ir-strip-debug-info.h
  source/slang/slang.cpp
Labels: pr: non-breaking
